import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { HeroPortrait } from "../../components/heroes/HeroPortrait";
import { BackButton, Panel, SectionTitle, SegmentedTabs, colors } from "../../components/ui";
import { CLASSES } from "../../data/classes/classes";
import { CLASS_CODEX, RACE_CODEX } from "../../data/codex/heroCodex";
import { RACES } from "../../data/races/races";
import { HERO_SKILLS } from "../../data/skills/heroSkills";
import type { AttributeKey } from "../../game/attributes/types";
import { getSkillDescriptionLines } from "../../game/combat/skillDescription";
import type { Modifier } from "../../game/modifiers/types";
import type { ClassId, RaceId } from "../../game/heroes/types";
import { getRaceNameColor } from "../../ui/raceColors";
import { getModifierTargetLabel } from "../../ui/modifierLabels";
import { useGuild } from "../../state/GuildContext";
import { BASE_CLASS_IDS, BASE_RACE_IDS, STORY_RACE_UNLOCKS } from "../../game/monetization/contentUnlockService";

type CodexTab = "Races" | "Classes";
const ATTRIBUTE_LABELS: Record<AttributeKey, string> = { strength: "STR", dexterity: "DEX", constitution: "CON", intelligence: "INT", wisdom: "WIS", charisma: "CHA" };
const modifierText = (modifier: Modifier) => `${getModifierTargetLabel(modifier.target)} ${modifier.value >= 0 ? "+" : ""}${modifier.operation === "percentage" ? `${Math.round(modifier.value * 100)}%` : modifier.value}`;
function Label({ children }: React.PropsWithChildren) { return <Text style={styles.label}>{children}</Text>; }

function Header({ portrait, title, subtitle, color, expanded }: { portrait: React.ReactNode; title: string; subtitle: string; color?: string; expanded: boolean }) {
  return <View style={styles.header}>{portrait}<View style={styles.headerText}><Text style={[styles.entryTitle, color ? { color } : undefined]}>{title}</Text><Text style={styles.meta}>{subtitle}</Text></View><Text style={styles.chevron}>{expanded ? "-" : "+"}</Text></View>;
}

function RaceEntry({ raceId, unlocked }: { raceId: RaceId; unlocked: boolean }) {
  const [expanded, setExpanded] = useState(false); const race = RACES[raceId]; const lore = RACE_CODEX[raceId]; const exampleClass = lore.recommendedClassIds[0] ?? "warrior";
  const source = BASE_RACE_IDS.includes(raceId) ? "Starting people" : raceId in STORY_RACE_UNLOCKS ? `Story unlock · ${STORY_RACE_UNLOCKS[raceId as keyof typeof STORY_RACE_UNLOCKS].replace(/_/g, " ")}` : "50-gem charter unlock";
  return <Pressable accessibilityRole="button" accessibilityState={{ expanded }} onPress={() => setExpanded(!expanded)}><Panel style={[styles.entry, !unlocked && styles.locked]}><Header portrait={<HeroPortrait raceId={raceId} classId={exampleClass} gender="female" variant={0} label={`${race.name} example`} size={50} />} title={race.name} subtitle={`${lore.epithet} · ${unlocked ? "AVAILABLE" : "LOCKED"}`} color={getRaceNameColor(raceId)} expanded={expanded} />{expanded && <View style={styles.details}><Text style={styles.source}>{source}</Text><Text style={styles.body}>{lore.overview}</Text><Label>HOMELAND</Label><Text style={styles.body}>{lore.homeland}</Text><Label>RECOMMENDED CLASSES</Label><View style={styles.chips}>{lore.recommendedClassIds.map((id) => <Text key={id} style={styles.chip}>{CLASSES[id].name}</Text>)}</View><Label>ADVENTURING STYLE</Label><Text style={styles.body}>{lore.playstyle}</Text><Label>RACIAL MODIFIERS</Label><View style={styles.chips}>{race.modifiers.map((modifier, index) => <Text key={`${modifier.target}-${index}`} style={styles.chip}>{modifierText(modifier)}</Text>)}</View></View>}</Panel></Pressable>;
}

function ClassEntry({ classId, unlocked }: { classId: ClassId; unlocked: boolean }) {
  const [expanded, setExpanded] = useState(false); const heroClass = CLASSES[classId]; const lore = CLASS_CODEX[classId]; const growth = Object.entries(heroClass.attributeGrowthWeights) as [AttributeKey, number][];
  return <Pressable accessibilityRole="button" accessibilityState={{ expanded }} onPress={() => setExpanded(!expanded)}><Panel style={[styles.entry, !unlocked && styles.locked]}><Header portrait={<HeroPortrait raceId="human" classId={classId} gender="male" variant={0} label={`${heroClass.name} example`} size={50} />} title={heroClass.name} subtitle={`${lore.role} · ${unlocked ? "AVAILABLE" : "LOCKED"}`} expanded={expanded} />{expanded && <View style={styles.details}>{!BASE_CLASS_IDS.includes(classId) && <Text style={styles.source}>50-gem charter unlock</Text>}<Text style={styles.body}>{lore.overview}</Text><Label>BATTLEFIELD STYLE</Label><Text style={styles.body}>{lore.playstyle}</Text><Label>ATTRIBUTE GROWTH</Label><View style={styles.growthRow}>{growth.map(([attribute, value]) => <View key={attribute} style={styles.growthCell}><Text style={styles.growthLabel}>{ATTRIBUTE_LABELS[attribute]}</Text><Text style={styles.growthValue}>{value.toFixed(1)}x</Text></View>)}</View><Label>SKILL PATH</Label>{heroClass.skillIds.map((skillId, index) => { const skill = HERO_SKILLS[skillId]; return skill ? <View key={skillId} style={styles.skill}><View style={styles.skillHeading}><Text style={styles.skillName}>{skill.name}</Text><Text style={styles.skillType}>{index === 0 ? "STARTING" : skill.type.replace(/_/g, " ").toUpperCase()}</Text></View>{getSkillDescriptionLines(skill).map((line) => <Text key={line} style={styles.skillLine}>{line}</Text>)}</View> : null; })}</View>}</Panel></Pressable>;
}

export function HeroCodexScreen({ onBack }: { onBack(): void }) {
  const [tab, setTab] = useState<CodexTab>("Races");
  const [query, setQuery] = useState("");
  const { guild } = useGuild();
  const normalized=query.trim().toLowerCase();const raceIds=(Object.keys(RACES) as RaceId[]).filter((id)=>!normalized||RACES[id].name.toLowerCase().includes(normalized)||RACE_CODEX[id].epithet.toLowerCase().includes(normalized));const classIds=(Object.keys(CLASSES) as ClassId[]).filter((id)=>!normalized||CLASSES[id].name.toLowerCase().includes(normalized)||CLASS_CODEX[id].role.toLowerCase().includes(normalized));
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.eyebrow}>GUILD ARCHIVES</Text><Text style={styles.title}>Heroes' Codex</Text><Text style={styles.intro}>A living field guide to {Object.keys(RACES).length} peoples and {Object.keys(CLASSES).length} guild disciplines. Locked entries explain how they permanently join every save's recruitment pool.</Text><TextInput accessibilityLabel="Search Heroes' Codex" placeholder="Search by name or role…" placeholderTextColor={colors.muted} value={query} onChangeText={setQuery} style={{backgroundColor:colors.panel,borderColor:colors.border,borderRadius:9,borderWidth:1,color:colors.text,marginBottom:12,paddingHorizontal:12,paddingVertical:10}}/><SegmentedTabs values={["Races", "Classes"] as const} value={tab} onChange={setTab} /><SectionTitle>{tab === "Races" ? `PEOPLES OF ELDORIA · ${raceIds.length}` : `ADVENTURING CLASSES · ${classIds.length}`}</SectionTitle>{tab === "Races" ? raceIds.map((id) => <RaceEntry key={id} raceId={id} unlocked={guild.entitlements.unlockedRaceIds.includes(id)} />) : classIds.map((id) => <ClassEntry key={id} classId={id} unlocked={guild.entitlements.unlockedClassIds.includes(id)} />)}</ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 40 }, eyebrow: { color: colors.gold, fontSize: 11, fontWeight: "900", letterSpacing: 2, marginTop: 16 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 3 }, intro: { color: colors.muted, lineHeight: 20, marginBottom: 16, marginTop: 8 }, entry: { marginBottom: 10 }, locked: { opacity: .72, borderStyle: "dashed" }, header: { alignItems: "center", flexDirection: "row" }, headerText: { flex: 1, marginLeft: 12 }, entryTitle: { color: colors.text, fontSize: 19, fontWeight: "900" }, meta: { color: colors.muted, fontSize: 12, marginTop: 2 }, chevron: { color: colors.gold, fontSize: 24, fontWeight: "700" }, details: { borderTopColor: colors.border, borderTopWidth: 1, marginTop: 14, paddingTop: 13 }, source: { color: colors.gold, fontSize: 11, fontWeight: "900", marginBottom: 9, textTransform: "capitalize" }, body: { color: colors.text, fontSize: 14, lineHeight: 20 }, label: { color: colors.gold, fontSize: 11, fontWeight: "900", letterSpacing: 1.2, marginBottom: 7, marginTop: 15 }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { backgroundColor: colors.panel2, borderColor: colors.border, borderRadius: 7, borderWidth: 1, color: colors.text, fontSize: 12, overflow: "hidden", paddingHorizontal: 9, paddingVertical: 6 }, growthRow: { flexDirection: "row", gap: 5 }, growthCell: { alignItems: "center", backgroundColor: colors.panel2, borderRadius: 7, flex: 1, paddingVertical: 7 }, growthLabel: { color: colors.muted, fontSize: 9, fontWeight: "900" }, growthValue: { color: colors.text, fontSize: 12, fontWeight: "800", marginTop: 2 }, skill: { backgroundColor: colors.panel2, borderRadius: 9, marginBottom: 8, padding: 11 }, skillHeading: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, skillName: { color: colors.text, flex: 1, fontSize: 14, fontWeight: "800" }, skillType: { color: colors.gold, fontSize: 9, fontWeight: "900" }, skillLine: { color: colors.muted, fontSize: 12, lineHeight: 17, marginTop: 4 } });
