import React, { useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, Panel, SecondaryButton, SegmentedTabs, colors } from "../../components/ui";
import { POTIONS } from "../../data/alchemy/potions";
import { craftPotion, isPotionRecipeUnlocked, usePersistentRemedy } from "../../game/alchemy/potionService";
import type { PotionId } from "../../game/alchemy/potionTypes";
import { useGuild } from "../../state/GuildContext";
import { PotionIcon } from "../../components/alchemy/PotionIcon";
import { MaterialCostList } from "../../components/materials/MaterialIcon";
import { getRaceNameColor } from "../../ui/raceColors";

export function AlchemyScreen({ onBack }: { onBack(): void }) {
  const { guild, updateGuild } = useGuild();
  const [message, setMessage] = useState<string>();
  const [tier,setTier]=useState<1|2|3>(1);
  const craft = (id: PotionId) => { try { updateGuild(craftPotion(guild, id)); setMessage(POTIONS[id].name+" crafted and stored."); } catch (error) { setMessage(error instanceof Error ? error.message : "Crafting failed"); } };
  const remedy = (heroId:string,id:PotionId) => { try { updateGuild(usePersistentRemedy(guild,heroId,id)); setMessage("Remedy administered."); } catch(error){setMessage(error instanceof Error?error.message:"Remedy failed");} };
  const remedies=Object.values(POTIONS).filter((potion)=>potion.curePersistentConditionIds?.length&&(guild.potions[potion.id]??0)>0);
  const affectedHeroes=guild.heroes.filter((hero)=>remedies.some((potion)=>hero.conditions.some((condition)=>potion.curePersistentConditionIds?.includes(condition.conditionId))));
  return <ScrollView contentContainerStyle={styles.content}>
    <BackButton onPress={onBack} /><Text style={styles.eyebrow}>GUILD ALCHEMY</Text><Text style={styles.title}>Potion Workshop</Text><Text style={styles.intro}>Turn gathered regional materials into combat supplies and remedies. Higher tiers unlock as the guild opens new regions.</Text>
    <Panel style={styles.stock}><Text style={styles.stockTitle}>STORED POTIONS</Text>{Object.values(POTIONS).map((potion) => <View key={potion.id} style={styles.stockRow}><PotionIcon potionId={potion.id} size={34}/><Text style={[styles.stockName, styles.flex]}>{potion.name}</Text><Text style={styles.quantity}>{guild.potions[potion.id]}</Text></View>)}</Panel>
    {message && <Text style={styles.message}>{message}</Text>}
    {affectedHeroes.length>0&&<><Text style={styles.section}>FIELD REMEDIES</Text>{affectedHeroes.map((hero)=><Panel key={hero.id} style={styles.remedy}><View style={styles.flex}><Text style={[styles.heroName,{color:getRaceNameColor(hero.raceId)}]}>{hero.name}</Text><Text style={styles.description}>{hero.conditions.map((condition)=>condition.conditionId.replace(/_/g," ")).join(" · ")}</Text></View>{remedies.filter((potion)=>hero.conditions.some((condition)=>potion.curePersistentConditionIds?.includes(condition.conditionId))).map((potion)=><SecondaryButton key={potion.id} label={"Use "+potion.name} onPress={()=>remedy(hero.id,potion.id)}/>)}</Panel>)}</>}
    <Text style={styles.section}>POTION RECIPES</Text><SegmentedTabs values={["Tier 1","Tier 2","Tier 3"] as const} value={`Tier ${tier}` as const} onChange={(value)=>setTier(Number(value.slice(-1)) as 1|2|3)}/>{Object.values(POTIONS).filter((potion)=>potion.tier===tier).map((potion) => { const unlocked=isPotionRecipeUnlocked(guild,potion.id); const requirements = Object.entries(potion.materials); const canCraft = unlocked&&guild.gold >= potion.goldCost && requirements.every(([id, amount]) => guild.materials[id as keyof typeof guild.materials] >= amount); return <Panel key={potion.id} style={[styles.recipe,!unlocked&&styles.locked]}><View style={styles.recipeHead}><PotionIcon potionId={potion.id} size={54}/><View style={styles.flex}><Text style={styles.name}>{potion.name}</Text><Text style={styles.description}>{potion.description}</Text><Text style={styles.unlock}>{unlocked?"RECIPE UNLOCKED":potion.requiredRegionId?`LOCKED · Travel progression must unlock ${potion.requiredRegionId.replace(/_/g," ")}.`:"LOCKED · Continue the campaign to discover this recipe."}</Text></View></View><Text style={styles.cost}>Cost: {potion.goldCost} gold</Text><MaterialCostList costs={potion.materials} inventory={guild.materials}/><ActionButton label={unlocked?"Craft Potion":potion.requiredRegionId?"Region Required":"Campaign Progress Required"} disabled={!canCraft} onPress={() => craft(potion.id)} /></Panel>; })}
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 45 }, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginTop: 8 }, title: { color: colors.text, fontSize: 29, fontWeight: "900", marginTop: 3 }, intro: { color: colors.muted, lineHeight: 19, marginBottom: 14, marginTop: 7 }, stock: { borderColor: colors.gold, marginBottom: 12 }, stockTitle: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, stockRow: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: 9, paddingVertical: 7 }, stockName: { color: colors.text }, quantity: { color: colors.gold, fontSize: 18, fontWeight: "900" }, message: { color: colors.green, fontWeight: "800", marginBottom: 10 }, section:{color:colors.gold,fontSize:10,fontWeight:"900",letterSpacing:1,marginBottom:7,marginTop:13},remedy:{alignItems:"center",flexDirection:"row",flexWrap:"wrap",gap:6,marginBottom:7},heroName:{fontSize:15,fontWeight:"900"},recipe: { gap: 9, marginBottom: 10 },locked:{opacity:.48},recipeHead: { alignItems: "center", flexDirection: "row", gap: 11 }, flex: { flex: 1 }, name: { color: colors.text, fontSize: 18, fontWeight: "900" }, description: { color: colors.muted, lineHeight: 18 }, unlock:{color:colors.green,fontSize:9,fontWeight:"900",marginTop:3,textTransform:"capitalize"},cost: { color: colors.gold, fontWeight: "800" } });
