import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text } from "react-native";
import { ActionButton, Panel, colors } from "../../components/ui";
import type { GuildState } from "../../game/guild/types";
import { choiceRequirementsMet, resolveEventChoice } from "../../game/world/worldEventResolver";
import type { WorldEventDefinition } from "../../game/world/worldTypes";
import type { RandomSource } from "../../utils/random";
export function StoryEventScreen({ event, guild, random, updateGuild, onDone }: { event: WorldEventDefinition; guild: GuildState; random: RandomSource; updateGuild(guild: GuildState): void; onDone(): void }) { const [result, setResult] = useState<string>(); const choose = (choiceId: string) => { const choice = event.choices.find((item) => item.id === choiceId)!; try { const resolution = resolveEventChoice(choice, guild.heroes, guild.world, random); updateGuild({ ...guild, gold: guild.gold + resolution.goldDelta, world: resolution.worldState }); setResult(resolution.check ? `D20 ${resolution.check.diceRoll} + ${resolution.check.modifier} = ${resolution.check.total} vs DC ${resolution.check.difficultyClass}: ${resolution.check.success ? "SUCCESS" : "FAILURE"}` : "The journey continues."); } catch (error) { setResult(error instanceof Error ? error.message : "Choice failed"); } };
  return <ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>TRAVEL EVENT</Text><Text style={styles.title}>{event.title}</Text><Text style={styles.description}>{event.description}</Text><Panel>{!result ? event.choices.map((choice) => { const enabled = choiceRequirementsMet(choice, guild.heroes, guild.world); return <Pressable key={choice.id} disabled={!enabled} onPress={() => choose(choice.id)} style={[styles.choice, !enabled && styles.disabled]}><Text style={styles.choiceText}>{choice.text}</Text>{choice.abilityCheck && <Text style={styles.check}>{choice.abilityCheck.attribute.toUpperCase()} · DC {choice.abilityCheck.difficultyClass}</Text>}{!enabled && <Text style={styles.check}>Requirements not met</Text>}</Pressable>; }) : <><Text style={styles.result}>{result}</Text><ActionButton label="Continue" onPress={onDone} /></>}</Panel></ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 22, paddingTop: 60 }, eyebrow: { color: colors.gold, fontWeight: "900", letterSpacing: 2 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 7 }, description: { color: colors.muted, lineHeight: 22, marginVertical: 15 }, choice: { padding: 13, borderColor: colors.border, borderWidth: 1, borderRadius: 10, marginBottom: 9 }, disabled: { opacity: .4 }, choiceText: { color: colors.text, fontWeight: "800" }, check: { color: colors.gold, fontSize: 11, marginTop: 4 }, result: { color: colors.text, lineHeight: 23, fontWeight: "800", marginBottom: 15 } });
