import React, { useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { useGameDialog } from "../../components/dialogs/GameDialog";
import { ActionButton, BackButton, EmptyState, Panel, Portrait, SecondaryButton, SegmentedTabs, colors } from "../../components/ui";
import { CLASSES } from "../../data/classes/classes";
import { RACES } from "../../data/races/races";
import { RECRUITMENT_CONFIG } from "../../data/recruitment/recruitmentBalance";
import { TRAITS } from "../../data/traits/traits";
import { ATTRIBUTE_KEYS } from "../../game/attributes/types";
import { createHeroCombatInstance, createHeroCombatUnit } from "../../game/combat/heroCombatFactory";
import { calculateHero } from "../../game/heroes/heroCalculator";
import { potentialRating, scoutingCost } from "../../game/recruitment/scoutingService";
import type { ScoutingLevel } from "../../game/recruitment/recruitmentTypes";
import { useGuild } from "../../state/GuildContext";
import { getRaceNameColor } from "../../ui/raceColors";
import { BACKGROUNDS } from "../../data/backgrounds/backgrounds";
import { isClassAttribute } from "../../ui/classAttributes";
import { getModifierTargetLabel } from "../../ui/modifierLabels";
import { formatAbilityModifier } from "../../game/attributes/dndAttributes";

const TABS = ["Overview", "Stats", "Traits", "Contract"] as const; type Tab = typeof TABS[number];
const range = (min: number, max: number) => min === max ? `${min}` : `${min}–${max}`;

export function CandidateDetailScreen({ candidateId, onBack }: { candidateId: string; onBack(): void }) {
  const { showDialog } = useGameDialog();
  const { guild, candidates, scoutCandidate, reserveCandidate, recruitCandidate } = useGuild();
  const [tab, setTab] = useState<Tab>("Overview"); const [message, setMessage] = useState<string>();
  const candidate = candidates.find((item) => item.candidateId === candidateId);
  if (!candidate) return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><EmptyState title="Candidate unavailable" message="This candidate was recruited, rejected, refreshed, or expired." /></ScrollView>;
  const hero = candidate.heroPreview; const calculated = calculateHero(hero); const instance = createHeroCombatInstance(hero); const unit = createHeroCombatUnit(hero, instance);
  const salaryCostMin = candidate.weeklySalaryEstimateMin * candidate.contractLengthWeeks; const salaryCostMax = candidate.weeklySalaryEstimateMax * candidate.contractLengthWeeks;
  const totalMin = candidate.recruitmentFeeEstimateMin + salaryCostMin; const totalMax = candidate.recruitmentFeeEstimateMax + salaryCostMax;
  const reserved = guild.recruitment.reservedCandidateId === candidateId;
  const run = (action: () => string | null, success: string) => { const error = action(); setMessage(error ?? success); };
  const confirm = () => showDialog({ title: `Recruit ${hero.name}?`, message: `Estimated fee: ${range(candidate.recruitmentFeeEstimateMin, candidate.recruitmentFeeEstimateMax)} gold\nSalary demand: ${range(candidate.weeklySalaryEstimateMin, candidate.weeklySalaryEstimateMax)} gold/week\nContract: ${candidate.contractLengthWeeks} weeks\nEstimated total: ${range(totalMin, totalMax)} gold`, eyebrow: "GUILD CONTRACT", actions: [{ label: "Cancel", tone: "secondary" }, { label: "Recruit", tone: "primary", onPress: () => { const error = recruitCandidate(candidateId); if (error) setMessage(error); else onBack(); } }] });
  const nextScout = Math.min(3, candidate.scoutingLevel + 1) as ScoutingLevel;
  return <ScrollView contentContainerStyle={styles.content}>
    <BackButton onPress={onBack} />
    <View style={styles.identity}><Portrait hero={hero} size={92} /><View style={styles.flex}><Text style={[styles.title, { color: getRaceNameColor(hero.raceId) }]}>{hero.name}</Text><Text style={styles.gold}>{RACES[hero.raceId].name} {CLASSES[hero.classId].name}</Text><Text style={styles.meta}>Age {hero.age} • Level {hero.level} • {candidate.archetype.toUpperCase()}</Text><Text style={styles.meta}>Background: {BACKGROUNDS[hero.backgroundId ?? "farmhand"].name}</Text></View></View>
    {message && <Text style={styles.message}>{message}</Text>}<SegmentedTabs values={TABS} value={tab} onChange={setTab} />
    {tab === "Overview" && <><Panel>{candidate.source === "regional_scout" && <Text style={styles.reportSource}>REGIONAL SCOUT REPORT · {candidate.sourceLocationName}</Text>}<Text style={styles.value}>Potential estimate: {range(candidate.potentialEstimateMin, candidate.potentialEstimateMax)}</Text><Text style={styles.meta}>{potentialRating(candidate.potentialEstimateMin)}–{potentialRating(candidate.potentialEstimateMax)}</Text><Text style={styles.line}>Recruitment fee estimate: {range(candidate.recruitmentFeeEstimateMin, candidate.recruitmentFeeEstimateMax)} gold</Text><Text style={styles.line}>Salary demand estimate: {range(candidate.weeklySalaryEstimateMin, candidate.weeklySalaryEstimateMax)} gold/week</Text><Text style={styles.line}>Contract preference: {candidate.contractLengthWeeks} weeks</Text><Text style={styles.line}>Scouting level: {candidate.scoutingLevel}/3</Text><Text style={styles.line}>Expires Day {candidate.expiresAtDay}</Text></Panel><View style={styles.actions}>{candidate.scoutingLevel < 3 && <View style={styles.flex}><SecondaryButton label={`Scout (${scoutingCost(nextScout)})`} onPress={() => run(() => scoutCandidate(candidateId), "Scouting report improved and estimates narrowed.")} /></View>}<View style={styles.flex}><SecondaryButton label={reserved ? "Reserved" : `Reserve (${RECRUITMENT_CONFIG.reservationCost})`} disabled={reserved} onPress={() => run(() => reserveCandidate(candidateId), `${hero.name} reserved.`)} /></View></View>{candidate.scoutingLevel < 3 && <Text style={styles.scoutHint}>Further scouting narrows potential, recruitment fee, and weekly salary estimates. Expert scouting reveals exact figures.</Text>}<ActionButton label={guild.heroes.length >= RECRUITMENT_CONFIG.heroCapacity ? "Guild Capacity Reached" : guild.gold < candidate.recruitmentFeeEstimateMin ? "Insufficient Gold" : "Recruit"} disabled={guild.heroes.length >= RECRUITMENT_CONFIG.heroCapacity || guild.gold < candidate.recruitmentFeeEstimateMin} onPress={confirm} /></>}
    {tab === "Stats" && <><Panel>{ATTRIBUTE_KEYS.map((key) => { const preferred = isClassAttribute(hero.classId, key); const estimate = candidate.attributeEstimates[key]; const scoreText = range(estimate.minimum, estimate.maximum); const modifierText = range(Number(formatAbilityModifier(estimate.minimum)), Number(formatAbilityModifier(estimate.maximum))); return <View key={key} style={styles.row}><Text style={[styles.meta, preferred && styles.classAttribute]}>{key}</Text><Text style={[styles.value, preferred && styles.classAttribute]}>{scoreText} (mod {modifierText})</Text></View>; })}<Text style={styles.classHint}>Green attributes are favored by this class. Scouting narrows every score; recruited heroes show exact values.</Text></Panel>{candidate.scoutingLevel === 3 ? <Panel style={styles.panelGap}>{Object.entries(calculated.stats).map(([key, value]) => <View key={key} style={styles.row}><Text style={styles.meta}>{key}</Text><Text style={styles.value}>{key === "criticalChance" ? `${(value * 100).toFixed(1)}%` : Math.round(value)}</Text></View>)}<View style={styles.row}><Text style={styles.meta}>Armor Class</Text><Text style={styles.value}>{unit.stats.armorClass}</Text></View><View style={styles.row}><Text style={styles.meta}>Movement Range</Text><Text style={styles.value}>{unit.movementRange}</Text></View></Panel> : <Panel style={styles.panelGap}><Text style={styles.meta}>Exact derived combat statistics become available with Expert scouting or after recruitment.</Text></Panel>}</>}
    {tab === "Traits" && hero.traitIds.map((id) => <Panel key={id} style={styles.panelGap}><Text style={styles.value}>{TRAITS[id].name} · {TRAITS[id].category.toUpperCase()}</Text><Text style={styles.traitDescription}>{TRAITS[id].description}</Text>{TRAITS[id].modifiers.map((modifier, index) => <Text key={index} style={styles.line}>{getModifierTargetLabel(modifier.target)}: {modifier.value >= 0 ? "+" : ""}{modifier.operation === "percentage" ? `${modifier.value * 100}%` : modifier.value}{modifier.condition ? " while HP ratio ≤ 0.50" : ""}</Text>)}</Panel>)}
    {tab === "Contract" && <Panel><Text style={styles.line}>Upfront fee estimate: {range(candidate.recruitmentFeeEstimateMin, candidate.recruitmentFeeEstimateMax)}</Text><Text style={styles.line}>Weekly salary demand: {range(candidate.weeklySalaryEstimateMin, candidate.weeklySalaryEstimateMax)}</Text><Text style={styles.line}>Contract length: {candidate.contractLengthWeeks} weeks</Text><Text style={styles.value}>Estimated salary cost: {range(salaryCostMin, salaryCostMax)}</Text><Text style={styles.total}>Estimated total cost: {range(totalMin, totalMax)}</Text><Text style={styles.meta}>Estimates become exact at Expert scouting.</Text></Panel>}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 45 }, identity: { flexDirection: "row", gap: 14, alignItems: "center", marginVertical: 14 }, flex: { flex: 1 }, title: { color: colors.text, fontSize: 27, fontWeight: "900" }, gold: { color: colors.gold, fontWeight: "800", marginTop: 3 }, meta: { color: colors.muted, textTransform: "capitalize", marginTop: 3 }, message: { color: colors.green, marginBottom: 10 }, reportSource: { color: colors.blue, fontSize: 10, fontWeight: "900", letterSpacing: .7, marginBottom: 8 }, value: { color: colors.text, fontWeight: "900", fontSize: 16 }, traitDescription: { color: colors.muted, lineHeight: 19, marginTop: 5 }, classAttribute: { color: colors.green, fontWeight: "900" }, classHint: { color: colors.green, fontSize: 10, fontWeight: "700", marginTop: 9 }, line: { color: colors.text, marginTop: 8 }, row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 6, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: colors.border }, actions: { flexDirection: "row", gap: 8, marginVertical: 12 }, scoutHint: { color: colors.muted, lineHeight: 19, marginBottom: 12 }, panelGap: { marginTop: 10 }, total: { color: colors.gold, fontWeight: "900", fontSize: 18, marginTop: 14 } });
