import React, { useEffect, useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { DungeonArtwork, DungeonNodeArtworkIcon, type DungeonArtworkVariant } from "../../components/dungeons/DungeonArtwork";
import { ActionButton, BackButton, Panel, Portrait, SecondaryButton, SectionTitle, colors } from "../../components/ui";
import { CRAFTING_RECIPES } from "../../data/crafting/recipes";
import { DUNGEONS, DUNGEON_NODES, DUNGEON_RUN_MODIFIERS } from "../../data/dungeons/dungeons";
import { createDungeonDraft, DUNGEON_UNLOCK_HERO_COUNT, selectDungeonDraftHero, type DungeonDraftState } from "../../game/dungeons/dungeonDraftService";
import { availableDungeonNodeIds, chooseDungeonNode, isCurrentDungeonNodeResolved } from "../../game/dungeons/dungeonService";
import { beginDungeonExpedition, closeDungeonExpedition, resolveDungeonUtilityNode } from "../../game/dungeons/dungeonRunService";
import type { DungeonDefinition, DungeonNodeDefinition, DungeonThemeId } from "../../game/dungeons/dungeonTypes";
import type { GuildState } from "../../game/guild/types";
import { calculateHero } from "../../game/heroes/heroCalculator";
import type { RandomSource } from "../../utils/random";
import { GameIcon } from "../../components/icons/GameIcon";
import type { GameIconId } from "../../data/ui/gameIcons";
import { generateRogueliteThemeOffers, isChapterOneComplete } from "../../game/dungeons/rogueliteRotationService";

const ICONS: Record<DungeonNodeDefinition["type"], GameIconId> = { event: "journal", combat: "weapon", elite: "boss", treasure: "loot", rest: "temple", merchant: "gold", boss: "boss" };
const THEME_ICONS: Record<DungeonThemeId, GameIconId> = { forest: "world", arctic: "current", jungle: "world", wasteland: "region_open", desert: "region_open", undead: "monster_manual" };
const NODE_ART: Record<string, DungeonArtworkVariant> = { event: "entrance", combat: "ossuary", elite: "boss", treasure: "treasure", rest: "ossuary", merchant: "merchant", boss: "boss" };

function ThemeHeader({ dungeon }: { dungeon: DungeonDefinition }) { return <Panel style={[styles.themeHeader, { borderColor: dungeon.accentColor }]}><GameIcon id={THEME_ICONS[dungeon.themeId]} size={48} /><View style={styles.flex}><Text style={styles.themeName}>{dungeon.name}</Text><Text style={styles.meta}>{dungeon.description}</Text><Text style={[styles.themeRule, { color: dungeon.accentColor }]}>{dungeon.themeRule}</Text></View></Panel>; }
function DraftHero({ guild, heroId, onPress }: { guild: GuildState; heroId: string; onPress?(): void }) { const hero = guild.heroes.find((entry) => entry.id === heroId); if (!hero) return null; const stats = calculateHero(hero).stats; const card = <Panel style={[styles.hero, onPress && styles.draftOffer]}><Portrait hero={hero} size={48}/><View style={styles.flex}><Text style={styles.heroName}>{hero.name} · Lv {hero.level}</Text><Text style={styles.meta}>{hero.classId} · HP {Math.round(hero.currentHP)}/{Math.round(stats.maxHP)}</Text><Text style={styles.meta}>Traits: {hero.traitIds.join(", ") || "None"}</Text></View>{onPress && <Text style={styles.mark}>DRAFT</Text>}</Panel>; return onPress ? <Pressable onPress={onPress}>{card}</Pressable> : card; }

export function DungeonScreen({ guild, random, updateGuild, onBack, startCombat }: { guild: GuildState; random: RandomSource; updateGuild(guild: GuildState): void; onBack(): void; startCombat(): void }) {
  const [selectedDungeonId, setSelectedDungeonId] = useState<string | null>(null); const [draft, setDraft] = useState<DungeonDraftState | null>(null); const [modifierIds, setModifierIds] = useState<string[]>([]); const run = guild.activeDungeonRun; const activeDungeon = run ? DUNGEONS[run.dungeonId]! : null;
  useEffect(() => { if (!run && isChapterOneComplete(guild) && guild.currentDay >= guild.rogueliteRotation.cooldownUntilDay && !guild.rogueliteRotation.offeredDungeonIds.length) { try { updateGuild(generateRogueliteThemeOffers(guild, random)); } catch { /* the lock panel explains why */ } } }, [run, guild.currentDay, guild.world.completedCampaignNodeIds.length, guild.rogueliteRotation.offeredDungeonIds.length]);
  const showError = (error: unknown) => Alert.alert("Roguelite Expedition", error instanceof Error ? error.message : "The action failed.");
  if (!run) {
    const selectedDungeon = selectedDungeonId ? DUNGEONS[selectedDungeonId] : null; const chapterUnlocked = isChapterOneComplete(guild); const cooldownReady = guild.currentDay >= guild.rogueliteRotation.cooldownUntilDay; const unlocked = chapterUnlocked && cooldownReady && guild.heroes.length >= DUNGEON_UNLOCK_HERO_COUNT;
    if (!selectedDungeon) return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.title}>Roguelite Expeditions</Text><Text style={styles.subtitle}>DRAFT FOUR HEROES · RANDOMIZED ROOMS · ONE LIFE PER RUN</Text><DungeonArtwork variant="entrance" compact/><Text style={styles.description}>Choose a theme, then complete four rounds of drafting. Each round presents three randomly selected heroes from your guild; choose exactly one.</Text>
      {!unlocked && <Panel style={styles.locked}><View style={{ alignItems: "center", flexDirection: "row", gap: 9 }}><GameIcon id="locked" size={34} /><Text style={styles.lockedTitle}>MODE LOCKED</Text></View><Text style={styles.description}>{!chapterUnlocked ? "Complete Chapter 1 and defeat the Goblin Chieftain." : !cooldownReady ? `The dungeon reopens on Day ${guild.rogueliteRotation.cooldownUntilDay}.` : `Recruit ${DUNGEON_UNLOCK_HERO_COUNT} heroes. Owned: ${guild.heroes.length}/${DUNGEON_UNLOCK_HERO_COUNT}`}</Text></Panel>}
      <SectionTitle>CHOOSE 1 OF 3 THEMES</SectionTitle>{guild.rogueliteRotation.offeredDungeonIds.map((id) => DUNGEONS[id]).filter((dungeon): dungeon is DungeonDefinition => Boolean(dungeon)).map((dungeon) => <Pressable key={dungeon.id} disabled={!unlocked} onPress={() => setSelectedDungeonId(dungeon.id)}><View style={!unlocked && styles.disabled}><ThemeHeader dungeon={dungeon}/><Text style={styles.poolSummary}>3 encounter groups · 2 elites · 2 possible bosses · Lv {dungeon.recommendedLevelMin}–{dungeon.recommendedLevelMax}</Text></View></Pressable>)}
    </ScrollView>;
    if (!draft) return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={() => setSelectedDungeonId(null)}/><Text style={styles.title}>Prepare the Draft</Text><ThemeHeader dungeon={selectedDungeon}/>{selectedDungeon.themeId === "undead" && <DungeonArtwork variant="entrance" compact/>}<SectionTitle>OPTIONAL RUN MODIFIERS</SectionTitle>{selectedDungeon.runModifierIds.map((id) => { const modifier = DUNGEON_RUN_MODIFIERS[id]!; const active = modifierIds.includes(id); return <Pressable key={id} onPress={() => setModifierIds((current) => current.includes(id) ? current.filter((entry) => entry !== id) : [...current, id])}><Panel style={[styles.option, active && styles.selected]}><Text style={styles.optionTitle}>{active ? "✓ " : "○ "}{modifier.name}</Text><Text style={styles.meta}>{modifier.description}</Text></Panel></Pressable>; })}<ActionButton label="Begin Hero Draft" onPress={() => { try { setDraft(createDungeonDraft(guild, random)); } catch (error) { showError(error); } }}/></ScrollView>;
    const draftedHeroes = draft.selectedHeroIds.map((id) => guild.heroes.find((hero) => hero.id === id)).filter(Boolean); const averageLevel = draftedHeroes.length ? draftedHeroes.reduce((sum, hero) => sum + hero.level, 0) / draftedHeroes.length : 0;
    return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={() => setDraft(null)}/><Text style={styles.title}>{draft.complete ? "Party Drafted" : `Draft Round ${draft.round} of 4`}</Text><ThemeHeader dungeon={selectedDungeon}/><Text style={styles.draftRule}>{draft.complete ? "Your four-hero expedition party is locked in." : "Choose one of these three guild heroes. The other two return to the pool."}</Text>
      {!!draft.selectedHeroIds.length && <><SectionTitle>DRAFTED PARTY</SectionTitle>{draft.selectedHeroIds.map((id) => <DraftHero key={id} guild={guild} heroId={id}/>)}</>}
      {!draft.complete && <><SectionTitle>PICK 1 OF 3</SectionTitle>{draft.offeredHeroIds.map((id) => <DraftHero key={id} guild={guild} heroId={id} onPress={() => { try { setDraft(selectDungeonDraftHero(draft, id, random)); } catch (error) { showError(error); } }}/>)}</>}
      {draft.complete && <><Text style={[styles.warning, averageLevel >= selectedDungeon.recommendedLevelMin && styles.ready]}>{averageLevel < selectedDungeon.recommendedLevelMin ? `DANGER: Drafted party average ${averageLevel.toFixed(1)} is below level ${selectedDungeon.recommendedLevelMin}.` : `Party average ${averageLevel.toFixed(1)} · Ready`}</Text><ActionButton label="Enter the Roguelite" onPress={() => { try { updateGuild(beginDungeonExpedition(guild, selectedDungeon.id, draft.selectedHeroIds, modifierIds, random)); } catch (error) { showError(error); } }}/></>}
    </ScrollView>;
  }

  const dungeon = activeDungeon!; const node = DUNGEON_NODES[run.currentNodeId]!; const resolved = isCurrentDungeonNodeResolved(run); const nextIds = availableDungeonNodeIds(run);
  if (run.status !== "active") return <ScrollView contentContainerStyle={styles.content}><Text style={styles.title}>{run.status === "victory" ? "Expedition Complete" : "Expedition Lost"}</Text>{dungeon.themeId === "undead" ? <DungeonArtwork variant={run.status === "victory" ? "treasure" : "entrance"} compact/> : <ThemeHeader dungeon={dungeon}/>}<Text style={run.status === "victory" ? styles.victory : styles.warning}>{run.status === "victory" ? `${dungeon.name} has yielded—for this run.` : "The surviving party returns from the expedition."}</Text><Panel style={styles.summary}><Text style={styles.summaryValue}>{run.goldEarned} gold</Text><Text style={styles.summaryValue}>{run.xpEarnedPerHero} XP per hero</Text><Text style={styles.meta}>Path: {[...run.visitedNodeIds, run.currentNodeId].map((id) => DUNGEON_NODES[id]?.title).join(" → ")}</Text><Text style={styles.meta}>Recipes: {run.recipeIdsUnlocked.length ? run.recipeIdsUnlocked.map((id) => CRAFTING_RECIPES[id]?.description ?? id).join(", ") : "None this run"}</Text></Panel><ActionButton label="Return to Guild" onPress={() => updateGuild(closeDungeonExpedition(guild))}/></ScrollView>;
  const resolveUtility = (choice?: "buy_supplies" | "leave") => { try { updateGuild(resolveDungeonUtilityNode(guild, random, choice).guild); } catch (error) { showError(error); } };
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.header}><BackButton onPress={onBack}/><Pressable onPress={() => Alert.alert("Abandon expedition?", "Run progress will be lost, but earned rewards remain.", [{ text: "Stay", style: "cancel" }, { text: "Abandon", style: "destructive", onPress: () => updateGuild(closeDungeonExpedition(guild, true)) }])}><Text style={styles.abandon}>Abandon</Text></Pressable></View><Text style={styles.title}>{dungeon.name}</Text><Text style={styles.subtitle}>Gold {run.goldEarned} · XP {run.xpEarnedPerHero}/hero · Rooms {run.resolvedNodeIds.length}/{dungeon.nodeIds.length}</Text><ThemeHeader dungeon={dungeon}/>
    <SectionTitle>ROUTE MAP</SectionTitle><View style={styles.map}>{dungeon.nodeIds.map((id) => { const entry = DUNGEON_NODES[id]!; const isCurrent = id === run.currentNodeId; const done = run.resolvedNodeIds.includes(id); return <View key={id} style={[styles.mapNode, isCurrent && { borderColor: dungeon.accentColor, borderWidth: 2 }, done && styles.done]}><DungeonNodeArtworkIcon type={entry.type}/><Text numberOfLines={1} style={styles.mapName}>{entry.title}</Text><Text style={styles.mapState}>{isCurrent ? "CURRENT" : done ? "CLEARED" : run.visitedNodeIds.includes(id) ? "VISITED" : entry.type.toUpperCase()}</Text></View>; })}</View>
    <SectionTitle>CURRENT ROOM</SectionTitle>{dungeon.themeId === "undead" && <DungeonArtwork variant={NODE_ART[node.type] ?? "entrance"} compact/>}<Panel style={[styles.room, { borderColor: dungeon.accentColor }]}><View style={{ alignItems: "center", flexDirection: "row", gap: 7 }}><GameIcon id={ICONS[node.type]} size={28} framed={false} /><Text style={[styles.roomType, { color: dungeon.accentColor }]}>{node.type.toUpperCase()}</Text></View><Text style={styles.roomTitle}>{node.title}</Text><Text style={styles.description}>{node.description}</Text>{run.lastResolutionText && <Text style={styles.resolution}>{run.lastResolutionText}</Text>}
      {!resolved && ["combat", "elite", "boss"].includes(node.type) && <ActionButton label={node.type === "boss" ? "Challenge Random Boss" : "Enter Tactical Combat"} onPress={startCombat}/>} {!resolved && node.type === "event" && <ActionButton label={`Attempt ${node.abilityCheck?.attribute.toUpperCase()} Check · DC ${node.abilityCheck?.difficultyClass}`} onPress={() => resolveUtility()}/>} {!resolved && node.type === "treasure" && <ActionButton label="Open Cache" onPress={() => resolveUtility()}/>} {!resolved && node.type === "rest" && <ActionButton label="Make Camp" onPress={() => resolveUtility()}/>} {!resolved && node.type === "merchant" && <View style={styles.actions}><ActionButton label={`Buy Supplies · ${node.merchantCost}g`} onPress={() => resolveUtility("buy_supplies")}/><SecondaryButton label="Leave" onPress={() => resolveUtility("leave")}/></View>}
    </Panel>{resolved && nextIds.length > 0 && <><SectionTitle>CHOOSE THE NEXT ROUTE</SectionTitle>{nextIds.map((id) => { const next = DUNGEON_NODES[id]!; return <Pressable key={id} onPress={() => updateGuild({ ...guild, activeDungeonRun: chooseDungeonNode(run, id) })}><Panel style={styles.routeChoice}><View style={{ alignItems: "center", flexDirection: "row", gap: 7 }}><GameIcon id={ICONS[next.type]} size={26} framed={false} /><Text style={[styles.roomType, { color: dungeon.accentColor }]}>{next.type.toUpperCase()}</Text></View><Text style={styles.optionTitle}>{next.title}</Text><Text style={styles.meta}>{next.description}</Text></Panel></Pressable>; })}</>}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 48 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { color: colors.text, fontSize: 29, fontWeight: "900", marginTop: 8 }, subtitle: { color: colors.gold, fontWeight: "800", fontSize: 12, marginTop: 5 }, description: { color: colors.muted, lineHeight: 20, marginVertical: 8 }, themeHeader: { flexDirection: "row", gap: 12, alignItems: "center", marginVertical: 9 }, themeGlyph: { width: 38, fontSize: 31, textAlign: "center", fontWeight: "900" }, themeName: { color: colors.text, fontSize: 18, fontWeight: "900" }, themeRule: { fontSize: 12, lineHeight: 17, marginTop: 5, fontWeight: "700" }, poolSummary: { color: colors.muted, fontSize: 11, marginTop: -4, marginBottom: 9, marginLeft: 12 }, locked: { borderColor: colors.danger, marginVertical: 10 }, lockedTitle: { color: colors.danger, fontWeight: "900", fontSize: 17 }, option: { marginBottom: 9 }, selected: { borderColor: colors.gold, backgroundColor: colors.panel2 }, optionTitle: { color: colors.text, fontSize: 16, fontWeight: "900" }, meta: { color: colors.muted, lineHeight: 18, marginTop: 4 }, hero: { flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 8 }, draftOffer: { borderColor: colors.gold }, disabled: { opacity: .42 }, flex: { flex: 1 }, heroName: { color: colors.text, fontWeight: "900" }, mark: { color: colors.gold, fontWeight: "900", fontSize: 11 }, draftRule: { color: colors.gold, lineHeight: 20, marginVertical: 10 }, warning: { color: colors.danger, fontWeight: "800", marginVertical: 12 }, ready: { color: colors.green }, victory: { color: colors.green, fontSize: 17, marginVertical: 12 }, abandon: { color: colors.danger, fontWeight: "800" }, map: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, mapNode: { width: "31%", minHeight: 94, backgroundColor: colors.panel, borderColor: colors.border, borderWidth: 1, borderRadius: 9, padding: 7, alignItems: "center", justifyContent: "center" }, done: { backgroundColor: "#203129" }, mapName: { color: colors.text, fontSize: 10, fontWeight: "800", textAlign: "center", marginTop: 3 }, mapState: { color: colors.muted, fontSize: 8, marginTop: 3 }, room: { marginBottom: 12 }, roomType: { color: colors.gold, fontSize: 12, fontWeight: "900", letterSpacing: 1 }, roomTitle: { color: colors.text, fontSize: 21, fontWeight: "900", marginTop: 4 }, resolution: { color: colors.green, lineHeight: 19, marginVertical: 9 }, actions: { gap: 8 }, routeChoice: { marginBottom: 9 }, summary: { gap: 8, marginVertical: 15 }, summaryValue: { color: colors.gold, fontSize: 20, fontWeight: "900" } });
