import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, Panel, SectionTitle, colors } from "../../components/ui";
import { RAIDS } from "../../data/raids/raids";
import { QUESTS } from "../../data/quests/quests";
import { getRaidLockReason, getRaidReadiness, getRaidRecord } from "../../game/raids/raidService";
import { useGuild } from "../../state/GuildContext";

export function RaidScreen({ onBack, inspectRaid }: { onBack(): void; inspectRaid(questId: string): void }) {
  const { guild } = useGuild(); const raids = Object.values(RAIDS); const [selectedId,setSelectedId]=useState(raids.find((raid)=>!getRaidLockReason(raid,guild))?.id??raids[0]!.id); const [showMechanics,setShowMechanics]=useState(false); const raid=RAIDS[selectedId]!; const quest=QUESTS[raid.questId]!; const lock=getRaidLockReason(raid,guild); const record=getRaidRecord(guild,raid.id); const readiness=getRaidReadiness(raid,guild.heroes);
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.eyebrow}>EIGHT-HERO ENDGAME MODE</Text><Text style={styles.title}>Guild Raids</Text><Text style={styles.intro}>Field two coordinated squads on the largest tactical maps. Raid victories impose a seven-day lockout; defeats consume the quest day and resources but may be retried after recovery.</Text>
    <View style={styles.raidTabs}>{raids.map((entry)=><Pressable key={entry.id} onPress={()=>setSelectedId(entry.id)} style={[styles.raidTab,entry.id===selectedId&&styles.selectedTab]}><Text style={styles.raidTabLevel}>LV {entry.recommendedLevel}</Text><Text numberOfLines={2} style={styles.raidTabName}>{entry.name.replace("The ","")}</Text></Pressable>)}</View>
    <Panel style={[styles.heroPanel,lock&&styles.lockedPanel]}><View style={styles.headingRow}><View style={styles.flex}><Text style={styles.raidName}>{raid.name}</Text><Text style={lock?styles.locked:styles.ready}>{lock?`LOCKED · ${lock}`:"RAID READY"}</Text></View><Text style={styles.skull}>☠</Text></View><Text style={styles.description}>{raid.description}</Text><View style={styles.stats}><Text style={styles.stat}>8 HEROES</Text><Text style={styles.stat}>2 SQUADS</Text><Text style={styles.stat}>{raid.phases.length} PHASES</Text><Text style={styles.stat}>{raid.weeklyLockoutDays}-DAY LOCKOUT</Text></View></Panel>
    <SectionTitle>ROSTER READINESS</SectionTitle><Panel style={readiness.status==="ready"?styles.readinessReady:readiness.status==="risky"?styles.readinessRisky:styles.readinessUnready}><View style={styles.headingRow}><Text style={styles.readinessTitle}>{readiness.status.toUpperCase()}</Text><Text style={styles.readinessNumbers}>{readiness.readyHeroes}/8 ready · Lv {readiness.averageLevel.toFixed(1)} · {Math.round(readiness.averageStamina)} stamina</Text></View>{readiness.warnings.length?<>{readiness.warnings.map((warning)=><Text key={warning} style={styles.readinessWarning}>⚠ {warning}</Text>)}</>:<Text style={styles.readinessGood}>Roster meets the baseline. Equipment, skills, squad composition and mechanic execution still decide the fight.</Text>}</Panel>
    <SectionTitle>FIELD BRIEFING</SectionTitle><Panel><Text style={styles.eyebrow}>PATRON</Text><Text style={styles.record}>{quest.storyContext?.patron}</Text><Text style={styles.eyebrow}>WHY THE GUILD IS NEEDED</Text><Text style={styles.record}>{quest.storyContext?.guildReason}</Text><Text style={styles.eyebrow}>PREPARATION</Text>{quest.preparationNotes?.map((note)=><Text key={note} style={styles.note}>• {note}</Text>)}</Panel>
    <SectionTitle>RAID PLAN</SectionTitle><View style={styles.squads}><Panel style={styles.squad}><Text style={styles.squadTitle}>VANGUARD · SLOTS 1–4</Text><Text style={styles.squadText}>Frontline, control and primary healing. Begins nearest the central pressure lane.</Text></Panel><Panel style={styles.squad}><Text style={styles.squadTitle}>SUPPORT · SLOTS 5–8</Text><Text style={styles.squadText}>Ranged pressure, secondary protection and mechanic response.</Text></Panel></View>
    <SectionTitle>BOSS MECHANICS</SectionTitle><Pressable accessibilityRole="button" onPress={()=>setShowMechanics((value)=>!value)} style={[styles.raidTab,styles.selectedTab]}><Text style={styles.raidTabName}>{showMechanics?"Hide Phase Guide":`Show ${raid.phases.length}-Phase Guide`}</Text><Text style={styles.raidTabLevel}>{showMechanics?"COMPACT VIEW":"TELEGRAPHS & RESPONSES"}</Text></Pressable>{showMechanics&&raid.phases.map((phase,index)=><Panel key={phase.id} style={styles.phase}><View style={styles.phaseBadge}><Text style={styles.phaseNumber}>{index+1}</Text></View><View style={styles.flex}><Text style={styles.phaseTitle}>{phase.name} · {Math.round(phase.hpRatioMax*100)}% HP</Text><Text style={styles.telegraph}>TELEGRAPH · {phase.telegraph}</Text><Text style={styles.mechanic}>{phase.mechanic}</Text><Text style={styles.response}>RESPONSE · {phase.requiredResponse}</Text></View></Panel>)}
    <SectionTitle>REWARDS & RECORD</SectionTitle><Panel><Text style={styles.reward}>{quest.goldRewardMin.toLocaleString()}–{quest.goldRewardMax.toLocaleString()} gold · {quest.xpRewardPerHero} XP per survivor</Text><Text style={record.firstVictoryDay?styles.cleared:styles.firstClear}>{record.firstVictoryDay?`FIRST CLEAR · Day ${record.firstVictoryDay} · ${raid.firstVictoryReward.trophyName} earned`:`FIRST CLEAR · +${raid.firstVictoryReward.gold} gold · ${raid.firstVictoryReward.trophyName}`}</Text><Text style={styles.record}>{record.victories} victories / {record.attempts} attempts · Best: {record.bestSurvivors}/8 standing</Text><Text style={styles.note}>Raid XP is intentionally lower than campaign XP. The main prize is themed boss loot, prestige, and testing your full roster.</Text></Panel>
    <View style={styles.action}><ActionButton disabled={Boolean(lock)} label={lock??"Inspect Raid & Assemble 8 Heroes"} onPress={()=>inspectRaid(raid.questId)}/></View>
  </ScrollView>;
}

const styles=StyleSheet.create({content:{padding:18,paddingBottom:50},eyebrow:{color:"#d39462",fontSize:10,fontWeight:"900",letterSpacing:1.8,marginTop:10},title:{color:colors.text,fontSize:32,fontWeight:"900",marginTop:4},intro:{color:colors.muted,lineHeight:20,marginVertical:12},raidTabs:{flexDirection:"row",gap:7,marginBottom:12},raidTab:{backgroundColor:colors.panel,borderColor:colors.border,borderRadius:10,borderWidth:1,flex:1,minHeight:72,padding:8},selectedTab:{borderColor:"#d39462",backgroundColor:"#2d211d"},raidTabLevel:{color:"#d39462",fontSize:9,fontWeight:"900"},raidTabName:{color:colors.text,fontSize:11,fontWeight:"800",marginTop:5},heroPanel:{borderColor:"#d39462",backgroundColor:"#211b1a"},lockedPanel:{borderColor:colors.border,opacity:.76},headingRow:{alignItems:"center",flexDirection:"row",justifyContent:"space-between",gap:8},flex:{flex:1},raidName:{color:colors.text,fontSize:23,fontWeight:"900"},ready:{color:colors.green,fontSize:11,fontWeight:"900",marginTop:4},locked:{color:colors.danger,fontSize:11,fontWeight:"900",marginTop:4},skull:{color:"#d39462",fontSize:31},description:{color:colors.muted,lineHeight:20,marginTop:10},stats:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:12},stat:{backgroundColor:"#382722",borderRadius:6,color:"#efc29b",fontSize:9,fontWeight:"900",paddingHorizontal:8,paddingVertical:5},readinessReady:{borderColor:colors.green},readinessRisky:{borderColor:colors.gold},readinessUnready:{borderColor:colors.danger},readinessTitle:{color:colors.text,fontSize:15,fontWeight:"900"},readinessNumbers:{color:colors.gold,fontSize:11,fontWeight:"800"},readinessWarning:{color:"#efb46f",fontSize:11,lineHeight:17,marginTop:7},readinessGood:{color:colors.green,fontSize:11,lineHeight:17,marginTop:7},squads:{flexDirection:"row",gap:8},squad:{flex:1,padding:11},squadTitle:{color:colors.gold,fontSize:10,fontWeight:"900"},squadText:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:5},phase:{alignItems:"flex-start",borderColor:"#60453a",flexDirection:"row",gap:11,marginBottom:8},phaseBadge:{alignItems:"center",backgroundColor:"#6b3329",borderRadius:18,height:36,justifyContent:"center",width:36},phaseNumber:{color:"#ffe1bc",fontSize:17,fontWeight:"900"},phaseTitle:{color:colors.text,fontSize:16,fontWeight:"900"},telegraph:{color:colors.gold,fontSize:10,fontWeight:"800",marginTop:6},mechanic:{color:colors.muted,fontSize:12,lineHeight:18,marginTop:4},response:{color:colors.green,fontSize:11,fontWeight:"800",lineHeight:17,marginTop:5},reward:{color:colors.gold,fontSize:15,fontWeight:"900"},firstClear:{color:"#e0b9ff",fontSize:12,fontWeight:"900",marginTop:9},cleared:{color:colors.green,fontSize:12,fontWeight:"900",marginTop:9},record:{color:colors.text,marginTop:8},note:{color:colors.muted,fontSize:11,lineHeight:17,marginTop:8},action:{marginTop:16}});
