import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { BackButton, Panel, SectionTitle, colors } from "../../components/ui";
import { QuestDialogueSequence } from "../../components/quests/QuestDialogueSequence";
import { getQuestDialogue } from "../../data/quests/questDialogue";
import { QUESTS } from "../../data/quests/quests";
import { useGuild } from "../../state/GuildContext";
import { getQuestContinuity, getQuestTypePresentation } from "../../game/quests/questPresentationService";
import { NpcPortrait } from "../../components/characters/NpcPortrait";

export function QuestBriefingScreen({ questId, onBack, onContinue }: { questId: string; onBack(): void; onContinue(): void }) {
  const { guild } = useGuild();
  const quest = QUESTS[questId]; const dialogue = getQuestDialogue(questId);
  const context = quest?.storyContext;
  const presentation = quest ? getQuestTypePresentation(quest) : undefined;
  const continuity = getQuestContinuity(guild, questId);
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.eyebrow}>QUEST BRIEFING</Text><Text style={styles.title}>{dialogue.briefingTitle}</Text><Text style={styles.quest}>{quest?.name}</Text>{presentation ? <Panel style={styles.identity}><Text style={styles.identityBadge}>{presentation.badge}</Text><Text style={styles.identityTitle}>{presentation.heading}</Text><Text style={styles.contextText}>{presentation.summary}</Text><Text style={styles.identityNote}>{presentation.completionNote}</Text></Panel> : null}{continuity.previousBeat ? <><SectionTitle>PREVIOUSLY</SectionTitle><Panel style={styles.previous}><Text style={styles.previousQuest}>DAY {continuity.previousBeat.day} · {continuity.previousBeat.questName.toUpperCase()}</Text><Text style={styles.contextText}>{continuity.previousBeat.aftermath}</Text></Panel></> : null}{continuity.returningContacts.length > 0 ? <><SectionTitle>RETURNING FACES</SectionTitle><Panel style={styles.returning}>{continuity.returningContacts.slice(0,3).map((contact)=><View key={contact.portraitId} style={styles.returningRow}><NpcPortrait portraitId={contact.portraitId} size={46}/><View style={styles.returningCopy}><Text style={styles.returningName}>{contact.speaker}</Text><Text style={styles.returningRole}>{contact.role}</Text><Text style={styles.returningSeen}>Last seen: {contact.previousQuestName}</Text></View></View>)}</Panel></> : null}{context ? <><SectionTitle>WHY THIS MATTERS</SectionTitle><Panel style={styles.context}><Text style={styles.contextLabel}>REQUESTED BY</Text><Text style={styles.contextText}>{context.patron}</Text><Text style={styles.contextLabel}>WHY YOUR GUILD ACCEPTS</Text><Text style={styles.contextText}>{context.guildReason}</Text><Text style={styles.contextLabel}>OBJECTIVE</Text><Text style={styles.contextText}>{context.immediateGoal}</Text><Text style={styles.thread}>STORY THREAD · {context.campaignConnection}</Text></Panel></> : null}<QuestDialogueSequence lines={dialogue.briefing} label={presentation?.briefingLabel ?? "BEFORE DEPARTURE"} finalLabel="Choose the Party" onComplete={onContinue} /><Pressable accessibilityRole="button" onPress={onContinue}><Text style={styles.skip}>Skip briefing and assemble party</Text></Pressable></ScrollView>;
}
const styles = StyleSheet.create({ content: { alignSelf: "center", maxWidth: 620, padding: 20, paddingBottom: 45, width: "100%" }, eyebrow: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 2, marginTop: 13 }, title: { color: colors.text, fontSize: 29, fontWeight: "900", marginTop: 4 }, quest: { color: colors.muted, fontSize: 12, fontWeight: "800", marginBottom: 8, marginTop: 4, textTransform: "uppercase" }, context: { borderColor: "#806a3d", marginBottom: 16 }, contextLabel: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.2, marginTop: 7 }, contextText: { color: colors.text, lineHeight: 20, marginTop: 3 }, thread: { borderTopColor: colors.border, borderTopWidth: 1, color: colors.muted, fontStyle: "italic", lineHeight: 19, marginTop: 10, paddingTop: 9 }, identity:{borderColor:"#6a5f3e",gap:4,marginBottom:12},identityBadge:{color:colors.gold,fontSize:9,fontWeight:"900",letterSpacing:1.3},identityTitle:{color:colors.text,fontSize:17,fontWeight:"900"},identityNote:{color:colors.muted,fontSize:10,fontStyle:"italic",lineHeight:15,marginTop:4},previous:{borderColor:"#506176",gap:4,marginBottom:12},previousQuest:{color:"#9eb6d2",fontSize:9,fontWeight:"900",letterSpacing:.8},returning:{gap:8,marginBottom:12},returningRow:{alignItems:"center",flexDirection:"row",gap:9},returningCopy:{flex:1},returningName:{color:colors.text,fontSize:13,fontWeight:"900"},returningRole:{color:colors.gold,fontSize:9,fontWeight:"800",marginTop:2,textTransform:"uppercase"},returningSeen:{color:colors.muted,fontSize:10,marginTop:2},skip: { color: colors.muted, fontSize: 11, marginTop: 14, textAlign: "center", textDecorationLine: "underline" } });
