import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { BackButton, Panel, SectionTitle, colors } from "../../components/ui";
import { HeroPortrait } from "../../components/heroes/HeroPortrait";
import { CLASSES } from "../../data/classes/classes";
import { RACES } from "../../data/races/races";
import { canClaimDailyLogin, claimDailyLogin, CONTENT_UNLOCK_COST, DAILY_LOGIN_GEMS, unlockPremiumContent, type PremiumContentId } from "../../game/monetization/contentUnlockService";
import { useGuild } from "../../state/GuildContext";
import { STORY_RACE_UNLOCKS } from "../../game/monetization/contentUnlockService";
import { QUESTS } from "../../data/quests/quests";
import { formatGameId } from "../../ui/textFormat";

const OFFERS: { id: PremiumContentId; title: string; kind: string; description: string; highlights: string }[] = [
  { id: "monk", title: CLASSES.monk.name, kind: "CLASS", description: "A disciplined mobile combatant who controls space through precise strikes, defense, and ki techniques.", highlights: "Dexterity / Wisdom · Ki techniques · Open Hand or Shadow path" },
  { id: "bard", title: CLASSES.bard.name, kind: "CLASS", description: "A charismatic battlefield supporter whose songs, cutting words, healing, and magic reshape a fight.", highlights: "Charisma / Dexterity · Inspiration · Lore or Valor college" },
  { id: "spellbow", title: CLASSES.spellbow.name, kind: "CLASS", description: "An arcane archer who pressures Magic Defense from long range and binds elemental effects into every shot.", highlights: "Intelligence / Dexterity · Magical ranged damage · Elemental Archer or Hexstalker" },
  { id: "bulwark", title: CLASSES.bulwark.name, kind: "CLASS", description: "A dedicated shield tank who anchors formations, disrupts advances, and absorbs pressure meant for allies.", highlights: "Constitution / Strength · Heavy protection · Bastion or Vanguard" },
  { id: "summoner", title: CLASSES.summoner.name, kind: "CLASS", description: "A battlefield conjurer who calls temporary allies, controls lanes, and divides enemy attention.", highlights: "Intelligence / Wisdom · Summons · Conjurer or Spirit Shepherd" },
  { id: "tiefling", title: RACES.tiefling.name, kind: "RACE", description: "Ember-Blooded adventurers whose infernal ancestry carries innate presence and arcane talent without determining their allegiance.", highlights: "Charisma +2 · Intelligence +1 · Ashlands homeland" },
];

export function ContentUnlockScreen({ onBack }: { onBack(): void }) {
  const { guild, updateGuild } = useGuild();
  const [message, setMessage] = useState<string | null>(null);
  const [selectedOfferId,setSelectedOfferId]=useState<PremiumContentId>(OFFERS[0]!.id);
  const owned = (id: PremiumContentId) => id === "tiefling" ? guild.entitlements.unlockedRaceIds.includes(id) : guild.entitlements.unlockedClassIds.includes(id);
  const buy = (id: PremiumContentId) => { try { updateGuild(unlockPremiumContent(guild, id)); setMessage(`NEW ${OFFERS.find((offer) => offer.id === id)!.kind} UNLOCKED · ${OFFERS.find((offer) => offer.id === id)!.title}\nAvailable permanently in Recruitment and Regional Scouting.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Unlock failed"); } };
  const claim = () => { try { updateGuild(claimDailyLogin(guild)); setMessage(`Daily reward claimed: +${DAILY_LOGIN_GEMS} gems.`); } catch (error) { setMessage(error instanceof Error ? error.message : "Reward unavailable"); } };
  const claimable = canClaimDailyLogin(guild);
  const selectedOffer=OFFERS.find((offer)=>offer.id===selectedOfferId)!;
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.eyebrow}>GUILD CHARTER EXPANSIONS</Text><Text style={styles.title}>Races & Classes</Text><Text style={styles.intro}>Optional permanent unlocks expand future recruitment pools. Existing heroes and candidates are never removed.</Text><View style={styles.wallet}><Text style={styles.gems}>◇ {guild.gems} gems</Text><Text style={styles.claims}>{guild.dailyLogin.totalClaims} daily rewards claimed</Text></View>
    {message && <Panel style={styles.message}><Text style={styles.messageText}>{message}</Text><Pressable onPress={() => setMessage(null)}><Text style={styles.dismiss}>Dismiss</Text></Pressable></Panel>}
    <Panel style={styles.daily}><View style={styles.row}><View style={styles.flex}><Text style={styles.cardTitle}>Daily Guild Stipend</Text><Text style={styles.copy}>Claim once per real-world calendar day. Five claims provide enough gems for one class or race unlock.</Text></View><Text style={styles.reward}>+◇{DAILY_LOGIN_GEMS}</Text></View><Action label={claimable ? `CLAIM +${DAILY_LOGIN_GEMS} GEMS` : "CLAIMED TODAY"} disabled={!claimable} onPress={claim}/></Panel>
    <SectionTitle>PERMANENT CONTENT</SectionTitle><View style={styles.offerGrid}>{OFFERS.map((offer) => { const isOwned = owned(offer.id); const selected=selectedOfferId===offer.id; return <Pressable accessibilityRole="button" accessibilityState={{selected}} key={offer.id} onPress={()=>setSelectedOfferId(offer.id)} style={styles.offerPressable}><Panel style={[styles.offerTile,selected&&styles.offerSelected]}><View style={styles.offerTileTop}><HeroPortrait raceId={offer.id === "tiefling" ? "tiefling" : "human"} classId={offer.id === "tiefling" ? "warrior" : offer.id} gender="female" label={offer.title} size={46}/><Text style={isOwned ? styles.ownedMini : styles.priceMini}>{isOwned ? "OWNED" : `◇${CONTENT_UNLOCK_COST}`}</Text></View><Text style={styles.kind}>{offer.kind}</Text><Text numberOfLines={1} style={styles.offerTileTitle}>{offer.title}</Text><Text style={styles.offerInspect}>{selected?"SELECTED":"INSPECT"}</Text></Panel></Pressable>; })}</View><Panel style={styles.offerDetail}><View style={styles.row}><HeroPortrait raceId={selectedOffer.id === "tiefling" ? "tiefling" : "human"} classId={selectedOffer.id === "tiefling" ? "warrior" : selectedOffer.id} gender="female" label={selectedOffer.title} size={54}/><View style={styles.flex}><Text style={styles.kind}>{selectedOffer.kind} CHARTER</Text><Text style={styles.cardTitle}>{selectedOffer.title}</Text><Text style={owned(selectedOffer.id)?styles.owned:styles.price}>{owned(selectedOffer.id)?"PERMANENTLY OWNED":`◇ ${CONTENT_UNLOCK_COST}`}</Text></View></View><Text style={styles.copy}>{selectedOffer.description}</Text><Text style={styles.highlights}>{selectedOffer.highlights}</Text><Action label={owned(selectedOffer.id) ? "UNLOCKED" : `UNLOCK · ◇${CONTENT_UNLOCK_COST}`} disabled={owned(selectedOffer.id) || guild.gems < CONTENT_UNLOCK_COST} onPress={() => buy(selectedOffer.id)}/></Panel>
    <SectionTitle>STORY PEOPLES</SectionTitle><View style={styles.storyGrid}>{(["stoneborn", "veilborn"] as const).map((raceId) => { const isOwned = guild.entitlements.unlockedRaceIds.includes(raceId); const questId = STORY_RACE_UNLOCKS[raceId]; return <Panel key={raceId} style={styles.storyTile}><View style={styles.storyHead}><HeroPortrait raceId={raceId} classId="cleric" gender="female" label={RACES[raceId].name} size={48}/><Text style={isOwned ? styles.ownedMini : styles.locked}>{isOwned ? "UNLOCKED" : "LOCKED"}</Text></View><Text style={styles.kind}>STORY RACE</Text><Text style={styles.offerTileTitle}>{RACES[raceId].name}</Text><Text numberOfLines={2} style={styles.storyRequirement}>{isOwned ? "Recruitment & scouting enabled" : `Complete: ${QUESTS[questId]?.name ?? formatGameId(questId)}`}</Text></Panel>; })}</View><Text style={styles.note}>All class and race unlocks are permanent across every save on this device. Story peoples are earned through campaign choices and never require gems.</Text>
  </ScrollView>;
}
function Action({ label, disabled, onPress }: { label: string; disabled: boolean; onPress(): void }) { return <Pressable disabled={disabled} onPress={onPress} style={({ pressed }) => [styles.action, (pressed || disabled) && styles.dim]}><Text style={styles.actionText}>{label}</Text></Pressable>; }
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 48 }, eyebrow: { color: colors.gold, fontSize: 11, fontWeight: "900", letterSpacing: 1.5, marginTop: 10 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 4 }, intro: { color: colors.muted, lineHeight: 20, marginVertical: 10 }, wallet: { flexDirection: "row", justifyContent: "space-between", marginBottom: 13 }, gems: { color: colors.blue, fontWeight: "900", fontSize: 17 }, claims: { color: colors.muted, fontSize: 11 }, message: { backgroundColor:"#17251e", borderColor: colors.green, borderWidth:2, flexDirection: "row", gap: 10, marginBottom: 12 }, messageText: { color: colors.text, flex: 1 }, dismiss: { color: colors.gold, fontWeight: "800" }, daily: { borderColor: colors.blue, gap: 11, marginBottom: 18 }, offer: { gap: 10, marginBottom: 11 }, offerGrid:{flexDirection:"row",flexWrap:"wrap",gap:8,marginBottom:10},offerPressable:{flexBasis:"30%",flexGrow:1,minWidth:96},offerTile:{minHeight:126,padding:9},offerSelected:{borderColor:colors.gold,backgroundColor:colors.panel2},offerTileTop:{alignItems:"flex-start",flexDirection:"row",justifyContent:"space-between"},offerTileTitle:{color:colors.text,fontSize:13,fontWeight:"900",marginTop:2},offerInspect:{color:colors.gold,fontSize:8,fontWeight:"900",letterSpacing:.6,marginTop:"auto",paddingTop:7},priceMini:{color:colors.blue,fontSize:9,fontWeight:"900"},ownedMini:{color:colors.green,fontSize:8,fontWeight:"900"},offerDetail:{borderColor:colors.gold,gap:9,marginBottom:14},storyGrid:{flexDirection:"row",gap:8},storyTile:{flex:1,minHeight:145,padding:10},storyHead:{alignItems:"flex-start",flexDirection:"row",justifyContent:"space-between"},storyRequirement:{color:colors.muted,fontSize:9,lineHeight:13,marginTop:6}, row: { flexDirection: "row", alignItems: "flex-start", gap: 12 }, flex: { flex: 1 }, cardTitle: { color: colors.text, fontSize: 19, fontWeight: "900" }, kind: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.2, marginBottom: 3 }, reward: { color: colors.blue, fontSize: 20, fontWeight: "900" }, copy: { color: colors.muted, lineHeight: 19 }, highlights: { color: colors.gold, fontSize: 11, fontWeight: "800" }, price: { color: colors.blue, fontWeight: "900", fontSize: 16 }, owned: { color: colors.green, fontWeight: "900", fontSize: 12 }, locked: { color: colors.muted, fontWeight: "900", fontSize: 12 }, action: { backgroundColor: colors.gold, borderRadius: 9, padding: 11, alignItems: "center" }, actionText: { color: "#17130c", fontWeight: "900" }, dim: { opacity: .42 }, section: { color: colors.gold, fontWeight: "900", letterSpacing: 1.3, marginBottom: 9, marginTop: 8 }, note: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 7 } });
