import type { CombatUnit } from "../combat/combatTypes";
import type { HeroRelationship, RelationshipBand } from "./relationshipTypes";
export function clampRelationshipScore(score: number): number { return Math.max(-100, Math.min(100, Math.round(score))); }
export function relationshipBand(score: number): RelationshipBand { const value = clampRelationshipScore(score); return value <= -51 ? "rival" : value <= -21 ? "dislike" : value <= 20 ? "neutral" : value <= 50 ? "friend" : "close_friend"; }
export function relationshipScore(relationships: readonly HeroRelationship[], a: string, b: string): number { return relationships.find((item) => (item.heroIdA === a && item.heroIdB === b) || (item.heroIdA === b && item.heroIdB === a))?.score ?? 0; }
export function setRelationship(relationships: readonly HeroRelationship[], heroIdA: string, heroIdB: string, score: number): HeroRelationship[] { if (heroIdA === heroIdB) throw new Error("A hero cannot have a relationship with themselves"); const rest = relationships.filter((item) => !((item.heroIdA === heroIdA && item.heroIdB === heroIdB) || (item.heroIdA === heroIdB && item.heroIdB === heroIdA))); return [...rest, { heroIdA, heroIdB, score: clampRelationshipScore(score) }]; }
const adjacent = (a: CombatUnit, b: CombatUnit) => Math.abs(a.position.x - b.position.x) + Math.abs(a.position.y - b.position.y) === 1;
export function relationshipCombatBonuses(heroId: string, party: readonly CombatUnit[], relationships: readonly HeroRelationship[]) { const allies = party.filter((unit) => unit.combatantId !== heroId && unit.isAlive); const self = party.find((unit) => unit.combatantId === heroId); const friendAdjacent = !!self && allies.some((ally) => relationshipScore(relationships, heroId, ally.combatantId) >= 21 && adjacent(self, ally)); const rivalPresent = allies.some((ally) => relationshipScore(relationships, heroId, ally.combatantId) <= -51); return { attackRollModifier: friendAdjacent ? 1 : 0, physicalDamageModifier: rivalPresent ? .05 : 0 }; }
export function healingReceivedFromHeroModifier(healerId: string, targetId: string, relationships: readonly HeroRelationship[]): number { return relationshipScore(relationships, healerId, targetId) <= -51 ? -.10 : 0; }
