import { describe, expect, it } from "vitest";
import { DUNGEONS, DUNGEON_NODES, DUNGEON_RUN_MODIFIERS } from "../src/data/dungeons/dungeons";
import { xpRequiredForNextLevel } from "../src/game/progression/xpSystem";
import { availableDungeonNodeIds, chooseDungeonNode, markDungeonNodeResolved, startDungeonRun } from "../src/game/dungeons/dungeonService";
describe("branching dungeon runs", () => {
  it("requires node resolution before offering three routes and allows branches to merge", () => { let run = startDungeonRun("wardstone_depths", ["brutal_host"]); expect(availableDungeonNodeIds(run)).toEqual([]); run = markDungeonNodeResolved(run, "Seal opened"); expect(availableDungeonNodeIds(run)).toEqual(["depths_combat", "depths_elite", "depths_trial"]); expect(() => chooseDungeonNode(run, "depths_boss")).toThrow("not connected"); run = chooseDungeonNode(run, "depths_elite"); expect(run.currentNodeId).toBe("depths_elite"); expect(run.status).toBe("active"); expect(DUNGEON_NODES.depths_combat?.nextNodeIds).toEqual(["depths_treasure"]); expect(DUNGEON_NODES.depths_elite?.nextNodeIds).toEqual(["depths_treasure"]); });
  it("defines all seven node types and explicit rest values", () => { expect(new Set(Object.values(DUNGEON_NODES).map((node) => node.type))).toEqual(new Set(["combat", "elite", "event", "treasure", "rest", "merchant", "boss"])); expect(DUNGEON_NODES.depths_rest).toMatchObject({ healMaxHpModifier: .25, manaRecoveryModifier: .40, staminaRecoveryModifier: .40 }); });
  it("makes a full combat route worth about twenty percent of a level at the theme ceiling", () => { const dungeon = DUNGEONS.ashen_march!; const total = DUNGEON_NODES.waste_combat!.xpRewardPerHero! + DUNGEON_NODES.waste_guard!.xpRewardPerHero! + DUNGEON_NODES.waste_boss!.xpRewardPerHero!; expect(total / xpRequiredForNextLevel(dungeon.recommendedLevelMax)).toBeCloseTo(.20, 2); });
  it("uses decimal risk and reward run modifiers", () => { expect(DUNGEON_RUN_MODIFIERS.brutal_host).toMatchObject({ rewardGoldModifier: .30, scoreBonus: 100 }); expect(DUNGEON_RUN_MODIFIERS.withered_grace).toMatchObject({ healingPowerModifier: -.25, rareLootModifier: .20, scoreBonus: 100 }); expect(DUNGEON_RUN_MODIFIERS.predators_clock).toMatchObject({ enemyInitiativeModifier: 2 }); });
});
