import { describe, expect, it } from "vitest";
import { CLASSES } from "../src/data/classes/classes";
import { HERO_SKILLS } from "../src/data/skills/heroSkills";
import { calculateSkillDamage } from "../src/game/combat/damageCalculator";
import { resolveSkill } from "../src/game/combat/skillResolver";
import { getHeroConditionalPassiveModifiers } from "../src/game/combat/heroCombatFactory";
import { combatUnit, sequenceRandom } from "./combatTestUtils";
import { testHero } from "./testHero";
describe("hero skills use the shared resolver", () => {
  it("gives all six classes one basic, two active, and one passive skill", () => { expect(Object.keys(CLASSES)).toHaveLength(6); for (const definition of Object.values(CLASSES)) { const skills = definition.skillIds.map((id) => HERO_SKILLS[id]!); expect(skills.filter((skill) => skill.type === "basic_attack")).toHaveLength(1); expect(skills.filter((skill) => skill.type === "active")).toHaveLength(2); expect(skills.filter((skill) => skill.type === "passive")).toHaveLength(1); } });
  it("Power Strike produces 150 raw physical damage before defense", () => { const attacker = { ...combatUnit("w").stats, physicalDamage: 100 }; const defender = { ...combatUnit("e").stats, physicalDefense: 0 }; expect(calculateSkillDamage(attacker, defender, HERO_SKILLS.warrior_power_strike!)).toBe(150); });
  it("Fireball independently hits, misses, crits, and rolls Burning for every target", () => { const actor = combatUnit("mage", "heroes"); const targets = [combatUnit("e1", "enemies"), combatUnit("e2", "enemies"), combatUnit("e3", "enemies")]; const result = resolveSkill(actor, targets, HERO_SKILLS.mage_fireball!, sequenceRandom([.5, .1, 0, .999, .9])); expect(result.resolution.hits).toHaveLength(3); expect(result.resolution.hits[0]).toMatchObject({ hit: true, critical: false, appliedConditionIds: ["burning"] }); expect(result.resolution.hits[1]?.hit).toBe(false); expect(result.resolution.hits[2]?.critical).toBe(true); });
  it("Cleric Heal restores 58 HP with 15% healing power", () => { const cleric = combatUnit("cleric", "heroes", { activeModifiers: [{ sourceSkillId: "faith", stat: "healingPower", operation: "percentage", value: .15, durationTurns: -1 }] }); const target = combatUnit("ally", "heroes", { maxHP: 200, currentHP: 100 }); expect(resolveSkill(cleric, [target], HERO_SKILLS.cleric_heal!, sequenceRandom([])).targets[0]?.currentHP).toBe(158); });
  it("Smite deals 25% more final damage to Undead", () => { const paladin = combatUnit("p", "heroes"); const normal = combatUnit("normal", "enemies"); const undead = combatUnit("undead", "enemies", { factionId: "undead" }); const normalDamage = resolveSkill(paladin, [normal], HERO_SKILLS.paladin_smite!, sequenceRandom([0, 1])).resolution.hits[0]!.damage; const undeadDamage = resolveSkill(paladin, [undead], HERO_SKILLS.paladin_smite!, sequenceRandom([0, 1])).resolution.hits[0]!.damage; expect(undeadDamage).toBe(Math.round(normalDamage * 1.25)); });
  it("Berserker Rage activates at 50% but not 51%", () => { const hero = { ...testHero(), classId: "berserker" as const }; expect(getHeroConditionalPassiveModifiers(hero, combatUnit(hero.id, "heroes", { currentHP: 50 }))).toContainEqual(expect.objectContaining({ value: .25 })); expect(getHeroConditionalPassiveModifiers(hero, combatUnit(hero.id, "heroes", { currentHP: 51 }))).toEqual([]); });
});
