import { describe, expect, it } from "vitest";
import { BATTLEFIELDS } from "../src/data/combat/battlefields";
import { RAIDS } from "../src/data/raids/raids";
import { createCombatBoard } from "../src/game/combat/grid/boardFactory";
import { generateHero } from "../src/game/heroes/heroGenerator";
import { buildRecommendedRaidParty, findRaidByQuestId, getActiveRaidPhase, getRaidCompositionWarnings, getRaidLockReason, getRaidReadiness, isRaidUnlocked, recordRaidOutcome, validateRaidParty } from "../src/game/raids/raidService";
import { QUESTS } from "../src/data/quests/quests";
import { QUEST_ENCOUNTERS } from "../src/data/encounters/questEncounters";
import { createGuild } from "../src/game/guild/guildService";
import { createSeededRandom } from "../src/utils/random";

describe("eight-hero raids", () => {
  it("adds two genuinely larger combat board sizes", () => { expect(createCombatBoard([],"raid_field")).toMatchObject({width:17,height:13}); expect(createCombatBoard([],"raid_arena")).toMatchObject({width:19,height:15}); });
  it("ships three raids with maps, eight spawns and at least three mechanics", () => { for(const raid of Object.values(RAIDS)){expect(BATTLEFIELDS[raid.battlefieldId]).toBeDefined();expect(raid.heroSpawnPositions).toHaveLength(8);expect(raid.phases.length).toBeGreaterThanOrEqual(3);} });
  it("forms two four-hero squads without changing ordinary party limits", () => { const random=createSeededRandom(70); const heroes=Array.from({length:8},()=>generateHero(random)); const result=validateRaidParty(RAIDS.broodheart_awakening!,heroes.map(hero=>hero.id),heroes); expect(result.valid).toBe(true);expect(result.squads.map(squad=>squad.heroIds.length)).toEqual([4,4]); });
  it("selects later boss phases at their HP thresholds", () => { const raid=RAIDS.white_maw_unbound!; expect(getActiveRaidPhase(raid,59,100).id).toBe("buried_alive");expect(getActiveRaidPhase(raid,24,100).id).toBe("endless_white"); });
  it("requires both campaign progress and eight owned heroes",()=>{const raid=RAIDS.broodheart_awakening!;expect(isRaidUnlocked(raid,5,8)).toBe(false);expect(isRaidUnlocked(raid,6,7)).toBe(false);expect(isRaidUnlocked(raid,6,8)).toBe(true);});
  it("connects every raid to an eight-hero quest and authored encounters",()=>{for(const raid of Object.values(RAIDS)){const quest=QUESTS[raid.questId];expect(quest).toMatchObject({minPartySize:8,maxPartySize:8,hiddenFromQuestBoard:true});expect(findRaidByQuestId(raid.questId)?.id).toBe(raid.id);for(const encounterId of quest!.encounterIds){const encounter=QUEST_ENCOUNTERS[encounterId];expect(encounter,encounterId).toBeDefined();expect(encounter!.heroSpawnPositions).toHaveLength(8);expect(BATTLEFIELDS[encounter!.battlefieldId]).toBeDefined();}}});
  it("applies a seven-day victory lockout and a one-day defeat recovery",()=>{const raid=RAIDS.broodheart_awakening!;const heroes=Array.from({length:8},()=>generateHero(createSeededRandom(Math.random())));const guild={...createGuild(),heroes,world:{...createGuild().world,campaignChapter:6},currentDay:40};expect(getRaidLockReason(raid,guild)).toBeNull();const victory=recordRaidOutcome(guild,raid.id,true,6);expect(getRaidLockReason(raid,victory)).toBe("Victory lockout · ready Day 47");expect(getRaidLockReason(raid,{...victory,currentDay:47})).toBeNull();const defeat=recordRaidOutcome(guild,raid.id,false,2);expect(getRaidLockReason(raid,defeat)).toBe("Raid recovery · ready Day 41");expect(getRaidLockReason(raid,{...defeat,currentDay:41})).toBeNull();expect(defeat.raidProgress?.records[raid.id]).toMatchObject({attempts:1,victories:0,bestSurvivors:2});});
  it("awards first-clear gold once and records a persistent raid achievement",()=>{const guild={...createGuild(),currentDay:50};const raid=RAIDS.broodheart_awakening!;const first=recordRaidOutcome(guild,raid.id,true,5);expect(first.gold-guild.gold).toBe(raid.firstVictoryReward.gold);expect(first.raidProgress?.records[raid.id]).toMatchObject({firstVictoryDay:50,bonusGoldClaimed:raid.firstVictoryReward.gold});const second=recordRaidOutcome({...first,currentDay:57},raid.id,true,8);expect(second.gold).toBe(first.gold);});
  it("warns when either four-hero squad lacks core raid coverage",()=>{const random=createSeededRandom(99);const heroes=Array.from({length:8},()=>({...generateHero(random),classId:"mage" as const}));expect(getRaidCompositionWarnings(heroes.map((hero)=>hero.id),heroes)).toContain("Vanguard has no frontline hero");});
  it("recognizes newer classes and reports roster readiness before assembly",()=>{const random=createSeededRandom(109);const classes=["bulwark","spellbow","summoner","bard","bulwark","spellbow","summoner","bard"] as const;const heroes=classes.map((classId,index)=>({...generateHero(random),id:`raid-${index}`,classId,level:10,adventureStamina:80}));expect(getRaidCompositionWarnings(heroes.map((hero)=>hero.id),heroes)).toEqual([]);expect(getRaidReadiness(RAIDS.broodheart_awakening!,heroes)).toMatchObject({readyHeroes:8,averageLevel:10,averageStamina:80,status:"ready"});});
  it("marks tired or under-levelled raid rosters as risky or unready",()=>{const random=createSeededRandom(110);const heroes=Array.from({length:8},(_,index)=>({...generateHero(random),id:`tired-${index}`,level:8,adventureStamina:35}));const readiness=getRaidReadiness(RAIDS.broodheart_awakening!,heroes);expect(readiness.status).toBe("unready");expect(readiness.warnings.join(" ")).toContain("stamina");});
  it("auto-fills two legal balanced squads from rested heroes",()=>{const random=createSeededRandom(111);const classes=["bulwark","cleric","ranger","mage","warrior","bard","spellbow","summoner","berserker"] as const;const heroes=classes.map((classId,index)=>({...generateHero(random),id:`auto-${index}`,classId,level:10,adventureStamina:index===8?10:90}));const ids=buildRecommendedRaidParty(heroes,50);expect(ids).toHaveLength(8);expect(ids).not.toContain("auto-8");expect(getRaidCompositionWarnings(ids,heroes)).toEqual([]);});
});
