import { describe, expect, it } from "vitest";
import { createCombatState } from "../src/game/combat/combatEngine";
import { generateHero } from "../src/game/heroes/heroGenerator";
import { initializeRaidMechanics, resolveRaidRoundStart, strikeRaidObjective } from "../src/game/raids/raidCombatMechanicService";
import { createSeededRandom } from "../src/utils/random";

const raidHeroes=()=>{const random=createSeededRandom(802);return Array.from({length:8},()=>generateHero(random));};
const bossHp=(state:ReturnType<typeof createCombatState>,ratio:number)=>({...state,enemies:state.enemies.map((enemy)=>enemy.instance.enemyDefinitionId===state.enemies.find((entry)=>entry.instance.enemyDefinitionId.includes("spider_queen")||entry.instance.enemyDefinitionId.includes("yeti")||entry.instance.enemyDefinitionId.includes("serekh"))?.instance.enemyDefinitionId?{...enemy,unit:{...enemy.unit,currentHP:enemy.unit.maxHP*ratio},instance:{...enemy.instance,currentHP:enemy.instance.maxHP*ratio}}:enemy)});

describe("runtime raid mechanics",()=>{
  it("telegraphs danger tiles for a full round before dealing percentage damage",()=>{const random=createSeededRandom(44);let state=initializeRaidMechanics(createCombatState("raid_broodheart_awakening",1,raidHeroes(),random));expect(state.raidMechanic?.activePhaseId).toBe("silken_procession");expect(state.raidMechanic?.resolvesAtRound).toBe(2);const first=state.heroes[0]!;state={...state,heroes:state.heroes.map((hero,index)=>index?hero:{...hero,unit:{...hero.unit,position:{x:5,y:2}},instance:{...hero.instance,position:{x:5,y:2}}})};const before=first.unit.currentHP;state=resolveRaidRoundStart({...state,round:2});expect(state.heroes[0]!.unit.currentHP).toBe(before-Math.round(first.unit.maxHP*.08));expect(state.log.at(-1)?.message).toContain("erupts");});
  it("emits a board-wide visual event when a raid phase begins",()=>{const state=initializeRaidMechanics(createCombatState("raid_white_maw_unbound",1,raidHeroes(),createSeededRandom(441)));expect(state.lastVisualEvent).toMatchObject({kind:"phase",actionId:"caldera_hunt"});});
  it("entombs two heroes during the White Maw middle phase",()=>{const random=createSeededRandom(45);let state=initializeRaidMechanics(createCombatState("raid_white_maw_unbound",1,raidHeroes(),random));state=resolveRaidRoundStart({...bossHp(state,.55),round:2});expect(state.raidMechanic?.activePhaseId).toBe("buried_alive");expect(state.heroes.filter((hero)=>hero.unit.activeConditions.some((condition)=>condition.conditionId==="rooted"))).toHaveLength(2);});
  it("contracts the final White Maw arena and damages heroes outside the safe center",()=>{const random=createSeededRandom(46);let state=initializeRaidMechanics(createCombatState("raid_white_maw_unbound",1,raidHeroes(),random));const before=state.heroes[0]!.unit.currentHP;state=resolveRaidRoundStart({...bossHp(state,.20),round:2});expect(state.raidMechanic?.activePhaseId).toBe("endless_white");expect(state.heroes[0]!.unit.currentHP).toBeLessThan(before);expect(state.log.at(-1)?.message).toContain("outer arena collapses");});
  it("reduces Serekh's marked strike when an adjacent hero intercepts it",()=>{const random=createSeededRandom(47);let state=initializeRaidMechanics(createCombatState("raid_chartmaker_ascendant",1,raidHeroes(),random));const before=new Map(state.heroes.map((hero)=>[hero.hero.id,hero.unit.currentHP]));state=resolveRaidRoundStart({...bossHp(state,.65),round:2});expect(state.raidMechanic?.activePhaseId).toBe("erase_the_vanguard");const damaged=state.heroes.filter((hero)=>hero.unit.currentHP<(before.get(hero.hero.id)??0));expect(damaged).toHaveLength(4);expect(state.log.some((entry)=>entry.message.includes("intercepted by an adjacent ally"))).toBe(true);});
  it("creates targetable raid objectives and lets an adjacent hero spend an action damaging one",()=>{const random=createSeededRandom(48);let state=initializeRaidMechanics(createCombatState("raid_broodheart_awakening",1,raidHeroes(),random));state={...state,awaitingHeroId:state.heroes[0]!.hero.id,heroes:state.heroes.map((hero,index)=>index?hero:{...hero,unit:{...hero.unit,position:{x:5,y:2}}})};expect(state.raidMechanic?.objectives).toHaveLength(4);state=strikeRaidObjective(state,{x:6,y:2});expect(state.actions.combatActionUsed).toBe(true);expect(state.raidMechanic?.objectives[0]?.currentIntegrity).toBe(1);});
  it("lets surviving Broodheart eggs restore the Queen every second round",()=>{const random=createSeededRandom(49);let state=initializeRaidMechanics(createCombatState("raid_broodheart_awakening",1,raidHeroes(),random));const queen=state.enemies.find((enemy)=>enemy.instance.enemyDefinitionId==="spider_queen")!;state={...state,round:2,enemies:state.enemies.map((enemy)=>enemy===queen?{...enemy,unit:{...enemy.unit,currentHP:enemy.unit.maxHP/2},instance:{...enemy.instance,currentHP:enemy.instance.maxHP/2}}:enemy)};const before=state.enemies.find((enemy)=>enemy.instance.enemyDefinitionId==="spider_queen")!.unit.currentHP;state=resolveRaidRoundStart(state);expect(state.enemies.find((enemy)=>enemy.instance.enemyDefinitionId==="spider_queen")!.unit.currentHP).toBeGreaterThan(before);expect(state.log.some((entry)=>entry.message.includes("Broodheart pulse"))).toBe(true);});
});
