import { describe, expect, it } from "vitest";
import { applyQuestRelationshipConsequences, getHeroCompatibility, healingReceivedFromHeroModifier, relationshipBand, relationshipCombatBonuses, setRelationship } from "../src/game/relationships/relationshipService";
import { combatUnit } from "./combatTestUtils";
import { createGuild } from "../src/game/guild/guildService";
import { testHero } from "./testHero";
import { deserializeGuild, serializeGuild } from "../src/game/save/saveService";
import { resolveSkill } from "../src/game/combat/skillResolver";
import { sequenceRandom } from "./combatTestUtils";
describe("hero relationships", () => {
  it("maps and clamps relationship bands", () => { expect(relationshipBand(-100)).toBe("rival"); expect(relationshipBand(-21)).toBe("dislike"); expect(relationshipBand(20)).toBe("neutral"); expect(relationshipBand(21)).toBe("friend"); expect(relationshipBand(100)).toBe("close_friend"); });
  it("grants adjacent friends +1 attack roll", () => { const relations = setRelationship([], "a", "b", 40); expect(relationshipCombatBonuses("a", [combatUnit("a", "heroes", { position: { x: 1, y: 1 } }), combatUnit("b", "heroes", { position: { x: 2, y: 1 } })], relations).attackRollModifier).toBe(1); });
  it("gives rivals damage tension and reduced mutual healing", () => { const relations = setRelationship([], "a", "b", -80); expect(relationshipCombatBonuses("a", [combatUnit("a", "heroes"), combatUnit("b", "heroes")], relations).physicalDamageModifier).toBe(.05); expect(healingReceivedFromHeroModifier("a", "b", relations)).toBe(-.10); });
  it("applies the rival healing penalty to resolved combat healing", () => { const healer = combatUnit("a", "heroes"); const target = combatUnit("b", "heroes", { currentHP: 40 }); const result = resolveSkill(healer, [target], { id: "test_heal", name: "Test Heal", type: "active", targetType: "single_ally", healMaxHpModifier: .40 }, sequenceRandom([]), { healingReceivedModifier: () => -.10 }); expect(result.targets[0]?.currentHP).toBe(76); });
  it("slowly develops bonds through shared quests and records meaningful band changes", () => { const a = testHero(); const b = { ...testHero(), id: "hero-b", name: "Bryn" }; const guild = createGuild(); guild.heroes = [a, b]; guild.relationships = setRelationship([], a.id, b.id, 20); const outcome = (hero: typeof a) => ({ heroId: hero.id, name: hero.name, raceId: hero.raceId, classId: hero.classId, gender: hero.gender, portraitVariant: hero.portraitVariant ?? 0, levelBefore: 1, levelAfter: 1, currentHP: 100, maxHP: 212, conditionIds: [], availableSkillPoints: 0, fellInBattle: false, newlyInjured: false }); const result = applyQuestRelationshipConsequences(guild, "victory", [outcome(a), outcome(b)], "goblin_patrol", "Goblin Patrol"); expect(result.changes[0]).toMatchObject({ previousScore: 20, newScore: 24, previousBand: "neutral", newBand: "friend", delta: 4 }); expect(result.guild.heroes.every((hero) => hero.history.events.some((event) => event.type === "relationship"))).toBe(true); });
  it("uses shared ideals and conflicting flaws to shape chemistry", () => { const profile = { personalityTraitId: "measured", idealId: "protection", bondId: "guild", flawId: "reckless" }; const a = { ...testHero(), roleplayProfile: profile }; const b = { ...testHero(), id: "hero-b", roleplayProfile: { ...profile, personalityTraitId: "vigilant", flawId: "rigid" } }; expect(getHeroCompatibility(a, b)).toMatchObject({ modifier: 2 }); const changed = { ...b, roleplayProfile: { ...b.roleplayProfile!, idealId: "honor", bondId: "family" } }; expect(getHeroCompatibility(a, changed)).toMatchObject({ modifier: -1 }); });
  it("persists relationships and migrates saves that predate them", () => { const guild = createGuild(); guild.relationships = setRelationship([], "a", "b", 34); expect(deserializeGuild(serializeGuild(guild)).relationships[0]?.score).toBe(34); const legacy = JSON.parse(serializeGuild(guild)); delete legacy.relationships; expect(deserializeGuild(JSON.stringify(legacy)).relationships).toEqual([]); });
});
