import { describe, expect, it } from "vitest";
import { createCombatBoard } from "../src/game/combat/grid/boardFactory";
import { spawnOccupants } from "../src/game/combat/grid/spawnService";
import { chooseEnemyDestination, selectTacticalTarget } from "../src/game/combat/tacticalAiService";
import { manhattanDistance } from "../src/game/combat/grid/distanceCalculator";
import { combatUnit, sequenceRandom } from "./combatTestUtils";
import { scoreEnemySkillOption } from "../src/game/combat/enemyBehaviorService";
import type { CombatSkillDefinition } from "../src/game/combat/skillTypes";

describe("enemy tactical movement", () => {
  it("avoids leaving melee reach when the positional gain is not worth a reaction", () => { const enemy = combatUnit("enemy", "enemies", { position: { x: 2, y: 2 }, movementRange: 3 }); const priorityTarget = combatUnit("target", "heroes", { position: { x: 5, y: 2 } }); const reactionThreat = combatUnit("threat", "heroes", { position: { x: 1, y: 2 } }); const board = spawnOccupants(createCombatBoard(), [{ occupantId: enemy.combatantId, position: enemy.position }, { occupantId: priorityTarget.combatantId, position: priorityTarget.position }, { occupantId: reactionThreat.combatantId, position: reactionThreat.position }]); expect(chooseEnemyDestination(board, enemy, priorityTarget, { preferredRange: 1, targetPriority: "lowest_hp" }, [reactionThreat])).toEqual(enemy.position); });
  it("moves a melee enemy toward preferred range using shared pathfinding", () => { const enemy = combatUnit("g", "enemies", { position: { x: 5, y: 2 }, movementRange: 3 }); const hero = combatUnit("h", "heroes", { position: { x: 1, y: 2 } }); const board = spawnOccupants(createCombatBoard(), [{ occupantId: "g", position: enemy.position }, { occupantId: "h", position: hero.position }]); expect(chooseEnemyDestination(board, enemy, hero, { preferredRange: 1, targetPriority: "nearest" })).toEqual({ x: 2, y: 2 }); });
  it("retreats when an archer target is too close", () => { const enemy = combatUnit("a", "enemies", { position: { x: 3, y: 2 }, movementRange: 3 }); const hero = combatUnit("h", "heroes", { position: { x: 2, y: 2 } }); const board = spawnOccupants(createCombatBoard(), [{ occupantId: "a", position: enemy.position }, { occupantId: "h", position: hero.position }]); const destination = chooseEnemyDestination(board, enemy, hero, { preferredRange: 4, retreatRange: 2, targetPriority: "lowest_hp" }); expect(manhattanDistance(destination, hero.position)).toBeGreaterThan(manhattanDistance(enemy.position, hero.position)); });
  it("supports nearest, lowest HP, highest damage, and random priorities", () => { const actor = combatUnit("a", "enemies", { position: { x: 5, y: 2 } }); const near = combatUnit("near", "heroes", { position: { x: 4, y: 2 }, currentHP: 90 }); const low = combatUnit("low", "heroes", { position: { x: 1, y: 2 }, currentHP: 10 }); const strong = combatUnit("strong", "heroes", { position: { x: 2, y: 2 }, stats: { ...combatUnit("x").stats, physicalDamage: 999 } }); expect(selectTacticalTarget(actor, [near, low, strong], { preferredRange: 1, targetPriority: "nearest" }, sequenceRandom([0]))?.combatantId).toBe("near"); expect(selectTacticalTarget(actor, [near, low, strong], { preferredRange: 1, targetPriority: "lowest_hp" }, sequenceRandom([0]))?.combatantId).toBe("low"); expect(selectTacticalTarget(actor, [near, low, strong], { preferredRange: 1, targetPriority: "highest_damage" }, sequenceRandom([0]))?.combatantId).toBe("strong"); expect(selectTacticalTarget(actor, [near, low], { preferredRange: 1, targetPriority: "random" }, sequenceRandom([.9]))?.combatantId).toBe("low"); });
  it("does not focus a wounded hero behind an impassable wall while a reachable target can be attacked", () => { const actor=combatUnit("a","enemies",{position:{x:1,y:2},movementRange:3});const reachable=combatUnit("reachable","heroes",{position:{x:2,y:2}});const trapped=combatUnit("trapped","heroes",{position:{x:7,y:2},currentHP:10});const board=spawnOccupants(createCombatBoard([],"battlefield",Array.from({length:7},(_,y)=>({position:{x:4,y},terrainType:"mountain" as const}))),[{occupantId:"a",position:actor.position},{occupantId:"reachable",position:reachable.position},{occupantId:"trapped",position:trapped.position}]);expect(selectTacticalTarget(actor,[reachable,trapped],{preferredRange:1,targetPriority:"lowest_hp"},sequenceRandom([0]),"ruthless",board)?.combatantId).toBe("reachable"); });
  it("uses terrain-cost immunity while planning movement",()=>{const actor=combatUnit("a","enemies",{position:{x:1,y:2},movementRange:1,ignoredTerrainMovementCosts:["shallow_water"]});const target=combatUnit("h","heroes",{position:{x:3,y:2}});const board=spawnOccupants(createCombatBoard([],"battlefield",[{position:{x:2,y:2},terrainType:"shallow_water"}]),[{occupantId:"a",position:actor.position},{occupantId:"h",position:target.position}]);expect(chooseEnemyDestination(board,actor,target,{preferredRange:1,targetPriority:"nearest"})).toEqual({x:2,y:2});});
  it("lets ruthless ranged enemies prefer useful high ground",()=>{const actor=combatUnit("a","enemies",{position:{x:3,y:2},movementRange:1});const target=combatUnit("h","heroes",{position:{x:7,y:2}});const board=spawnOccupants(createCombatBoard([],"battlefield",[{position:{x:4,y:2},terrainType:"normal",elevation:2}]),[{occupantId:"a",position:actor.position},{occupantId:"h",position:target.position}]);expect(chooseEnemyDestination(board,actor,target,{preferredRange:4,targetPriority:"nearest"},[],"ruthless")).toEqual({x:4,y:2});});
});

describe("enemy skill utility",()=>{it("does not multiply a single-target action's value by the number of possible targets",()=>{const actor=combatUnit("a","enemies");const targets=[combatUnit("h1"),combatUnit("h2"),combatUnit("h3")];const single={id:"single",name:"Single",type:"active",targetType:"single_enemy",damageType:"physical",damageMultiplier:1} satisfies CombatSkillDefinition;const group={...single,id:"group",name:"Group",targetType:"all_enemies"} satisfies CombatSkillDefinition;expect(scoreEnemySkillOption(single,actor,targets)).toBe(scoreEnemySkillOption(single,actor,[targets[0]!]));expect(scoreEnemySkillOption(group,actor,targets)).toBeGreaterThan(scoreEnemySkillOption(single,actor,targets));});});
