import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { CLASSES } from "../data/classes/classes"; import { CONDITIONS } from "../data/conditions/conditions"; import { RACES } from "../data/races/races"; import { HERO_SKILLS } from "../data/skills/heroSkills"; import { SUBCLASSES } from "../data/subclasses/subclasses"; import { TRAITS } from "../data/traits/traits";
import { ActionButton, BackButton, Panel, Portrait, SectionTitle, SegmentedTabs, colors } from "../components/ui";
import { SkillInfoPanel } from "../components/skills/SkillInfoPanel";
import type { CombatSkillDefinition } from "../game/combat/skillTypes";
import { getAvailableClassSkillPoints } from "../game/progression/skills/skillProgressionService";
import { getRaceNameColor } from "../ui/raceColors";
import { ATTRIBUTE_KEYS } from "../game/attributes/types"; import { createHeroCombatInstance, createHeroCombatUnit } from "../game/combat/heroCombatFactory"; import { calculateHero, collectHeroModifiers } from "../game/heroes/heroCalculator"; import type { Hero } from "../game/heroes/types"; import { getHeroSkillIds } from "../game/progression/subclasses/subclassService"; import { xpRequiredForNextLevel } from "../game/progression/xpSystem";
import { resolveEquipmentDefinition } from "../game/equipment/equipmentResolver";
import { HeroHistoryTimeline } from "../components/heroes/HeroHistoryTimeline";
const TABS = ["Overview", "Stats", "Skills", "Gear", "History"] as const; type Tab = typeof TABS[number];
const LABELS: Record<string,string> = { strength:"STR", dexterity:"DEX", constitution:"CON", intelligence:"INT", wisdom:"WIS", charisma:"CHA", maxHP:"Max HP", physicalAttack:"Physical Attack", physicalDefense:"Physical Defense", magicPower:"Magic Power", magicDefense:"Magic Defense", speed:"Speed", criticalChance:"Critical Chance" };
const modifierText = (operation: "flat"|"percentage", value: number, target: string) => `${value >= 0 ? "+" : ""}${operation === "percentage" ? `${Math.round(value * 100)}%` : value} ${LABELS[target] ?? target.replace(/([A-Z])/g," $1")}`;
function ResourceBar({ label, value, max, color }: { label:string; value:number; max:number; color:string }) { const ratio = max ? Math.max(0, Math.min(1, value / max)) : 0; return <View style={styles.resource}><View style={styles.row}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue}>{Math.round(value)} / {Math.round(max)}</Text></View><View style={styles.track}><View style={[styles.fill,{ width:`${ratio*100}%`, backgroundColor:color }]} /></View></View>; }
function HeroSkillsList({ skills }: { skills: CombatSkillDefinition[] }) { const [selectedId, setSelectedId] = useState<string>(); const selected = skills.find((skill) => skill.id === selectedId); return <>{skills.map((skill) => <Pressable key={skill.id} onPress={() => setSelectedId((value) => value === skill.id ? undefined : skill.id)}><Panel style={[styles.skill, selectedId === skill.id && styles.selectedSkill]}><View style={styles.row}><Text style={styles.entryName}>{skill.name}</Text><Text style={styles.skillAction}>{selectedId === skill.id ? "Hide" : "View details"}</Text></View><Text style={styles.hint}>{skill.type.replace(/_/g, " ").toUpperCase()} • Range {skill.range ?? "Self"}</Text></Panel></Pressable>)}{selected && <SkillInfoPanel skill={selected} />}</>; }
export function HeroDetailScreen({ hero, onBack, candidate=false, recruit, openSubclass, openSkillTree }: { hero:Hero; onBack():void; candidate?:boolean; recruit?():string|null; openSubclass?():void; openSkillTree?():void }) { const [tab,setTab]=useState<Tab>("Overview"); const [message,setMessage]=useState<string|null>(null); const calculated=calculateHero(hero); const instance=createHeroCombatInstance(hero); const unit=createHeroCombatUnit(hero,instance); const skills=getHeroSkillIds(hero).map((id)=>HERO_SKILLS[id]).filter(Boolean); const skillPoints=getAvailableClassSkillPoints(hero); const handleRecruit=()=>{const error=recruit?.(); if(error)setMessage(error); else onBack();}; return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><View style={styles.identity}><Portrait hero={hero} size={96}/><View style={styles.identityText}><Text style={[styles.name,{color:getRaceNameColor(hero.raceId)}]}>{hero.name}</Text><Text style={styles.meta}>{RACES[hero.raceId].name} • {CLASSES[hero.classId].name}</Text><Text style={styles.secondary}>Level {hero.level} • Age {hero.age}</Text></View></View>{candidate && <Panel style={styles.contract}><Text style={styles.rowValue}>{hero.recruitmentCost} gold • {hero.salary}/day</Text><ActionButton label="Recruit" onPress={handleRecruit}/>{message&&<Text style={styles.error}>{message}</Text>}</Panel>}<SegmentedTabs values={TABS} value={tab} onChange={setTab}/>
{tab==="Overview"&&<><ResourceBar label="HP" value={hero.currentHP} max={calculated.stats.maxHP} color={colors.green}/>{instance.maxMana>0&&<ResourceBar label="Mana" value={instance.currentMana} max={instance.maxMana} color={colors.blue}/>}<ResourceBar label="XP" value={hero.xp} max={xpRequiredForNextLevel(hero.level)} color={colors.gold}/><Panel><Text style={styles.entryName}>Potential {hero.potentialEstimateMin}–{hero.potentialEstimateMax}</Text><Text style={styles.hint}>Estimated scouting range. True potential remains hidden.</Text></Panel><SectionTitle>TRAITS</SectionTitle><Panel>{hero.traitIds.map((id)=><View key={id} style={styles.entry}><Text style={styles.entryName}>{TRAITS[id].name} · {TRAITS[id].category.toUpperCase()}</Text><Text style={styles.hint}>{TRAITS[id].description}</Text>{TRAITS[id].modifiers.map((m,i)=><Text key={i} style={styles.hint}>{modifierText(m.operation,m.value,m.target)}{m.condition?" while at or below 50% HP":""}</Text>)}</View>)}</Panel><SectionTitle>CONDITIONS</SectionTitle><Panel>{hero.conditions.length?hero.conditions.map((c)=><View key={c.conditionId} style={styles.entry}><Text style={styles.entryName}>{CONDITIONS[c.conditionId].name} • {c.remainingDuration} days</Text>{CONDITIONS[c.conditionId].modifiers.map((m,i)=><Text key={i} style={styles.hint}>{modifierText(m.operation,m.value,m.target)}</Text>)}</View>):<Text style={styles.hint}>No active conditions</Text>}</Panel><SectionTitle>SUBCLASS</SectionTitle><Panel><Text style={styles.entryName}>{hero.subclassId?`${CLASSES[hero.classId].name} → ${SUBCLASSES[hero.subclassId]?.name}`:hero.level>=10?"SUBCLASS AVAILABLE":"Unlocks at Level 10"}</Text>{hero.subclassId&&<Text style={styles.hint}>{SUBCLASSES[hero.subclassId]?.description}</Text>}{openSubclass&&!hero.subclassId&&<View style={styles.action}><ActionButton label={hero.level>=10?"Choose Subclass":"View Subclasses"} onPress={openSubclass}/></View>}</Panel></>}
{tab==="Stats"&&<><SectionTitle>ATTRIBUTE BREAKDOWN</SectionTitle><Panel>{ATTRIBUTE_KEYS.map((key)=>{const mods=collectHeroModifiers(hero).filter((m)=>m.target===key);return <View key={key} style={styles.breakdown}><View style={styles.row}><Text style={styles.rowLabel}>{LABELS[key]}</Text><Text style={styles.rowValue}>{hero.baseAttributes[key]} → {Math.round(calculated.attributes[key])}</Text></View>{mods.map((m,i)=><Text key={i} style={styles.source}>{m.source}: {m.sourceId} {modifierText(m.operation,m.value,m.target)}</Text>)}</View>})}</Panel><SectionTitle>COMBAT & QUEST STATS</SectionTitle><Panel>{Object.entries(calculated.stats).map(([key,value])=><View key={key} style={styles.row}><Text style={styles.rowLabel}>{LABELS[key]}</Text><Text style={styles.rowValue}>{key==="criticalChance"?`${(value*100).toFixed(1)}%`:Math.round(value)}</Text></View>)}<View style={styles.row}><Text style={styles.rowLabel}>Armor Class</Text><Text style={styles.rowValue}>{unit.stats.armorClass}</Text></View><View style={styles.row}><Text style={styles.rowLabel}>Movement</Text><Text style={styles.rowValue}>{unit.movementRange}</Text></View></Panel></>}
{tab==="Skills"&&<><Panel style={styles.skillProgress}><Text style={styles.entryName}>{skillPoints > 0 ? `${skillPoints} CLASS SKILL POINT${skillPoints === 1 ? "" : "S"} AVAILABLE` : "CLASS SKILL PROGRESSION"}</Text><Text style={styles.hint}>Level 1 heroes begin with one basic skill. Choose permanent class skills at Levels 2, 4, and 6.</Text>{openSkillTree&&<View style={styles.action}><ActionButton label={skillPoints > 0 ? "Choose a Skill" : "View Skill Tree"} onPress={openSkillTree}/></View>}</Panel><SectionTitle>LEARNED SKILLS</SectionTitle><HeroSkillsList skills={skills}/></>}
{tab==="Gear"&&<Panel>{Object.entries(hero.equipment).map(([slot,id])=><View key={slot} style={styles.row}><Text style={styles.rowLabel}>{slot.replace(/([0-9])/g," $1")}</Text><Text style={styles.rowValue}>{id?resolveEquipmentDefinition(id)?.name:"Empty"}</Text></View>)}</Panel>}
{tab==="History"&&<><Panel><View style={styles.row}><Text style={styles.rowLabel}>Quests Completed</Text><Text style={styles.rowValue}>{hero.history.questsCompleted}</Text></View><View style={styles.row}><Text style={styles.rowLabel}>Enemies Defeated</Text><Text style={styles.rowValue}>{hero.history.enemiesDefeated}</Text></View><View style={styles.row}><Text style={styles.rowLabel}>Recorded Deeds</Text><Text style={styles.rowValue}>{hero.history.events?.length ?? 0}</Text></View><SectionTitle>ACHIEVEMENTS</SectionTitle><Text style={styles.hint}>{hero.history.achievements.join(" • ")||"None yet"}</Text></Panel><SectionTitle>HERO CHRONICLE</SectionTitle><HeroHistoryTimeline events={hero.history.events ?? []}/></>}</ScrollView>; }
const styles=StyleSheet.create({content:{padding:18,paddingBottom:50},identity:{flexDirection:"row",alignItems:"center",gap:15,marginVertical:14},identityText:{flex:1},name:{color:colors.text,fontSize:29,fontWeight:"900"},meta:{color:colors.gold,fontWeight:"800",marginTop:4},secondary:{color:colors.muted,marginTop:4},contract:{gap:10,marginBottom:14},error:{color:colors.danger},resource:{marginBottom:12},row:{flexDirection:"row",justifyContent:"space-between",paddingVertical:7,gap:8},rowLabel:{color:colors.muted,textTransform:"capitalize"},rowValue:{color:colors.text,fontWeight:"800"},track:{height:8,backgroundColor:colors.panel2,borderRadius:5,overflow:"hidden"},fill:{height:"100%"},entry:{marginBottom:12},entryName:{color:colors.text,fontWeight:"800",fontSize:16},hint:{color:colors.muted,lineHeight:20,marginTop:3},action:{marginTop:10},breakdown:{paddingVertical:5,borderBottomWidth:StyleSheet.hairlineWidth,borderColor:colors.border},source:{color:colors.green,fontSize:11,marginLeft:10},skill:{marginBottom:10},skillProgress:{marginBottom:12,borderColor:colors.gold},selectedSkill:{borderColor:colors.gold},skillAction:{color:colors.gold,fontSize:11,fontWeight:"800"}});
