import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { ActionButton, BackButton, Panel, Portrait, SegmentedTabs, colors } from "../components/ui";
import { CLASSES } from "../data/classes/classes";
import { QUESTS } from "../data/quests/quests";
import { calculateHero } from "../game/heroes/heroCalculator";
import { getQuestAdventureStaminaCost } from "../game/heroes/adventureStaminaService";
import type { Party } from "../game/party/partyTypes";
import { validateParty } from "../game/party/partyValidator";
import { useGuild } from "../state/GuildContext";
import { getRaceNameColor } from "../ui/raceColors";
import { getPartyBondSummary, getQuestSkillCoverage } from "../game/party/partyReadinessService";
import { getEligiblePersonalQuestHeroes } from "../game/quests/questAvailability";
import { buildRecommendedRaidParty, findRaidByQuestId, getRaidCompositionWarnings } from "../game/raids/raidService";
import { loadPartyPreset, savePartyPreset } from "../game/party/partyPresetService";
import { getPartyCompositionSummary, suggestPartyForQuest } from "../game/party/partyRecommendationService";
type RosterRole="All"|"Frontline"|"Support"|"Ranged";const ROSTER_ROLES:RosterRole[]=["All","Frontline","Support","Ranged"];const ROLE_CLASSES:Record<Exclude<RosterRole,"All">,string[]>={Frontline:["warrior","paladin","berserker","bulwark","monk"],Support:["cleric","bard","summoner","paladin"],Ranged:["ranger","mage","spellbow","summoner"]};
const extraStyles=StyleSheet.create({presetToggle:{alignItems:"center",backgroundColor:colors.panel,borderColor:colors.border,borderRadius:9,borderWidth:1,flexDirection:"row",justifyContent:"space-between",marginBottom:9,padding:11},presetToggleMark:{color:colors.gold,fontSize:18,fontWeight:"900"},search:{backgroundColor:colors.panel,borderColor:colors.border,borderRadius:9,borderWidth:1,color:colors.text,marginBottom:9,paddingHorizontal:12,paddingVertical:10}});

export function PartySelectionScreen({ questId, onBack, start }: { questId: string; onBack(): void; start(party: Party): void }) {
  const { guild,updateGuild } = useGuild(); const quest = QUESTS[questId]!; const [ids, setIds] = useState<string[]>([]); const [presetMessage,setPresetMessage]=useState<string>();const[showPresets,setShowPresets]=useState(false);const[roleFilter,setRoleFilter]=useState<RosterRole>("All");const[search,setSearch]=useState(""); const staminaCost = getQuestAdventureStaminaCost(quest);
  const party = { id: `party-${questId}`, heroIds: ids }; const validation = validateParty(party, guild.heroes, quest.maxPartySize); const sizeValid = ids.length >= quest.minPartySize && ids.length <= quest.maxPartySize;
  const selectedHeroes = ids.map((id) => guild.heroes.find((hero) => hero.id === id)).filter((hero): hero is NonNullable<typeof hero> => Boolean(hero));
  const personalHeroes=getEligiblePersonalQuestHeroes(quest,guild.heroes);const personalHeroSelected=!quest.personalHeroRequirement||personalHeroes.some((hero)=>ids.includes(hero.id));
  const averageLevel = selectedHeroes.length ? selectedHeroes.reduce((sum, hero) => sum + hero.level, 0) / selectedHeroes.length : 0; const recommendedMin = quest.recommendedLevelMin ?? 1; const underLevelled = averageLevel > 0 && averageLevel < recommendedMin; const minimumPartyLevel = quest.minimumPartyAverageLevel ?? 0; const levelGateMet = !minimumPartyLevel || averageLevel >= minimumPartyLevel;
  const skillCoverage=getQuestSkillCoverage(quest,selectedHeroes); const bonds=getPartyBondSummary(selectedHeroes,guild.relationships);
  const composition=getPartyCompositionSummary(quest,selectedHeroes);
  const raid=findRaidByQuestId(questId);const raidWarnings=raid?getRaidCompositionWarnings(ids,guild.heroes):[];
  const visibleHeroes=guild.heroes.filter((hero)=>(roleFilter==="All"||ROLE_CLASSES[roleFilter].includes(hero.classId))&&(!search.trim()||`${hero.name} ${CLASSES[hero.classId].name}`.toLowerCase().includes(search.trim().toLowerCase()))).sort((a,b)=>Number(ids.includes(b.id))-Number(ids.includes(a.id))||b.level-a.level);
  const toggle = (id: string) => setIds((current) => current.includes(id) ? current.filter((entry) => entry !== id) : current.length < quest.maxPartySize ? [...current, id] : current);
  const slot=(index:number)=>{const hero=guild.heroes.find((entry)=>entry.id===ids[index]);return <View key={index} style={[styles.slot,raid&&styles.raidSlot,hero&&styles.filled]}>{hero?<><Portrait hero={hero} size={raid?36:44}/><Text numberOfLines={1} style={[styles.slotName,{color:getRaceNameColor(hero.raceId)}]}>{hero.name}</Text></>:<><Text style={styles.plus}>+</Text><Text style={styles.empty}>Slot {index+1}</Text></>}</View>};
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.title}>Assemble Party</Text><Text style={styles.quest}>{quest.name} · Difficulty {quest.difficulty} · Recommended Lv {recommendedMin}–{quest.recommendedLevelMax ?? recommendedMin} · Cost {staminaCost} readiness</Text>
    <Pressable accessibilityRole="button" accessibilityState={{expanded:showPresets}} onPress={()=>setShowPresets((value)=>!value)} style={extraStyles.presetToggle}><Text style={styles.readinessTitle}>SQUAD PRESETS</Text><Text style={extraStyles.presetToggleMark}>{showPresets?"−":"+"}</Text></Pressable>{showPresets&&<Panel style={styles.presets}><Text style={styles.meta}>Save up to three lineups. Unavailable heroes are skipped when a squad is loaded.</Text><View style={styles.presetRows}>{[0,1,2].map((index)=>{const preset=guild.partyPresets[index];return <View key={index} style={styles.presetRow}><Pressable accessibilityRole="button" disabled={!preset} onPress={()=>{if(!preset)return;const loaded=loadPartyPreset(guild,preset.id,quest.maxPartySize,staminaCost);setIds(loaded);setPresetMessage(loaded.length?`${preset.name} loaded.`:`${preset.name} has no available heroes.`);}} style={[styles.presetButton,!preset&&styles.disabled]}><Text style={styles.presetText}>{preset?`${preset.name} · ${preset.heroIds.length}`:`Squad ${index+1} · Empty`}</Text></Pressable><Pressable accessibilityRole="button" disabled={!ids.length} onPress={()=>{try{updateGuild(savePartyPreset(guild,ids,index));setPresetMessage(`Squad ${index+1} saved.`);}catch(error){setPresetMessage(error instanceof Error?error.message:"Could not save squad.");}}} style={[styles.savePreset,!ids.length&&styles.disabled]}><Text style={styles.savePresetText}>SAVE</Text></Pressable></View>})}</View>{presetMessage?<Text style={styles.presetMessage}>{presetMessage}</Text>:null}</Panel>}
    {raid?<><View style={styles.slots}><ActionButton label="Auto-fill Balanced" onPress={()=>setIds(buildRecommendedRaidParty(guild.heroes,staminaCost))}/><ActionButton label="Clear" disabled={!ids.length} onPress={()=>setIds([])}/></View><View style={styles.raidSquads}><View style={styles.squadBlock}><Text style={styles.vanguardLabel}>VANGUARD · SLOTS 1–4</Text><View style={styles.slots}>{[0,1,2,3].map(slot)}</View></View><View style={styles.squadBlock}><Text style={styles.supportLabel}>SUPPORT · SLOTS 5–8</Text><View style={styles.slots}>{[4,5,6,7].map(slot)}</View></View></View></>:<><View style={styles.suggestionRow}><View style={styles.suggestionAction}><ActionButton label="Suggest Party" onPress={()=>setIds(suggestPartyForQuest(guild,quest))}/></View><View style={styles.suggestionAction}><ActionButton label="Clear" disabled={!ids.length} onPress={()=>setIds([])}/></View></View><View style={styles.slots}>{Array.from({length:quest.maxPartySize},(_,index)=>slot(index))}</View></>}
    {raid&&ids.length===8&&<Panel style={styles.readiness}><Text style={styles.readinessTitle}>RAID COMPOSITION</Text>{raidWarnings.length?raidWarnings.map((warning)=><Text key={warning} style={styles.danger}>! {warning}</Text>):<Text style={styles.ready}>✓ Both squads have frontline, support and ranged coverage.</Text>}<Text style={styles.meta}>Warnings are advisory. Slot order controls which four heroes form each squad.</Text></Panel>}
    {selectedHeroes.length > 0 && <Panel style={[styles.readiness, (underLevelled||composition.warnings.length>0) && styles.dangerPanel]}><View style={styles.summaryTop}><View><Text style={styles.readinessTitle}>PARTY READINESS</Text><Text style={styles.meta}>Average Lv {composition.averageLevel.toFixed(1)} · HP {Math.round(composition.averageHpPercent)}% · Readiness {Math.round(composition.averageReadiness)}</Text></View><Text style={underLevelled ? styles.danger : styles.ready}>{underLevelled?"DANGER":"READY"}</Text></View><View style={styles.roleRow}><Text style={composition.frontline?styles.roleReady:styles.roleMissing}>Frontline {composition.frontline}</Text><Text style={composition.support?styles.roleReady:styles.roleMissing}>Support {composition.support}</Text><Text style={composition.ranged?styles.roleReady:styles.roleMissing}>Ranged {composition.ranged}</Text></View>{underLevelled&&<Text style={styles.danger}>Below recommended level {recommendedMin}.</Text>}{composition.warnings.map((warning)=><Text key={warning} style={styles.warningLine}>! {warning}</Text>)}</Panel>}
    {selectedHeroes.length > 0 && (skillCoverage.length > 0 || selectedHeroes.length > 1) && <Panel style={styles.readiness}><Text style={styles.readinessTitle}>SKILLS & PARTY CHEMISTRY</Text>{skillCoverage.map((entry)=><Text key={entry.skillId} style={entry.covered?styles.ready:styles.danger}>{entry.covered?"✓":"!"} {entry.name}{entry.bestHeroName?` · ${entry.bestHeroName} +${entry.bonus}`:" · no proficient hero"}</Text>)}{selectedHeroes.length>1&&<Text style={styles.meta}>{bonds.friends} friendly bond{bonds.friends===1?"":"s"} · {bonds.rivals} rival bond{bonds.rivals===1?"":"s"}{bonds.strongestLabel?` · ${bonds.strongestLabel}`:""}</Text>}{bonds.warning&&<Text style={styles.danger}>{bonds.warning}</Text>}</Panel>}
    <TextInput accessibilityLabel="Search party roster" placeholder="Search hero or class…" placeholderTextColor={colors.muted} value={search} onChangeText={setSearch} style={extraStyles.search}/><SegmentedTabs values={ROSTER_ROLES} value={roleFilter} onChange={setRoleFilter}/>
    {visibleHeroes.map((hero) => { const selected = ids.includes(hero.id); const stats = calculateHero(hero); const disabled = !hero.isAvailable || hero.currentHP <= 0 || hero.adventureStamina < staminaCost; return <Pressable key={hero.id} disabled={disabled} onPress={() => toggle(hero.id)}><Panel style={[styles.hero, selected && styles.selected, disabled && styles.disabled]}><View style={styles.row}><Portrait hero={hero} size={52}/><View style={styles.flex}><Text style={[styles.name,{color:getRaceNameColor(hero.raceId)}]}>{hero.name} · Lv {hero.level}</Text><Text style={styles.meta}>{CLASSES[hero.classId].name} · HP {Math.round(hero.currentHP)}/{Math.round(stats.stats.maxHP)}</Text><Text style={styles.meta}>Readiness {hero.adventureStamina}/100 · {hero.conditions.length ? hero.conditions.map((condition) => condition.conditionId).join(", ") : "Ready"}</Text></View><Text style={styles.check}>{selected ? "✓" : disabled ? "Unavailable" : "○"}</Text></View></Panel></Pressable>; })}
    {(!validation.valid || !sizeValid || !levelGateMet || !personalHeroSelected) && <Text style={styles.error}>{!ids.length ? `Select ${quest.minPartySize}–${quest.maxPartySize} heroes.` : !sizeValid ? `This quest requires ${quest.minPartySize}–${quest.maxPartySize} heroes.` : !personalHeroSelected?`Include the hero whose personal story opened this quest: ${personalHeroes.map((hero)=>hero.name).join(" or ")}.`:!levelGateMet ? `This boss requires a party averaging Level ${minimumPartyLevel}. Current average: ${averageLevel.toFixed(1)}.` : validation.errors.join(" · ")}</Text>}
    <ActionButton label={!personalHeroSelected?"Personal Hero Required":!levelGateMet && ids.length ? `Requires Average Level ${minimumPartyLevel}` : underLevelled ? "Start Despite Danger" : "Start Quest"} disabled={!validation.valid || !sizeValid || !levelGateMet || !personalHeroSelected} onPress={() => start(party)}/>
  </ScrollView>;
}

const styles = StyleSheet.create({ content:{padding:16,paddingBottom:45},title:{color:colors.text,fontSize:30,fontWeight:"900",marginTop:10},quest:{color:colors.gold,marginTop:4,marginBottom:16},presets:{marginBottom:12,padding:11},suggestionRow:{flexDirection:"row",gap:7,marginBottom:8},suggestionAction:{flex:1},presetRows:{gap:6,marginTop:9},presetRow:{flexDirection:"row",gap:6},presetButton:{backgroundColor:colors.panel2,borderColor:colors.border,borderRadius:7,borderWidth:1,flex:1,padding:9},presetText:{color:colors.text,fontSize:11,fontWeight:"800"},savePreset:{alignItems:"center",borderColor:colors.gold,borderRadius:7,borderWidth:1,justifyContent:"center",paddingHorizontal:12},savePresetText:{color:colors.gold,fontSize:9,fontWeight:"900"},presetMessage:{color:colors.green,fontSize:10,marginTop:7},slots:{flexDirection:"row",flexWrap:"wrap",gap:7,marginBottom:12},raidSquads:{gap:8,marginBottom:4},squadBlock:{backgroundColor:"#151d2b",borderColor:colors.border,borderRadius:10,borderWidth:1,padding:8},vanguardLabel:{color:"#ed9c76",fontSize:10,fontWeight:"900",letterSpacing:.7,marginBottom:7},supportLabel:{color:"#77bfe9",fontSize:10,fontWeight:"900",letterSpacing:.7,marginBottom:7},slot:{flexGrow:1,flexBasis:70,height:92,borderWidth:1,borderStyle:"dashed",borderColor:colors.border,borderRadius:10,alignItems:"center",justifyContent:"center"},raidSlot:{flexBasis:"22%",height:78},filled:{borderStyle:"solid",borderColor:colors.gold,backgroundColor:colors.panel},plus:{color:colors.muted,fontSize:23},empty:{color:colors.muted,fontSize:10},slotName:{fontSize:10,marginTop:4,maxWidth:"95%"},readiness:{marginBottom:14,padding:12},summaryTop:{alignItems:"center",flexDirection:"row",justifyContent:"space-between",gap:8},roleRow:{flexDirection:"row",flexWrap:"wrap",gap:6,marginTop:9},roleReady:{backgroundColor:"#173d2b",borderRadius:5,color:colors.green,fontSize:9,fontWeight:"900",paddingHorizontal:7,paddingVertical:4},roleMissing:{backgroundColor:"#3f2726",borderRadius:5,color:colors.danger,fontSize:9,fontWeight:"900",paddingHorizontal:7,paddingVertical:4},warningLine:{color:"#efb46f",fontSize:10,fontWeight:"800",lineHeight:15,marginTop:5},dangerPanel:{borderColor:colors.danger},readinessTitle:{color:colors.text,fontWeight:"900"},ready:{color:colors.green,fontSize:12,marginTop:5},danger:{color:colors.danger,fontSize:12,marginTop:5,fontWeight:"700"},hero:{marginBottom:8},selected:{borderColor:colors.gold,backgroundColor:colors.panel2},disabled:{opacity:.45},row:{flexDirection:"row",alignItems:"center",gap:10},flex:{flex:1},name:{fontWeight:"900"},meta:{color:colors.muted,fontSize:12,marginTop:3},check:{color:colors.gold,fontWeight:"900"},error:{color:colors.danger,marginVertical:10} });
