import React, { useState } from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, EmptyState, Panel, SecondaryButton, SegmentedTabs, colors } from "../components/ui";
import { QUEST_ENCOUNTERS } from "../data/encounters/questEncounters";
import { getEnemyDefinition } from "../data/enemies";
import { QUESTS } from "../data/quests/quests";
import { REGIONS } from "../data/world/regions";
import { SETTLEMENTS } from "../data/world/settlements";
import { isQuestAvailableAtCurrentLocation, isQuestAvailableForGuild, isQuestBoardCategoryUnlocked } from "../game/quests/questAvailability";
import { useGuild } from "../state/GuildContext";
import { filterQuests, getQuestReadiness, sortQuestsForRoster, type QuestTab } from "../ui/questList";
import { getAvailableCampaignNodes } from "../game/campaign/campaignService";
import { DUNGEON_UNLOCK_HERO_COUNT } from "../game/dungeons/dungeonDraftService";
import { getQuestTravelStep } from "../game/quests/questTravelService";
import { getDefaultTravelPartyHeroIds } from "../game/world/travelPartyService";
export const QUEST_SCREEN_TABS: QuestTab[] = ["Campaign", "Side Quests", "Bosses"];
const TABS = QUEST_SCREEN_TABS;

export function QuestSelectionScreen({ onBack, selectQuest, openCampaign, openDungeons, openOperations, openRaids, initialTab = "Campaign" }: { onBack?: () => void; selectQuest(id: string): void; openCampaign?(): void; openDungeons?(): void; openOperations?(): void; openRaids?(): void; initialTab?: QuestTab }) {
  const { guild } = useGuild();const [showQuestDetails,setShowQuestDetails]=useState(!guild.uiPreferences.compactQuestCards);
  const [tab, setTab] = useState<QuestTab>(initialTab === "Contracts" ? "Campaign" : initialTab); const [showActivities,setShowActivities]=useState(false); const categoryType = tab === "Side Quests" ? "side" : tab === "Bosses" ? "boss" : "campaign"; const highestHeroLevel = Math.max(1, ...guild.heroes.map((hero) => hero.level)); const fieldHeroes = [...guild.heroes].sort((a,b)=>b.level-a.level).slice(0,4); const fieldLevel = fieldHeroes.length ? fieldHeroes.reduce((sum,hero)=>sum+hero.level,0)/fieldHeroes.length : 1; const categoryUnlocked = isQuestBoardCategoryUnlocked(categoryType, guild.world, highestHeroLevel); const dungeonChapterUnlocked = guild.world.completedCampaignNodeIds.includes("broken_wardstone"); const dungeonRosterUnlocked = guild.heroes.length >= DUNGEON_UNLOCK_HERO_COUNT; const dungeonUnlocked = dungeonChapterUnlocked && dungeonRosterUnlocked; const operationsRosterUnlocked = guild.heroes.length >= 6; const operationsUnlocked = dungeonChapterUnlocked && operationsRosterUnlocked;const nextCampaignNode=getAvailableCampaignNodes(guild.world)[0];
  const availableCategoryQuests = categoryUnlocked ? filterQuests(Object.values(QUESTS), tab, guild.world.completedQuestIds).filter((quest) => !quest.hiddenFromQuestBoard && guild.world.unlockedRegionIds.includes(quest.regionId) && isQuestAvailableForGuild(quest,guild.world,guild.heroes)) : [];
  const localQuests = sortQuestsForRoster(availableCategoryQuests.filter((quest)=>isQuestAvailableAtCurrentLocation(quest,guild.world)),fieldLevel);
  const remoteQuests = sortQuestsForRoster(availableCategoryQuests.filter((quest)=>!isQuestAvailableAtCurrentLocation(quest,guild.world)),fieldLevel);
  const quests = [...localQuests, ...remoteQuests];
  const travelPartySize = getDefaultTravelPartyHeroIds(guild).length;
  return <ScrollView contentContainerStyle={styles.content}>{onBack && <BackButton onPress={onBack}/>}<Text style={styles.title}>Quests</Text><Text style={styles.intro}>Showing work available at {guild.world.currentSettlementId?.replace(/_/g," ") ?? REGIONS[guild.world.currentRegionId]?.name ?? "your current location"}. Readiness uses the average level of your four strongest heroes: {fieldLevel.toFixed(1)}.</Text>
    {(openDungeons||openOperations)&&<View style={styles.activitiesToggle}><SecondaryButton label={showActivities?"Hide Other Activities":"Other Activities · Expeditions & Operations"} onPress={()=>setShowActivities((value)=>!value)}/></View>}
    {showActivities&&<>{openDungeons && <View style={styles.expedition}><Text style={styles.expeditionTitle}>WARDSTONE EXPEDITIONS · {DUNGEON_UNLOCK_HERO_COUNT} HEROES</Text><Text style={styles.expeditionText}>{dungeonUnlocked ? "Choose 1 of 3 themes · 7-day victory cooldown" : !dungeonChapterUnlocked ? "LOCKED · Complete Chapter 1 and defeat its boss" : `LOCKED · Recruit ${DUNGEON_UNLOCK_HERO_COUNT} heroes · Owned ${guild.heroes.length}/${DUNGEON_UNLOCK_HERO_COUNT}`}</Text><ActionButton disabled={!dungeonUnlocked} label={guild.activeDungeonRun ? "Resume Dungeon Run" : "Enter Roguelite Dungeon"} onPress={openDungeons}/></View>}{openOperations && <View style={styles.operation}><Text style={styles.operationTitle}>CRISIS OPERATIONS · 6 HEROES</Text><Text style={styles.expeditionText}>{operationsUnlocked ? `Two simultaneous teams · D20 command phases${guild.currentDay < guild.guildOperations.nextAvailableDay ? ` · Ready Day ${guild.guildOperations.nextAvailableDay}` : ""}` : !dungeonChapterUnlocked ? "LOCKED · Establish the guild by completing Chapter 1" : `LOCKED · Recruit 6 heroes · Owned ${guild.heroes.length}/6`}</Text><ActionButton disabled={!operationsUnlocked || guild.currentDay < guild.guildOperations.nextAvailableDay} label="Open Crisis Operations" onPress={openOperations}/></View>}{openRaids&&<View style={styles.operation}><Text style={styles.operationTitle}>GUILD RAIDS · 8 HEROES</Text><Text style={styles.expeditionText}>Two squads · largest tactical arenas · multi-phase bosses · weekly victory lockouts</Text><ActionButton label="Open Guild Raids" onPress={openRaids}/></View>}</>}
    <SegmentedTabs values={TABS} value={tab} onChange={setTab}/><View style={styles.activitiesToggle}><SecondaryButton label={showQuestDetails?"Compact Quest Cards":"Show Quest Details"} onPress={()=>setShowQuestDetails((value)=>!value)}/></View>{tab === "Campaign" && openCampaign && <Panel style={styles.campaign}><Text style={styles.recommended}>CONTINUE CHAPTER {guild.world.campaignChapter}</Text><Text style={styles.name}>{nextCampaignNode?.title??"Campaign Timeline"}</Text><Text style={styles.detail}>{nextCampaignNode?.description??"Review completed chapters and the next available story objective."}</Text><View style={{marginTop:10}}><ActionButton label={nextCampaignNode?.questId?"Prepare Next Campaign Quest":"Open Campaign Timeline"} onPress={openCampaign}/></View></Panel>}
    {quests.map((quest) => {
      const factions = [...new Set(quest.encounterIds.flatMap((id) => QUEST_ENCOUNTERS[id]?.enemies ?? []).map((entry) => getEnemyDefinition(entry.enemyDefinitionId).factionId))];
      const region = REGIONS[quest.regionId];
      const readiness=getQuestReadiness(quest,fieldLevel);
      const local = isQuestAvailableAtCurrentLocation(quest,guild.world);
      const recommendedHere = localQuests[0]?.id === quest.id;
      const destination = quest.settlementIds?.length ? quest.settlementIds.map((id)=>SETTLEMENTS[id]?.name??id.replace(/_/g," ")).join(" / ") : region?.name ?? quest.regionId;
      let travelStep: ReturnType<typeof getQuestTravelStep> | null = null;
      if (!local && travelPartySize > 0) { try { travelStep = getQuestTravelStep(guild, quest.id, travelPartySize); } catch { travelStep = null; } }
      return <Panel key={quest.id} style={[styles.card,recommendedHere&&styles.recommendedCard,!local&&styles.remoteCard]}>
        <View style={styles.row}><View style={styles.flex}><View style={styles.labelRow}>{recommendedHere&&<Text style={styles.recommended}>RECOMMENDED HERE</Text>}{!local&&<Text style={styles.travelRequired}>TRAVEL REQUIRED</Text>}<Text style={[styles.readiness,readiness==="DANGER"&&styles.danger,readiness==="ROUTINE"&&styles.routine]}>{readiness}</Text></View><Text style={styles.name}>{quest.name}</Text><Text style={styles.difficulty}>{quest.questType.toUpperCase()} · Difficulty {quest.difficulty} · Lv {quest.recommendedLevelMin ?? region?.recommendedLevelMin}–{quest.recommendedLevelMax ?? region?.recommendedLevelMax}</Text></View><ActionButton label={local?"Inspect":"Inspect / Travel"} onPress={() => selectQuest(quest.id)}/></View>
        {!local&&<View style={styles.travelPreview}><Text style={styles.travelDestination}>DESTINATION · {destination}</Text><Text style={styles.travelMeta}>{travelStep ? `Next leg: ${travelStep.label} · ${travelStep.days}d · ${travelStep.rationCost} rations` : "Open the quest for route guidance."}</Text></View>}
        {showQuestDetails&&<><Text style={styles.detail}>{region?.name} · Party {quest.minPartySize}–{quest.maxPartySize} · {quest.encounterIds.length} encounter{quest.encounterIds.length === 1 ? "" : "s"}</Text><Text style={styles.detail}>Expected foes: {factions.join(", ") || "Unknown"}</Text><Text style={styles.reward}>{quest.goldRewardMin}–{quest.goldRewardMax} gold · {quest.xpRewardPerHero} XP/hero</Text></>}
      </Panel>;
    })}
    {!quests.length && <EmptyState title={categoryUnlocked ? `No ${tab.toLowerCase()} available` : `${tab} locked`} message={categoryUnlocked ? "Progress the campaign, unlock more regions, or check another category." : tab === "Contracts" ? `Raise a hero to Level 2 to unlock repeatable contracts. Highest level: ${highestHeroLevel}.` : tab === "Side Quests" ? `Raise a hero to Level 3 to unlock side quests. Highest level: ${highestHeroLevel}.` : "Complete Chapter 1 before optional boss quests appear."}/>}
  </ScrollView>;
}
const styles = StyleSheet.create({ content:{padding:16,paddingBottom:40},title:{color:colors.text,fontSize:30,fontWeight:"900",marginTop:8},intro:{color:colors.muted,lineHeight:20,marginVertical:9},activitiesToggle:{marginBottom:12},expedition:{backgroundColor:"#241f2d",borderColor:"#8b6cab",borderWidth:1,borderRadius:14,padding:14,gap:7,marginBottom:10},expeditionTitle:{color:"#c6a7e5",fontWeight:"900",letterSpacing:1.2},operation:{backgroundColor:"#20291f",borderColor:"#718957",borderWidth:1,borderRadius:14,padding:14,gap:7,marginBottom:14},operationTitle:{color:"#a9cb82",fontWeight:"900",letterSpacing:1.2},expeditionText:{color:colors.muted,fontSize:12,marginBottom:3},campaign:{marginBottom:12},card:{marginBottom:11},recommendedCard:{borderColor:colors.gold},remoteCard:{borderColor:"#53606b",opacity:.94},labelRow:{flexDirection:"row",alignItems:"center",gap:6,marginBottom:4},recommended:{color:colors.gold,fontSize:9,fontWeight:"900",letterSpacing:.7},travelRequired:{color:"#efb46f",fontSize:9,fontWeight:"900",letterSpacing:.7},readiness:{color:colors.green,fontSize:9,fontWeight:"900",letterSpacing:.7},danger:{color:colors.danger},routine:{color:colors.muted},row:{flexDirection:"row",alignItems:"center",gap:10},flex:{flex:1},name:{color:colors.text,fontSize:19,fontWeight:"900"},difficulty:{color:colors.gold,fontSize:12,marginTop:3},detail:{color:colors.muted,marginTop:7},travelPreview:{backgroundColor:colors.panel2,borderRadius:7,marginTop:9,padding:8},travelDestination:{color:"#efb46f",fontSize:9,fontWeight:"900",letterSpacing:.5},travelMeta:{color:colors.muted,fontSize:10,marginTop:4},reward:{color:colors.green,fontWeight:"700",marginTop:8} });
