import React from "react";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, Panel, SectionTitle, colors } from "../components/ui";
import { QUESTS } from "../data/quests/quests";
import { QUEST_ENCOUNTERS } from "../data/encounters/questEncounters";
import { getEnemyDefinition } from "../data/enemies";
import { REGIONS } from "../data/world/regions";
import { SETTLEMENTS } from "../data/world/settlements";
import { useGuild } from "../state/GuildContext";
import { getQuestReadiness } from "../ui/questList";
import { getQuestSkillCoverage } from "../game/party/partyReadinessService";
import type { Hero } from "../game/heroes/types";
import type { QuestDefinition } from "../game/quests/questTypes";
import { getQuestCombatProfile } from "../game/quests/questCombatProfileService";
import { isQuestAvailableAtCurrentLocation } from "../game/quests/questAvailability";

function QuestSkillPreview({ quest, heroes }: { quest: QuestDefinition; heroes: readonly Hero[] }) {
  const checks = getQuestSkillCoverage(quest, heroes); if (!checks.length) return null;
  return <><SectionTitle>EXPECTED CHECKS</SectionTitle><Panel>{checks.map((entry) => <Text key={entry.skillId} style={entry.covered ? styles.covered : styles.uncovered}>{entry.covered ? "✓" : "!"} {entry.name}{entry.bestHeroName ? ` · ${entry.bestHeroName} +${entry.bonus}` : " · roster lacks proficiency"}</Text>)}<Text style={styles.optional}>This is preparation knowledge, not a requirement. Untrained heroes may still attempt a D20 check.</Text></Panel></>;
}

export function QuestDetailScreen({ questId, onBack, assemble, openWorld }: { questId: string; onBack(): void; assemble(): void; openWorld(): void }) {
  const { guild } = useGuild(); const quest = QUESTS[questId];
  if (!quest) return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.title}>Quest unavailable</Text></ScrollView>;
  const enemies = quest.encounterIds.flatMap((id) => QUEST_ENCOUNTERS[id]?.enemies ?? []); const factions = [...new Set(enemies.map((entry) => getEnemyDefinition(entry.enemyDefinitionId).factionId))]; const region = REGIONS[quest.regionId];const combatProfile=getQuestCombatProfile(quest);
  const fieldHeroes = [...guild.heroes].filter((hero) => hero.currentHP > 0 && hero.isAvailable).sort((a,b) => b.level-a.level).slice(0,quest.maxPartySize); const fieldLevel = fieldHeroes.length ? fieldHeroes.reduce((sum,hero) => sum+hero.level,0)/fieldHeroes.length : 1; const readiness = getQuestReadiness(quest,fieldLevel); const enoughHeroes = fieldHeroes.length >= quest.minPartySize; const locationReady = isQuestAvailableAtCurrentLocation(quest, guild.world); const requiredSettlements = (quest.settlementIds ?? []).map((id) => SETTLEMENTS[id]?.name ?? id.replace(/_/g, " ")); const requiredLocation = requiredSettlements.length ? `${requiredSettlements.join(" / ")} · ${region?.name ?? quest.regionId}` : region?.name ?? quest.regionId; const currentLocation = guild.world.currentSettlementId ? SETTLEMENTS[guild.world.currentSettlementId]?.name ?? guild.world.currentSettlementId.replace(/_/g, " ") : REGIONS[guild.world.currentRegionId]?.name ?? guild.world.currentRegionId; const canAssemble = locationReady && enoughHeroes && (readiness !== "DANGER" || !quest.minimumPartyAverageLevel);
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.title}>{quest.name}</Text><Text style={styles.kind}>{quest.questType.toUpperCase()} • {region?.name}</Text><Text style={styles.description}>{quest.description ?? `A ${quest.difficulty}-star assignment in ${region?.name}. Prepare for ${quest.encounterIds.length} tactical encounters.`}</Text>
    <SectionTitle>LOCATION</SectionTitle><Panel style={locationReady ? styles.locationReady : styles.locationBlocked}><Text style={locationReady ? styles.locationReadyText : styles.locationBlockedText}>{locationReady ? "✓ YOU ARE AT THE QUEST LOCATION" : "TRAVEL REQUIRED"}</Text><Text style={styles.line}>Required: {requiredLocation}</Text><Text style={styles.line}>Current: {currentLocation}</Text>{!locationReady ? <ActionButton label="Open World Map" onPress={openWorld} /> : null}</Panel>
    {quest.storyContext ? <><SectionTitle>WHY THIS MATTERS</SectionTitle><Panel><Text style={styles.contextLabel}>Requested by</Text><Text style={styles.line}>{quest.storyContext.patron}</Text><Text style={styles.contextLabel}>Why your guild accepts</Text><Text style={styles.contextCopy}>{quest.storyContext.guildReason}</Text><Text style={styles.contextLabel}>Story connection</Text><Text style={styles.contextCopy}>{quest.storyContext.campaignConnection}</Text></Panel></> : null}
    <SectionTitle>PARTY READINESS</SectionTitle><Panel style={[styles.readinessPanel,readiness === "DANGER" && styles.dangerPanel]}><Text style={[styles.readiness,readiness === "DANGER" && styles.danger]}>{readiness} · FIELD LEVEL {fieldLevel.toFixed(1)}</Text><Text style={styles.line}>{fieldHeroes.length} available heroes · requires {quest.minPartySize}–{quest.maxPartySize}</Text><Text style={styles.line}>Recommended level {quest.recommendedLevelMin ?? region?.recommendedLevelMin}–{quest.recommendedLevelMax ?? region?.recommendedLevelMax}{quest.minimumPartyAverageLevel ? ` · minimum average ${quest.minimumPartyAverageLevel}` : ""}</Text><Text style={styles.line}>{quest.encounterIds.length} combat · {quest.explorationStageIds?.length ?? 0} checks · {quest.decisionStageIds?.length ?? 0} choices</Text><Text style={styles.line}>Enemy factions: {factions.join(", ")}</Text>{quest.preparationNotes?.map((note) => <Text key={note} style={styles.preparation}>◆ {note}</Text>)}</Panel>
    <SectionTitle>ENEMY COMBAT PROFILE</SectionTitle><Panel><Text style={styles.profile}>{combatProfile.summary}</Text><View style={styles.profileBar}><View style={[styles.physicalBar,{width:`${combatProfile.physicalThreat*100}%`}]}/><View style={[styles.magicBar,{width:`${combatProfile.magicThreat*100}%`}]}/></View><Text style={styles.physicalText}>PHYSICAL THREAT · {Math.round(combatProfile.physicalThreat*100)}%</Text><Text style={styles.magicText}>MAGIC THREAT · {Math.round(combatProfile.magicThreat*100)}%</Text><Text style={styles.recommendation}>Recommended offense: {combatProfile.recommendedDamage.toUpperCase()}</Text>{combatProfile.conditionIds.length>0&&<Text style={styles.line}>Likely conditions: {combatProfile.conditionIds.map((id)=>id.replace(/_/g," ")).join(", ")}</Text>}{quest.questType === "side" && !quest.hiddenFromQuestBoard ? <Text style={styles.sideQuestBonus}>SIDE QUEST PRESSURE · Enemies gain +1 attack roll and +5% damage.</Text> : null}<Text style={styles.optional}>This profile uses enemies already revealed by the quest briefing. Individual elite defenses may differ.</Text></Panel>
    <QuestSkillPreview quest={quest} heroes={fieldHeroes}/><SectionTitle>REWARDS</SectionTitle><Panel><Text style={styles.reward}>◆ {quest.goldRewardMin}–{quest.goldRewardMax} gold</Text><Text style={styles.reward}>★ {quest.xpRewardPerHero} XP per hero</Text><Text style={styles.line}>Loot table: {quest.lootTableId.replace(/_/g," ")}</Text></Panel><View style={styles.action}><ActionButton disabled={!canAssemble} label={!locationReady ? `Travel to ${requiredLocation}` : !enoughHeroes ? `Need ${quest.minPartySize} Available Heroes` : readiness === "DANGER" ? "Assemble Anyway · Danger" : "Assemble Party"} onPress={assemble}/></View>
  </ScrollView>;
}

const styles=StyleSheet.create({content:{padding:20,paddingBottom:45},title:{color:colors.text,fontSize:30,fontWeight:"900",marginTop:12},kind:{color:colors.gold,fontWeight:"800",marginTop:5},description:{color:colors.muted,lineHeight:22,marginVertical:18},line:{color:colors.text,marginVertical:5},contextLabel:{color:colors.gold,fontSize:10,fontWeight:"900",letterSpacing:1,marginTop:7,textTransform:"uppercase"},contextCopy:{color:colors.text,lineHeight:20,marginTop:4},locationReady:{borderColor:colors.green,gap:5},locationBlocked:{borderColor:colors.danger,gap:5},locationReadyText:{color:colors.green,fontSize:10,fontWeight:"900",letterSpacing:.8},locationBlockedText:{color:colors.danger,fontSize:10,fontWeight:"900",letterSpacing:.8},readinessPanel:{borderColor:colors.green},dangerPanel:{borderColor:colors.danger},readiness:{color:colors.green,fontSize:13,fontWeight:"900",letterSpacing:.8},danger:{color:colors.danger},covered:{color:colors.green,fontWeight:"800",marginVertical:4},uncovered:{color:colors.danger,fontWeight:"800",marginVertical:4},optional:{color:colors.muted,fontStyle:"italic",lineHeight:19,marginBottom:7,marginTop:8},preparation:{color:colors.text,lineHeight:20,marginVertical:4},reward:{color:colors.green,fontWeight:"800",fontSize:17,marginVertical:5},action:{marginTop:18},profile:{color:colors.text,fontWeight:"900",marginBottom:8},profileBar:{borderRadius:5,flexDirection:"row",height:9,overflow:"hidden"},physicalBar:{backgroundColor:"#e56f58"},magicBar:{backgroundColor:"#9d78e8"},physicalText:{color:"#ff9a78",fontSize:10,fontWeight:"900",marginTop:7},magicText:{color:"#c4a4ff",fontSize:10,fontWeight:"900",marginTop:4},recommendation:{color:colors.gold,fontWeight:"900",marginTop:8},sideQuestBonus:{color:"#f1b26c",fontSize:10,fontWeight:"900",lineHeight:15,marginTop:9}});
