import React, { useState } from "react";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, Panel, Portrait, SecondaryButton, colors } from "../components/ui";
import { CLASSES } from "../data/classes/classes";
import { RACES } from "../data/races/races";
import { RECRUITMENT_CONFIG } from "../data/recruitment/recruitmentBalance";
import { TRAITS } from "../data/traits/traits";
import { publicCandidateRating } from "../game/recruitment/candidateGenerator";
import type { RecruitmentCandidate } from "../game/recruitment/recruitmentTypes";
import { useGuild } from "../state/GuildContext";
import { getRaceNameColor } from "../ui/raceColors";
import { RegionalScoutPanel } from "./Recruitment/RegionalScoutPanel";

const range = (min: number, max: number) => min === max ? `${min}` : `${min}–${max}`;

export function RecruitmentScreen({ onBack, inspect, openCalendar }: { onBack(): void; inspect(candidate: RecruitmentCandidate): void; openCalendar(): void }) {
  const { candidates, guild, refreshCandidates, recruitCandidate, rejectCandidate } = useGuild();
  const [message, setMessage] = useState<string>(); const [compareIds, setCompareIds] = useState<string[]>([]);
  const freeReady = guild.currentDay >= guild.recruitment.nextFreeRefreshDay;
  const act = (action: () => string | null, success: string) => { const error = action(); setMessage(error ?? success); };
  const confirmRecruit = (candidate: RecruitmentCandidate) => Alert.alert(`Recruit ${candidate.heroPreview.name}?`, `Estimated fee: ${range(candidate.recruitmentFeeEstimateMin, candidate.recruitmentFeeEstimateMax)}\nEstimated salary demand: ${range(candidate.weeklySalaryEstimateMin, candidate.weeklySalaryEstimateMax)}/week\nContract: ${candidate.contractLengthWeeks} weeks\n\nFinal terms are resolved from the candidate's actual demands.`, [{ text: "Cancel", style: "cancel" }, { text: "Recruit", onPress: () => act(() => recruitCandidate(candidate.candidateId), `${candidate.heroPreview.name} joined the guild.`) }]);
  const toggleCompare = (id: string) => setCompareIds((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 3 ? [...current, id] : current);
  const compared = candidates.filter((item) => compareIds.includes(item.candidateId));
  return <ScrollView contentContainerStyle={styles.content}>
    <BackButton onPress={onBack} /><Text style={styles.title}>Recruitment</Text><Text style={styles.sub}>Roster {guild.heroes.length}/{RECRUITMENT_CONFIG.heroCapacity} • Gold {guild.gold.toLocaleString()}</Text>
    <Panel style={styles.refresh}><View><Text style={styles.name}>Candidate Search</Text><Text style={styles.meta}>Next free refresh: {freeReady ? "Ready" : `${guild.recruitment.nextFreeRefreshDay - guild.currentDay} days`}</Text><Text style={styles.meta}>Manual refresh: {guild.recruitment.manualRefreshCost} gold</Text></View><View style={styles.refreshButtons}><SecondaryButton label={freeReady ? "Free Refresh" : "Refresh"} disabled={!freeReady && guild.gold < guild.recruitment.manualRefreshCost} onPress={() => act(() => refreshCandidates(freeReady), "Candidate pool refreshed.")} /></View></Panel>
    <RegionalScoutPanel openCalendar={openCalendar} />
    {message && <Text style={styles.message}>{message}</Text>}
    {candidates.map((candidate) => { const hero = candidate.heroPreview; const reserved = guild.recruitment.reservedCandidateId === candidate.candidateId; return <Panel key={candidate.candidateId} style={styles.card}>
      <View style={styles.row}><Portrait hero={hero} size={72} /><View style={styles.flex}><Text style={[styles.name, { color: getRaceNameColor(hero.raceId) }]}>{hero.name}{reserved ? " • RESERVED" : ""}</Text><Text style={styles.meta}>{RACES[hero.raceId].name} {CLASSES[hero.classId].name} • Age {hero.age} • Lv {hero.level}</Text><Text style={styles.archetype}>{candidate.archetype.toUpperCase()} • {publicCandidateRating(candidate.rarityScore)}</Text>{candidate.source === "regional_scout" && <Text style={styles.scoutSource}>SCOUT REPORT · {candidate.sourceLocationName}</Text>}<Text style={styles.potential}>Potential estimate {candidate.potentialEstimateMin}–{candidate.potentialEstimateMax}</Text><Text style={styles.meta}>Traits: {hero.traitIds.map((id) => TRAITS[id].name).join(", ")}</Text><Text style={styles.cost}>Fee estimate: {range(candidate.recruitmentFeeEstimateMin, candidate.recruitmentFeeEstimateMax)} gold</Text><Text style={styles.cost}>Salary demand: {range(candidate.weeklySalaryEstimateMin, candidate.weeklySalaryEstimateMax)} gold/week</Text><Text style={styles.meta}>{candidate.contractLengthWeeks}-week contract • Scouting Lv {candidate.scoutingLevel}</Text><Text style={styles.meta}>Expires in {Math.max(0, candidate.expiresAtDay - guild.currentDay)} days</Text></View></View>
      <Pressable onPress={() => toggleCompare(candidate.candidateId)} style={styles.compare}><Text style={styles.compareText}>{compareIds.includes(candidate.candidateId) ? "✓ Selected for comparison" : "○ Compare"}</Text></Pressable>
      <View style={styles.actions}><View style={styles.flex}><SecondaryButton label="Inspect / Scout" onPress={() => inspect(candidate)} /></View><View style={styles.flex}><ActionButton label={guild.gold < candidate.recruitmentFeeEstimateMin ? "Insufficient Gold" : "Recruit"} disabled={guild.gold < candidate.recruitmentFeeEstimateMin || guild.heroes.length >= RECRUITMENT_CONFIG.heroCapacity} onPress={() => confirmRecruit(candidate)} /></View></View>
      <Pressable onPress={() => act(() => rejectCandidate(candidate.candidateId), `${hero.name} rejected.`)}><Text style={styles.reject}>Reject candidate</Text></Pressable>
    </Panel>; })}
    {compared.length >= 2 && <Panel><Text style={styles.name}>Candidate Comparison</Text><View style={styles.compareGrid}>{compared.map((candidate) => <View key={candidate.candidateId} style={styles.compareColumn}><Text numberOfLines={1} style={[styles.columnName, { color: getRaceNameColor(candidate.heroPreview.raceId) }]}>{candidate.heroPreview.name}</Text><Text style={styles.meta}>{candidate.heroPreview.raceId}</Text><Text style={styles.meta}>{candidate.heroPreview.classId}</Text><Text style={styles.meta}>Lv {candidate.heroPreview.level} • Age {candidate.heroPreview.age}</Text><Text style={styles.potential}>POT {candidate.potentialEstimateMin}–{candidate.potentialEstimateMax}</Text><Text style={styles.meta}>Fee {range(candidate.recruitmentFeeEstimateMin, candidate.recruitmentFeeEstimateMax)}</Text><Text style={styles.meta}>Demand {range(candidate.weeklySalaryEstimateMin, candidate.weeklySalaryEstimateMax)}/wk</Text>{Object.entries(candidate.heroPreview.baseAttributes).map(([key, value]) => <Text key={key} style={styles.meta}>{key.slice(0, 3).toUpperCase()} {value}</Text>)}</View>)}</View></Panel>}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 45 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 10 }, sub: { color: colors.gold, marginTop: 3, marginBottom: 12 }, refresh: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 }, refreshButtons: { minWidth: 110 }, message: { color: colors.green, marginBottom: 10 }, card: { marginBottom: 12 }, row: { flexDirection: "row", gap: 12 }, flex: { flex: 1 }, name: { color: colors.text, fontSize: 18, fontWeight: "900" }, meta: { color: colors.muted, fontSize: 12, marginTop: 3 }, archetype: { color: colors.gold, fontWeight: "900", fontSize: 11, marginTop: 4 }, scoutSource: { color: colors.blue, fontSize: 9, fontWeight: "900", letterSpacing: .6, marginTop: 4 }, potential: { color: colors.green, fontWeight: "800", marginTop: 5 }, cost: { color: colors.text, fontWeight: "800", marginTop: 5 }, actions: { flexDirection: "row", gap: 9, marginTop: 10 }, compare: { paddingVertical: 8 }, compareText: { color: colors.gold, fontWeight: "700" }, reject: { color: colors.danger, textAlign: "center", paddingTop: 12 }, compareGrid: { flexDirection: "row", gap: 7, marginTop: 10 }, compareColumn: { flex: 1, backgroundColor: colors.panel2, padding: 7, borderRadius: 8 }, columnName: { color: colors.text, fontWeight: "900", fontSize: 11 } });
