import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text } from "react-native";
import { BackButton, Panel, SectionTitle, colors } from "../../components/ui";
import { SkillInfoPanel } from "../../components/skills/SkillInfoPanel";
import { HERO_SKILLS } from "../../data/skills/heroSkills";
import { ADVANCED_CLASS_NAMES } from "../../data/masteries/masteries";
import type { Hero } from "../../game/heroes/types";
import { getMasteryChoices, selectMastery } from "../../game/progression/masteries/masteryService";
import { getSubclassChoices, selectSubclass } from "../../game/progression/subclasses/subclassService";
import { getModifierTargetLabel } from "../../ui/modifierLabels";
import { formatGameId } from "../../ui/textFormat";
export function SubclassSelectionScreen({ hero, onBack, onSelect }: { hero: Hero; onBack(): void; onSelect(hero: Hero): void }) {
  const [error,setError]=useState<string>(); const [selectedSkillId,setSelectedSkillId]=useState<string>(); const masteryMode=Boolean(hero.subclassId); const choices=masteryMode?getMasteryChoices(hero):getSubclassChoices(hero);
  const choose=(id:string)=>{try{onSelect(masteryMode?selectMastery(hero,id):selectSubclass(hero,id));}catch(caught){setError(caught instanceof Error?caught.message:"Selection failed");}};
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.title}>{masteryMode?"Choose a Mastery":"Choose a Subclass"}</Text><Text style={styles.warning}>This level-{masteryMode?10:5} choice is permanent for {hero.name}.</Text><SectionTitle>{masteryMode?"TWO MASTERIES":"TWO PATHS"}</SectionTitle>
    {choices.map((choice)=>{const locked=hero.level<choice.levelRequirement||(masteryMode?Boolean(hero.masteryId):Boolean(hero.subclassId));const advancedName=masteryMode&&hero.subclassId?ADVANCED_CLASS_NAMES[`${hero.subclassId}:${choice.id}`]:undefined;return <Panel key={choice.id} style={styles.card}><Text style={styles.name}>{choice.name}</Text>{advancedName&&<Text style={styles.advanced}>Advanced title · {advancedName}</Text>}<Text style={styles.description}>{choice.description}</Text><Text style={styles.label}>MODIFIERS</Text>{choice.modifiers.length?choice.modifiers.map((modifier,index)=><Text key={`${modifier.target}-${index}`} style={styles.line}>{getModifierTargetLabel(modifier.target)}: {modifier.value>0?"+":""}{modifier.operation==="percentage"?`${modifier.value*100}%`:modifier.value}</Text>):<Text style={styles.line}>Power is provided by its combat ability.</Text>}<Text style={styles.label}>ADDED SKILL · TAP FOR DETAILS</Text>{choice.addedSkillIds.map((id)=><React.Fragment key={id}><Pressable onPress={()=>setSelectedSkillId((value)=>value===id?undefined:id)}><Text style={styles.skillLink}>{HERO_SKILLS[id]?.name??formatGameId(id)} ›</Text></Pressable>{selectedSkillId===id&&HERO_SKILLS[id]&&<SkillInfoPanel skill={HERO_SKILLS[id]}/>}</React.Fragment>)}<Pressable disabled={locked} onPress={()=>choose(choice.id)} style={[styles.button,locked&&styles.disabled]}><Text style={styles.buttonText}>{masteryMode&&hero.masteryId?"Mastery already chosen":hero.level<choice.levelRequirement?`Unlocks at Level ${choice.levelRequirement}`:`Choose ${choice.name}`}</Text></Pressable></Panel>;})}{error&&<Text style={styles.error}>{error}</Text>}
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:20,paddingBottom:50},title:{color:colors.text,fontSize:29,fontWeight:"900",marginTop:10},warning:{color:colors.gold,marginTop:5},card:{marginTop:12},name:{color:colors.text,fontSize:21,fontWeight:"900"},advanced:{color:colors.gold,fontWeight:"800",marginTop:3},description:{color:colors.muted,lineHeight:20,marginVertical:8},label:{color:colors.gold,fontSize:10,fontWeight:"900",marginTop:8},line:{color:colors.text,marginTop:3},skillLink:{color:colors.gold,marginTop:7,fontWeight:"800",paddingVertical:4},button:{backgroundColor:colors.gold,padding:11,borderRadius:9,marginTop:12,alignItems:"center"},buttonText:{color:"#17130c",fontWeight:"900"},disabled:{opacity:.4},error:{color:colors.danger,marginTop:10}});
