import { CONTRACT_LENGTH_WEIGHTS, RECRUITMENT_ARCHETYPES, RECRUITMENT_CLASS_WEIGHTS, RECRUITMENT_CONFIG, RECRUITMENT_RACE_WEIGHTS } from "../../data/recruitment/recruitmentBalance";
import type { ClassId, RaceId, TraitId } from "../heroes/types";
import { generateHero } from "../heroes/heroGenerator";
import type { RandomSource } from "../../utils/random";
import { calculateRecruitmentFee, calculateWeeklySalary } from "./recruitmentCostCalculator";
import { attributeEstimates, financialEstimate } from "./scoutingService";
import type { ContractLengthWeeks, RecruitmentArchetype, RecruitmentCandidate } from "./recruitmentTypes";
export type RecruitmentLevelRanges = Partial<Record<RecruitmentArchetype,{min:number;max:number}>>;
import { TRAITS } from "../../data/traits/traits";
import { getBackgroundModifier } from "../../data/backgrounds/backgrounds";
import { generateWeightedTraits } from "../traits/traitGenerationService";

function weightedPick<T extends string | number>(random: RandomSource, weights: Record<T, number>): T { const entries = Object.entries(weights) as [T, number][]; const total = entries.reduce((sum, [, weight]) => sum + weight, 0); let roll = random.next() * total; for (const [id, weight] of entries) { roll -= weight; if (roll < 0) return id; } return entries[entries.length - 1]![0]; }
export function getArchetypeWeights(reputation: number): Record<RecruitmentArchetype, number> { const elite = Math.min(.10, .05 + Math.floor(Math.max(0, reputation) / 20) * .01); const remainingScale = (1 - elite) / .95; return { prospect: .35 * remainingScale, standard: .40 * remainingScale, veteran: .20 * remainingScale, elite }; }
function rarityScore(candidate: { level: number; traits: TraitId[]; attributes: Record<string, number> }): number { const levelNormalized = Math.min(100, candidate.level / 12 * 100); const positive = candidate.traits.filter((id) => TRAITS[id].polarity === "positive").length; const negative = candidate.traits.filter((id) => TRAITS[id].polarity === "negative").length; const traitQuality = Math.max(0, Math.min(100, 50 + positive * 20 - negative * 15)); const attributeQuality = Object.values(candidate.attributes).reduce((sum, value) => sum + value, 0) / 120 * 100; return Math.round(Math.max(0, Math.min(100, levelNormalized * .20 + traitQuality * .35 + attributeQuality * .45))); }
export function generateRecruitmentCandidate(random: RandomSource, currentDay: number, reputation = 0, forcedArchetype?: RecruitmentArchetype, forcedRaceId?: RaceId, forcedClassId?: ClassId, allowedRaceIds?: RaceId[], allowedClassIds?: ClassId[], levelRanges?: RecruitmentLevelRanges): RecruitmentCandidate {
  const raceWeights = Object.fromEntries(Object.entries(RECRUITMENT_RACE_WEIGHTS).filter(([id]) => !allowedRaceIds || allowedRaceIds.includes(id as RaceId))) as Record<RaceId, number>;
  const classWeights = Object.fromEntries(Object.entries(RECRUITMENT_CLASS_WEIGHTS).filter(([id]) => !allowedClassIds || allowedClassIds.includes(id as ClassId))) as Record<ClassId, number>;
  const archetype = forcedArchetype ?? weightedPick(random, getArchetypeWeights(reputation)); const balance = RECRUITMENT_ARCHETYPES[archetype]; const raceId = forcedRaceId ?? weightedPick(random, raceWeights) as RaceId; const classId = forcedClassId ?? weightedPick(random, classWeights) as ClassId;
  const traitCount = random.int(balance.traitCountMin, balance.traitCountMax); const levelRange=levelRanges?.[archetype]??{min:1,max:1}; const level=random.int(Math.max(1,levelRange.min),Math.max(levelRange.min,levelRange.max));
  let hero = generateHero(random, { raceId, classId, age: random.int(balance.ageMin, balance.ageMax), level, traitCount: 0 }); hero = { ...hero, traitIds: generateWeightedTraits(random, traitCount) };
  const recruitmentFee = calculateRecruitmentFee(hero.level, balance.recruitmentFeeModifier, 0, getBackgroundModifier(hero.backgroundId, "recruitmentFee")); const weeklySalary = calculateWeeklySalary(hero, balance.salaryModifier); const contractLengthWeeks = Number(weightedPick(random, CONTRACT_LENGTH_WEIGHTS)) as ContractLengthWeeks; const candidateId = `candidate-${hero.id}`;
  const financialRadius = balance.estimateRadius / 100 + .05; const feeEstimate = financialEstimate(recruitmentFee, financialRadius); const salaryEstimate = financialEstimate(weeklySalary, financialRadius);
  hero = { ...hero, recruitmentCost: recruitmentFee, salary: weeklySalary };
  return { candidateId, heroPreview: hero, archetype, recruitmentFee, weeklySalary, recruitmentFeeEstimateMin: feeEstimate.minimum, recruitmentFeeEstimateMax: feeEstimate.maximum, weeklySalaryEstimateMin: salaryEstimate.minimum, weeklySalaryEstimateMax: salaryEstimate.maximum, contractLengthWeeks, attributeEstimates: attributeEstimates(hero.baseAttributes, 0), scoutingLevel: 0, generatedAtDay: currentDay, expiresAtDay: currentDay + RECRUITMENT_CONFIG.expirationDays, rarityScore: rarityScore({ level: hero.level, traits: hero.traitIds, attributes: hero.baseAttributes }), source: "guild_board", sourceRaceId: null, sourceRegionId: null, sourceLocationName: null };
}
export function generateRecruitmentPool(random: RandomSource, currentDay: number, reputation = 0, count: number = RECRUITMENT_CONFIG.candidateCount, allowedRaceIds?: RaceId[], allowedClassIds?: ClassId[], levelRanges?: RecruitmentLevelRanges): RecruitmentCandidate[] { const generate = () => generateRecruitmentCandidate(random, currentDay, reputation, undefined, undefined, undefined, allowedRaceIds, allowedClassIds, levelRanges); const candidates = Array.from({ length: count }, generate); if (candidates.length >= 3) { for (let attempt = 0; attempt < 5; attempt++) { const allClass = candidates.every((item) => item.heroPreview.classId === candidates[0]!.heroPreview.classId); const allRace = candidates.every((item) => item.heroPreview.raceId === candidates[0]!.heroPreview.raceId); const allType = candidates.every((item) => item.archetype === candidates[0]!.archetype); if (!allClass && !allRace && !allType) break; candidates[2] = generate(); } } return candidates; }
export function publicCandidateRating(score: number): "Common" | "Notable" | "Rare" | "Exceptional" { return score < 50 ? "Common" : score < 70 ? "Notable" : score < 85 ? "Rare" : "Exceptional"; }
