import { GAME_CONFIG } from "../../config/gameConfig";
import { CONTRACT_LENGTH_WEIGHTS, RECRUITMENT_ARCHETYPES, RECRUITMENT_CLASS_WEIGHTS, RECRUITMENT_CONFIG, RECRUITMENT_RACE_WEIGHTS } from "../../data/recruitment/recruitmentBalance";
import type { ClassId, RaceId, TraitId } from "../heroes/types";
import { generateHero } from "../heroes/heroGenerator";
import { generateWeightedPotential } from "../progression/potentialGenerator";
import type { RandomSource } from "../../utils/random";
import { calculateRecruitmentFee, calculateWeeklySalary } from "./recruitmentCostCalculator";
import { financialEstimate, potentialEstimate } from "./scoutingService";
import type { ContractLengthWeeks, RecruitmentArchetype, RecruitmentCandidate } from "./recruitmentTypes";
import { TRAITS } from "../../data/traits/traits";
import { getBackgroundModifier } from "../../data/backgrounds/backgrounds";

function weightedPick<T extends string | number>(random: RandomSource, weights: Record<T, number>): T { const entries = Object.entries(weights) as [T, number][]; const total = entries.reduce((sum, [, weight]) => sum + weight, 0); let roll = random.next() * total; for (const [id, weight] of entries) { roll -= weight; if (roll < 0) return id; } return entries[entries.length - 1]![0]; }
export function getArchetypeWeights(reputation: number): Record<RecruitmentArchetype, number> { const elite = Math.min(.10, .05 + Math.floor(Math.max(0, reputation) / 20) * .01); const remainingScale = (1 - elite) / .95; return { prospect: .35 * remainingScale, standard: .40 * remainingScale, veteran: .20 * remainingScale, elite }; }
export function reputationPotentialBonus(reputation: number): number { return Math.min(10, Math.floor(Math.max(0, reputation) / 10)); }
function pickWeightedTrait(random: RandomSource, ids: TraitId[]): TraitId { const total = ids.reduce((sum, id) => sum + TRAITS[id].generationWeight, 0); let roll = random.next() * total; for (const id of ids) { roll -= TRAITS[id].generationWeight; if (roll < 0) return id; } return ids[ids.length - 1]!; }
function weightedTraits(random: RandomSource, count: number): TraitId[] { const definitions = Object.values(TRAITS); const selected = new Set<TraitId>(); let attempts = 0; while (selected.size < Math.min(count, definitions.length) && attempts++ < 60) { const roll = random.next(); const polarity = roll < .55 ? "positive" : roll < .85 ? "mixed" : "negative"; const pool = definitions.filter((trait) => trait.polarity === polarity).map((trait) => trait.id); selected.add(pickWeightedTrait(random, pool)); } return [...selected]; }
function rarityScore(candidate: { potential: number; level: number; traits: TraitId[]; attributes: Record<string, number> }): number { const levelNormalized = Math.min(100, candidate.level / 12 * 100); const positive = candidate.traits.filter((id) => TRAITS[id].polarity === "positive").length; const negative = candidate.traits.filter((id) => TRAITS[id].polarity === "negative").length; const traitQuality = Math.max(0, Math.min(100, 50 + positive * 20 - negative * 15)); const attributeQuality = Object.values(candidate.attributes).reduce((sum, value) => sum + value, 0) / 120 * 100; return Math.round(Math.max(0, Math.min(100, candidate.potential * .40 + levelNormalized * .20 + traitQuality * .25 + attributeQuality * .15))); }
export function generateRecruitmentCandidate(random: RandomSource, currentDay: number, reputation = 0, forcedArchetype?: RecruitmentArchetype, forcedRaceId?: RaceId, forcedClassId?: ClassId): RecruitmentCandidate {
  const archetype = forcedArchetype ?? weightedPick(random, getArchetypeWeights(reputation)); const balance = RECRUITMENT_ARCHETYPES[archetype]; const raceId = forcedRaceId ?? weightedPick(random, RECRUITMENT_RACE_WEIGHTS) as RaceId; const classId = forcedClassId ?? weightedPick(random, RECRUITMENT_CLASS_WEIGHTS) as ClassId;
  const basePotential = generateWeightedPotential(random, Math.max(GAME_CONFIG.potentialMin, balance.potentialMin), balance.potentialMax); const truePotential = Math.min(GAME_CONFIG.potentialMax, basePotential + reputationPotentialBonus(reputation)); const traitCount = random.int(balance.traitCountMin, balance.traitCountMax);
  let hero = generateHero(random, { raceId, classId, age: random.int(balance.ageMin, balance.ageMax), level: random.int(balance.levelMin, balance.levelMax), potential: truePotential, traitCount: 0 }); hero = { ...hero, traitIds: weightedTraits(random, traitCount) };
  const recruitmentFee = calculateRecruitmentFee(hero.level, truePotential, balance.recruitmentFeeModifier, 0, getBackgroundModifier(hero.backgroundId, "recruitmentFee")); const weeklySalary = calculateWeeklySalary(hero, balance.salaryModifier); const contractLengthWeeks = Number(weightedPick(random, CONTRACT_LENGTH_WEIGHTS)) as ContractLengthWeeks; const estimate = potentialEstimate(truePotential, balance.estimateRadius); const candidateId = `candidate-${hero.id}`;
  const financialRadius = balance.estimateRadius / 100 + .05; const feeEstimate = financialEstimate(recruitmentFee, financialRadius); const salaryEstimate = financialEstimate(weeklySalary, financialRadius);
  hero = { ...hero, recruitmentCost: recruitmentFee, salary: weeklySalary, potentialEstimateMin: estimate.minimum, potentialEstimateMax: estimate.maximum };
  return { candidateId, heroPreview: hero, truePotential, archetype, recruitmentFee, weeklySalary, recruitmentFeeEstimateMin: feeEstimate.minimum, recruitmentFeeEstimateMax: feeEstimate.maximum, weeklySalaryEstimateMin: salaryEstimate.minimum, weeklySalaryEstimateMax: salaryEstimate.maximum, contractLengthWeeks, potentialEstimateMin: estimate.minimum, potentialEstimateMax: estimate.maximum, scoutingLevel: 0, generatedAtDay: currentDay, expiresAtDay: currentDay + RECRUITMENT_CONFIG.expirationDays, rarityScore: rarityScore({ potential: truePotential, level: hero.level, traits: hero.traitIds, attributes: hero.baseAttributes }), source: "guild_board", sourceRaceId: null, sourceRegionId: null, sourceLocationName: null };
}
export function generateRecruitmentPool(random: RandomSource, currentDay: number, reputation = 0, count = RECRUITMENT_CONFIG.candidateCount): RecruitmentCandidate[] { const candidates = Array.from({ length: count }, () => generateRecruitmentCandidate(random, currentDay, reputation)); if (candidates.length >= 3) { for (let attempt = 0; attempt < 5; attempt++) { const allClass = candidates.every((item) => item.heroPreview.classId === candidates[0]!.heroPreview.classId); const allRace = candidates.every((item) => item.heroPreview.raceId === candidates[0]!.heroPreview.raceId); const allType = candidates.every((item) => item.archetype === candidates[0]!.archetype); if (!allClass && !allRace && !allType) break; candidates[2] = generateRecruitmentCandidate(random, currentDay, reputation); } } return candidates; }
export function publicCandidateRating(score: number): "Common" | "Notable" | "Rare" | "Exceptional" { return score < 50 ? "Common" : score < 70 ? "Notable" : score < 85 ? "Rare" : "Exceptional"; }
