import { RECRUITMENT_CONFIG } from "../../data/recruitment/recruitmentBalance";
import type { GuildState } from "../guild/types";
import type { RandomSource } from "../../utils/random";
import { generateRecruitmentPool } from "./candidateGenerator";
import { createHeroContract } from "./contractService";
import { scoutCandidate, scoutingCost } from "./scoutingService";
import type { RecruitmentCandidate, RecruitmentState, ScoutingLevel } from "./recruitmentTypes";
import { validateCandidateRecruitment } from "./recruitmentValidator";

function withCandidates(state: RecruitmentState, candidates: RecruitmentCandidate[]): RecruitmentState { return { ...state, candidates, candidateIds: candidates.map((candidate) => candidate.candidateId) }; }
export function createRecruitmentState(currentDay: number, candidates: RecruitmentCandidate[] = []): RecruitmentState { return { candidateIds: candidates.map((candidate) => candidate.candidateId), candidates, reservedCandidateId: null, reservationExpiresAtDay: null, lastFreeRefreshDay: currentDay, nextFreeRefreshDay: currentDay + RECRUITMENT_CONFIG.freeRefreshDays, manualRefreshCost: RECRUITMENT_CONFIG.manualRefreshCost, regionalScoutMission: null }; }
export function initializeRecruitment(guild: GuildState, random: RandomSource): GuildState { const purged = purgeExpiredCandidates(guild); if (purged.recruitment.candidates.length) return purged; const candidates = generateRecruitmentPool(random, guild.currentDay, guild.reputation); return { ...purged, recruitment: createRecruitmentState(guild.currentDay, candidates) }; }
export function purgeExpiredCandidates(guild: GuildState): GuildState { const reservationActive = guild.recruitment.reservedCandidateId && (guild.recruitment.reservationExpiresAtDay ?? 0) > guild.currentDay; const candidates = guild.recruitment.candidates.filter((candidate) => candidate.expiresAtDay > guild.currentDay); const reservedStillExists = reservationActive && candidates.some((candidate) => candidate.candidateId === guild.recruitment.reservedCandidateId); return { ...guild, recruitment: { ...withCandidates(guild.recruitment, candidates), reservedCandidateId: reservedStillExists ? guild.recruitment.reservedCandidateId : null, reservationExpiresAtDay: reservedStillExists ? guild.recruitment.reservationExpiresAtDay : null } }; }
export function manualRefreshRecruitment(guild: GuildState, random: RandomSource): GuildState { if (guild.gold < guild.recruitment.manualRefreshCost) throw new Error("Insufficient Gold"); const reserved = guild.recruitment.candidates.filter((candidate) => candidate.candidateId === guild.recruitment.reservedCandidateId && (guild.recruitment.reservationExpiresAtDay ?? 0) > guild.currentDay); const generated = generateRecruitmentPool(random, guild.currentDay, guild.reputation); return { ...guild, gold: guild.gold - guild.recruitment.manualRefreshCost, recruitment: withCandidates(guild.recruitment, [...reserved, ...generated]) }; }
export function freeRefreshRecruitment(guild: GuildState, random: RandomSource): GuildState { if (guild.currentDay < guild.recruitment.nextFreeRefreshDay) throw new Error("Free refresh is not ready"); const refreshed = manualRefreshRecruitment({ ...guild, gold: guild.gold + guild.recruitment.manualRefreshCost }, random); return { ...refreshed, recruitment: { ...refreshed.recruitment, lastFreeRefreshDay: guild.currentDay, nextFreeRefreshDay: guild.currentDay + RECRUITMENT_CONFIG.freeRefreshDays } }; }
export function reserveCandidate(guild: GuildState, candidateId: string): GuildState { if (guild.recruitment.reservedCandidateId && (guild.recruitment.reservationExpiresAtDay ?? 0) > guild.currentDay) throw new Error("Only one candidate may be reserved"); if (!guild.recruitment.candidateIds.includes(candidateId)) throw new Error("Candidate is no longer available"); if (guild.gold < RECRUITMENT_CONFIG.reservationCost) throw new Error("Insufficient Gold"); return { ...guild, gold: guild.gold - RECRUITMENT_CONFIG.reservationCost, recruitment: { ...guild.recruitment, reservedCandidateId: candidateId, reservationExpiresAtDay: guild.currentDay + RECRUITMENT_CONFIG.reservationDays } }; }
export function scoutRecruitmentCandidate(guild: GuildState, candidateId: string): GuildState { const candidate = guild.recruitment.candidates.find((item) => item.candidateId === candidateId); if (!candidate) throw new Error("Candidate is no longer available"); const nextLevel = (candidate.scoutingLevel + 1) as ScoutingLevel; const cost = scoutingCost(nextLevel); if (guild.gold < cost) throw new Error("Insufficient Gold"); const updated = scoutCandidate(candidate); return { ...guild, gold: guild.gold - cost, recruitment: withCandidates(guild.recruitment, guild.recruitment.candidates.map((item) => item.candidateId === candidateId ? updated : item)) }; }
export function recruitCandidate(guild: GuildState, candidateId: string): GuildState { const candidate = guild.recruitment.candidates.find((item) => item.candidateId === candidateId); if (!candidate) throw new Error("Candidate is no longer available"); const errors = validateCandidateRecruitment(guild, candidate); if (errors.length) throw new Error(errors.join(". ")); const hero = { ...candidate.heroPreview, potential: candidate.truePotential, recruitmentCost: candidate.recruitmentFee, salary: candidate.weeklySalary, isAvailable: true, history: { ...candidate.heroPreview.history, importantEvents: [...candidate.heroPreview.history.importantEvents, `Joined the guild on Day ${guild.currentDay}.`] } }; const candidates = guild.recruitment.candidates.filter((item) => item.candidateId !== candidateId); return { ...guild, gold: guild.gold - candidate.recruitmentFee, heroes: [...guild.heroes, hero], heroContracts: [...guild.heroContracts, createHeroContract(hero, candidate.weeklySalary, candidate.contractLengthWeeks, guild.currentDay)], recruitment: { ...withCandidates(guild.recruitment, candidates), reservedCandidateId: guild.recruitment.reservedCandidateId === candidateId ? null : guild.recruitment.reservedCandidateId, reservationExpiresAtDay: guild.recruitment.reservedCandidateId === candidateId ? null : guild.recruitment.reservationExpiresAtDay } }; }
export function rejectCandidate(guild: GuildState, candidateId: string, random: RandomSource): GuildState { let candidates = guild.recruitment.candidates.filter((item) => item.candidateId !== candidateId); if (!candidates.length) candidates = generateRecruitmentPool(random, guild.currentDay, guild.reputation); return { ...guild, recruitment: withCandidates(guild.recruitment, candidates) }; }
