import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, Panel, colors } from "../../components/ui";
import { DIFFICULTIES } from "../../data/difficulty/difficulties";
import type { GameDifficultyId } from "../../game/difficulty/difficultyTypes";

const IDS: GameDifficultyId[] = ["standard", "veteran", "iron_guild"];
const AI_LABELS = { trained: "TRAINED", tactical: "TACTICAL", ruthless: "RUTHLESS" } as const;

export function NewGameSetupScreen({ onBack, onStart }: { onBack(): void; onStart(difficultyId: GameDifficultyId): void }) {
  const [selectedId, setSelectedId] = useState<GameDifficultyId>("standard"); const selected = DIFFICULTIES[selectedId];
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.eyebrow}>NEW GUILD CHARTER</Text><Text style={styles.title}>Choose Your Challenge</Text><Text style={styles.intro}>Difficulty is bound to this save. It controls enemy strength and decision-making as well as the pressure on your guild treasury.</Text>
    <View style={styles.cards}>{IDS.map((id) => { const entry = DIFFICULTIES[id]; const active = id === selectedId; return <Pressable key={id} accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={() => setSelectedId(id)}><Panel style={[styles.card, active && styles.selected, id === "iron_guild" && styles.iron]}><View style={styles.cardHead}><View style={styles.flex}><Text style={styles.name}>{entry.name}</Text><Text style={styles.tagline}>{entry.tagline}</Text></View><View style={[styles.mark, active && styles.markSelected]}><Text style={styles.markText}>{active ? "✓" : ""}</Text></View></View><Text style={styles.description}>{entry.description}</Text><View style={styles.metrics}><Metric label="ENEMY AI" value={AI_LABELS[entry.enemyAiLevel]} /><Metric label="ENEMY HP" value={`${Math.round(entry.enemyHpMultiplier * 100)}%`} /><Metric label="ENEMY DAMAGE" value={`${Math.round(entry.enemyDamageMultiplier * 100)}%`} /><Metric label="QUEST GOLD" value={`${Math.round(entry.questGoldMultiplier * 100)}%`} /></View>{!entry.allowsPaidRecruitmentRefresh && <Text style={styles.restriction}>IRON RULE · No gold-paid tavern recruitment refreshes. Scheduled free and tutorial refreshes remain available.</Text>}</Panel></Pressable>; })}</View>
    <Panel style={styles.summary}><Text style={styles.summaryLabel}>SELECTED CHARTER</Text><Text style={styles.summaryName}>{selected.name}</Text><Text style={styles.summaryText}>AI: {AI_LABELS[selected.enemyAiLevel]} · Attack rolls +{selected.enemyAttackRollModifier} · Defense scores +{selected.enemyDefenseScoreModifier} · Tavern income {Math.round(selected.tavernIncomeMultiplier * 100)}%</Text></Panel><ActionButton label={`Found Guild · ${selected.name}`} onPress={() => onStart(selectedId)} />
  </ScrollView>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { alignSelf: "center", maxWidth: 620, padding: 20, paddingBottom: 45, width: "100%" }, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 2, marginTop: 12 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 5 }, intro: { color: colors.muted, lineHeight: 20, marginBottom: 18, marginTop: 8 }, cards: { gap: 11 }, card: { borderWidth: 1, gap: 9 }, selected: { backgroundColor: "#29281f", borderColor: colors.gold, borderWidth: 2 }, iron: { borderColor: "#72504c" }, cardHead: { alignItems: "center", flexDirection: "row", gap: 10 }, flex: { flex: 1 }, name: { color: colors.text, fontSize: 21, fontWeight: "900" }, tagline: { color: colors.gold, fontSize: 11, fontWeight: "800", marginTop: 2 }, mark: { alignItems: "center", borderColor: colors.border, borderRadius: 13, borderWidth: 2, height: 26, justifyContent: "center", width: 26 }, markSelected: { backgroundColor: colors.gold, borderColor: colors.gold }, markText: { color: "#17130c", fontWeight: "900" }, description: { color: colors.muted, fontSize: 12, lineHeight: 18 }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 6 }, metric: { backgroundColor: colors.panel2, borderRadius: 7, padding: 7, width: "48%" }, metricLabel: { color: colors.muted, fontSize: 8, fontWeight: "900", letterSpacing: .7 }, metricValue: { color: colors.text, fontSize: 13, fontWeight: "900", marginTop: 2 }, restriction: { color: colors.danger, fontSize: 10, fontWeight: "800", lineHeight: 15 }, summary: { borderColor: colors.gold, marginBottom: 12, marginTop: 16 }, summaryLabel: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.4 }, summaryName: { color: colors.text, fontSize: 18, fontWeight: "900", marginTop: 3 }, summaryText: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 4 } });
