import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ActionButton, BackButton, Panel, colors } from "../../components/ui";
import { DIFFICULTIES } from "../../data/difficulty/difficulties";
import type { GameDifficultyId } from "../../game/difficulty/difficultyTypes";

const IDS: GameDifficultyId[] = ["standard", "veteran", "iron_guild"];
const EXPERIENCE_GUIDE: Record<GameDifficultyId, { bestFor: string; experience: string }> = {
  standard: { bestFor: "New players · Story-focused play", experience: "Forgiving battles · Comfortable economy" },
  veteran: { bestFor: "Experienced D20 and strategy players", experience: "Smarter foes · Tighter resources" },
  iron_guild: { bestFor: "Veterans seeking the full challenge", experience: "Ruthless foes · Harsh consequences" },
};

export function NewGameSetupScreen({ onBack, onStart }: { onBack(): void; onStart(difficultyId: GameDifficultyId): void }) {
  const [selectedId, setSelectedId] = useState<GameDifficultyId>("standard"); const selected = DIFFICULTIES[selectedId];
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.eyebrow}>NEW GUILD CHARTER</Text><Text style={styles.title}>Choose Your Challenge</Text><Text style={styles.intro}>Choose the experience that sounds most enjoyable. Difficulty is tied to this save and cannot be changed later.</Text>
    <View style={styles.cards}>{IDS.map((id) => { const entry = DIFFICULTIES[id]; const guide = EXPERIENCE_GUIDE[id]; const active = id === selectedId; return <Pressable key={id} accessibilityRole="radio" accessibilityState={{ checked: active }} onPress={() => setSelectedId(id)}><Panel style={[styles.card, active && styles.selected, id === "iron_guild" && styles.iron]}><View style={styles.cardHead}><View style={styles.flex}><Text style={styles.name}>{entry.name}</Text><Text style={styles.tagline}>{entry.tagline}</Text></View><View style={[styles.mark, active && styles.markSelected]}><Text style={styles.markText}>{active ? "✓" : ""}</Text></View></View><Text style={styles.description}>{entry.description}</Text><View style={styles.guide}><Text style={styles.guideLabel}>BEST FOR</Text><Text style={styles.guideValue}>{guide.bestFor}</Text><Text style={styles.guideLabel}>WHAT TO EXPECT</Text><Text style={styles.guideValue}>{guide.experience}</Text></View>{!entry.allowsPaidRecruitmentRefresh && <Text style={styles.restriction}>IRON RULE · Tavern candidates cannot be refreshed with gold. Scheduled free and tutorial refreshes remain available.</Text>}</Panel></Pressable>; })}</View>
    <Panel style={styles.summary}><Text style={styles.summaryLabel}>SELECTED CHARTER</Text><Text style={styles.summaryName}>{selected.name}</Text><Text style={styles.summaryText}>{EXPERIENCE_GUIDE[selectedId].bestFor}</Text></Panel><ActionButton label={`Found Guild · ${selected.name}`} onPress={() => onStart(selectedId)} />
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { alignSelf: "center", maxWidth: 620, padding: 20, paddingBottom: 45, width: "100%" }, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 2, marginTop: 12 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 5 }, intro: { color: colors.muted, lineHeight: 20, marginBottom: 18, marginTop: 8 }, cards: { gap: 11 }, card: { borderWidth: 1, gap: 9 }, selected: { backgroundColor: "#29281f", borderColor: colors.gold, borderWidth: 2 }, iron: { borderColor: "#72504c" }, cardHead: { alignItems: "center", flexDirection: "row", gap: 10 }, flex: { flex: 1 }, name: { color: colors.text, fontSize: 21, fontWeight: "900" }, tagline: { color: colors.gold, fontSize: 11, fontWeight: "800", marginTop: 2 }, mark: { alignItems: "center", borderColor: colors.border, borderRadius: 13, borderWidth: 2, height: 26, justifyContent: "center", width: 26 }, markSelected: { backgroundColor: colors.gold, borderColor: colors.gold }, markText: { color: "#17130c", fontWeight: "900" }, description: { color: colors.muted, fontSize: 12, lineHeight: 18 }, guide: { backgroundColor: colors.panel2, borderRadius: 7, gap: 2, padding: 9 }, guideLabel: { color: colors.gold, fontSize: 8, fontWeight: "900", letterSpacing: .8, marginTop: 3 }, guideValue: { color: colors.text, fontSize: 11, fontWeight: "700", lineHeight: 16 }, restriction: { color: colors.danger, fontSize: 10, fontWeight: "800", lineHeight: 15 }, summary: { borderColor: colors.gold, marginBottom: 12, marginTop: 16 }, summaryLabel: { color: colors.gold, fontSize: 9, fontWeight: "900", letterSpacing: 1.4 }, summaryName: { color: colors.text, fontSize: 18, fontWeight: "900", marginTop: 3 }, summaryText: { color: colors.muted, fontSize: 11, lineHeight: 17, marginTop: 4 } });
