import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useGameDialog } from "../../components/dialogs/GameDialog";
import { ActionButton, BackButton, Panel, SecondaryButton, SegmentedTabs, colors } from "../../components/ui";
import { MaterialCostList } from "../../components/materials/MaterialIcon";
import { EquipmentIcon } from "../../components/equipment/EquipmentIcon";
import { ARTISAN_BUILDINGS, ARTISANS } from "../../data/crafting/artisans";
import { ENCHANTMENTS } from "../../data/crafting/enchantments";
import { CRAFTING_RECIPES } from "../../data/crafting/recipes";
import { EQUIPMENT } from "../../data/equipment/equipment";
import { GUILDMASTER_SKILLS } from "../../data/guildmaster/guildmasterSkills";
import { getNextArtisanBuildingTier, startArtisanConstruction } from "../../game/crafting/artisanBuildingService";
import { craftEquipment, enchantInventoryEquipment, materialRequirementsMet } from "../../game/crafting/craftingService";
import type { ArtisanType } from "../../game/crafting/craftingTypes";
import { resolveEquipmentDefinition } from "../../game/equipment/equipmentResolver";
import { hasGuildmasterSkill } from "../../game/guildmaster/guildmasterProgression";
import { useGuild } from "../../state/GuildContext";
import { GameIcon } from "../../components/icons/GameIcon";
import { describeEquipmentSpecialEffect } from "../../game/equipment/equipmentSpecialEffectService";
import { getDurabilityLabel, getRepairCost, repairHeroEquipment, repairInventoryEquipment } from "../../game/equipment/equipmentDurabilityService";
import { getEquipmentRarityColor } from "../../ui/equipmentRarity";
const TABS: ArtisanType[] = ["blacksmith", "tailor", "jeweler"];

export function CraftingScreen({ onBack, openCalendar }: { onBack(): void; openCalendar(): void }) {
  const { showDialog } = useGameDialog();
  const { guild, updateGuild } = useGuild();
  const [tab, setTab] = useState<ArtisanType>("blacksmith");
  const artisan = ARTISANS[tab]; const state = guild.artisans[tab]; const nextTier = getNextArtisanBuildingTier(guild, tab);
  const act = (action: () => typeof guild, message: string) => { try { updateGuild(action()); showDialog({ title: "Workshop order complete", message, tone: "success" }); } catch (error) { showDialog({ title: "Cannot complete", message: error instanceof Error ? error.message : "Workshop action failed", tone: "danger" }); } };
  const artisanRecipes = Object.values(CRAFTING_RECIPES).filter((recipe) => recipe.artisanType === tab);
  const recipes = artisanRecipes.filter((recipe) => !recipe.unlockSource || (guild.unlockedRecipeIds ?? []).includes(recipe.id));
  const lockedRecipeCount = artisanRecipes.length - recipes.length;
  const tierName = state.level > 0 ? ARTISAN_BUILDINGS[tab][state.level - 1]?.name : "Not constructed";
  const requiredSkill = nextTier ? GUILDMASTER_SKILLS[nextTier.requiredSkillId] : null;
  const skillMet = nextTier ? hasGuildmasterSkill(guild.guildmaster, nextTier.requiredSkillId) : false;
  const construction = state.construction;
  const anyConstruction = Object.values(guild.artisans).some((entry) => entry.construction);
  const damagedInventory = guild.inventory.map((key, index) => ({ key, index, item: resolveEquipmentDefinition(key) })).filter((entry) => entry.item && entry.item.durability < 100);
  const damagedEquipped = guild.heroes.flatMap((hero) => Object.entries(hero.equipment).flatMap(([slot, key]) => { const item = key ? resolveEquipmentDefinition(key) : undefined; return item && item.durability < 100 ? [{ hero, slot: slot as keyof typeof hero.equipment, key, item }] : []; }));
  return <ScrollView contentContainerStyle={styles.content}>
    <BackButton onPress={onBack} />
    <View style={styles.header}><View style={styles.flex}><Text style={styles.title}>Artisan District</Text><Text style={styles.day}>Guild Day {guild.currentDay}</Text></View>{anyConstruction && <SecondaryButton label="Open Calendar" onPress={openCalendar} />}</View>
    <Text style={styles.intro}>A Guildmaster charter only grants permission. Every workshop must still be funded with gold and takes several in-game days to construct or upgrade.</Text>
    <SegmentedTabs values={TABS} value={tab} onChange={setTab}/>
    <Panel style={[styles.artisan, !state.recruited && styles.lockedWorkshop]}>
      <View style={styles.buildingHead}><GameIcon id={tab === "blacksmith" ? "blacksmith" : tab === "tailor" ? "tailor" : "jeweler"} size={48} /><View style={styles.flex}><Text style={styles.artisanName}>{artisan.name}</Text><Text style={state.recruited ? styles.operational : styles.locked}>{state.recruited ? `LEVEL ${state.level} · ${tierName?.toUpperCase()} · OPERATIONAL` : construction ? "CONSTRUCTION IN PROGRESS" : "WORKSHOP NOT BUILT"}</Text></View></View>
      <Text style={styles.role}>{artisan.fantasyRole}</Text><Text style={styles.description}>{artisan.description}</Text>
      {construction ? <View style={styles.project}><Text style={styles.projectName}>Building {ARTISAN_BUILDINGS[tab][construction.targetLevel - 1]!.name}</Text><Text style={styles.projectMeta}>Started Day {construction.startDay} · Completes Day {construction.completionDay}</Text><Text style={styles.projectDays}>{Math.max(0, construction.completionDay - guild.currentDay)} day(s) remaining</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${Math.min(100, (guild.currentDay - construction.startDay) / Math.max(1, construction.completionDay - construction.startDay) * 100)}%` }]} /></View></View>
      : nextTier ? <View style={styles.project}><Text style={styles.projectName}>{state.level === 0 ? "Construct" : "Upgrade to"} {nextTier.name}</Text><Text style={styles.projectMeta}>{nextTier.goldCost.toLocaleString()} gold · {nextTier.durationDays} days · Requires {requiredSkill?.name}</Text>{!skillMet && <Text style={styles.lockReason}>Unlock {requiredSkill?.name} in the Guildmaster skill tree first.</Text>}<ActionButton label={skillMet ? `${state.level === 0 ? "Begin Construction" : "Begin Upgrade"} · ${nextTier.goldCost.toLocaleString()} Gold` : "Guildmaster Skill Required"} disabled={!skillMet || guild.gold < nextTier.goldCost} onPress={() => act(() => startArtisanConstruction(guild, tab), `${nextTier.name} will complete on Day ${guild.currentDay + nextTier.durationDays}.`)} /></View>
      : <Text style={styles.mastered}>MAXIMUM BUILDING LEVEL</Text>}
    </Panel>

    {tab === "blacksmith" && <><Text style={styles.section}>REPAIR BENCH</Text><Panel style={styles.recipe}><Text style={styles.projectName}>Equipment maintenance</Text><Text style={styles.description}>Damage suffered in battle has a small chance to reduce one equipped item's durability. Durability scales its numerical bonuses; broken equipment provides none until repaired.</Text>{!damagedInventory.length && !damagedEquipped.length ? <Text style={styles.operational}>ALL EQUIPMENT IS IN GOOD REPAIR</Text> : null}{damagedEquipped.map((entry) => <View key={`${entry.hero.id}-${entry.slot}`} style={styles.repairRow}><EquipmentIcon equipmentKey={entry.key} slot={entry.item.slot} label={entry.item.name} size={42}/><View style={styles.flex}><Text style={styles.itemName}>{entry.item.name}</Text><Text style={[styles.meta, entry.item.durability < 40 && styles.lockReason]}>{entry.hero.name} · {getDurabilityLabel(entry.item.durability)} · {entry.item.durability}%</Text></View><SecondaryButton label={`Repair · ${getRepairCost(entry.key)}g`} disabled={!state.recruited || guild.gold < getRepairCost(entry.key)} onPress={() => act(() => repairHeroEquipment(guild, entry.hero.id, entry.slot), `${entry.item.name} restored to 100% durability.`)}/></View>)}{damagedInventory.map((entry) => <View key={`${entry.key}-${entry.index}`} style={styles.repairRow}><EquipmentIcon equipmentKey={entry.key} slot={entry.item!.slot} label={entry.item!.name} size={42}/><View style={styles.flex}><Text style={styles.itemName}>{entry.item!.name}</Text><Text style={[styles.meta, entry.item!.durability < 40 && styles.lockReason]}>Inventory · {getDurabilityLabel(entry.item!.durability)} · {entry.item!.durability}%</Text></View><SecondaryButton label={`Repair · ${getRepairCost(entry.key)}g`} disabled={!state.recruited || guild.gold < getRepairCost(entry.key)} onPress={() => act(() => repairInventoryEquipment(guild, entry.index), `${entry.item!.name} restored to 100% durability.`)}/></View>)}</Panel></>}

    <Text style={styles.section}>RECIPES</Text>
    {lockedRecipeCount > 0 && <Panel style={styles.recipe}><Text style={styles.projectName}>{lockedRecipeCount} undiscovered pattern{lockedRecipeCount === 1 ? "" : "s"}</Text><Text style={styles.description}>Side quests can reveal regional patterns. Elite roguelite clears may reveal class rings, while Boss clears may reveal rare class weapons.</Text></Panel>}
    {!state.recruited && <Text style={styles.lockReason}>Recipes can be inspected now, but crafting remains locked until this building is operational.</Text>}
    {recipes.map((recipe) => { const output = EQUIPMENT[recipe.outputEquipmentId]!; const rarityColor = getEquipmentRarityColor(output.rarity); const effects = output.specialEffectIds.map(describeEquipmentSpecialEffect).filter((effect): effect is NonNullable<typeof effect> => Boolean(effect)); const available = state.recruited && state.level >= recipe.artisanLevel && guild.gold >= recipe.goldCost && materialRequirementsMet(guild, recipe.materials); return <Panel key={recipe.id} style={[styles.recipe, { borderColor: rarityColor }, (!state.recruited || state.level < recipe.artisanLevel) && styles.disabled]}><View style={styles.recipeHead}><EquipmentIcon equipmentKey={output.id} slot={output.slot} label={output.name} size={52}/><View style={styles.flex}><Text style={[styles.itemName, { color: rarityColor }]}>{output.name}</Text><Text style={[styles.meta, { color: rarityColor }]}>{output.rarity.toUpperCase()} · {output.slot} · Workshop Lv {recipe.artisanLevel}</Text></View></View><Text style={styles.description}>{recipe.description}</Text>{effects.map((effect) => <View key={effect.name} style={{ backgroundColor: colors.panel2, borderLeftColor: colors.gold, borderLeftWidth: 3, borderRadius: 7, padding: 8 }}><Text style={{ color: colors.gold, fontSize: 12, fontWeight: "900", marginBottom: 2 }}>{effect.name}</Text><Text style={styles.description}>{effect.description}</Text></View>)}<Text style={styles.cost}>{recipe.goldCost} gold</Text><MaterialCostList costs={recipe.materials} inventory={guild.materials} /><ActionButton label={!state.recruited ? "Build Workshop First" : state.level < recipe.artisanLevel ? `Requires Workshop Level ${recipe.artisanLevel}` : "Craft Item"} disabled={!available} onPress={() => act(() => craftEquipment(guild, recipe.id), `${output.name} added to inventory.`)} /></Panel>; })}
    {tab === "jeweler" && state.recruited && <><Text style={styles.section}>ENCHANT EQUIPMENT</Text><Text style={styles.description}>One initial enchantment slot is available per item. Enchantments remain attached when the gear is equipped.</Text>{guild.inventory.map((key, inventoryIndex) => { const item = resolveEquipmentDefinition(key); if (!item || item.enchantmentIds.length) return null; const options = Object.values(ENCHANTMENTS).filter((enchantment) => enchantment.applicableSlots.includes(item.slot)); if (!options.length) return null; return <Panel key={`${key}-${inventoryIndex}`} style={styles.recipe}><Text style={styles.itemName}>{item.name}</Text><Text style={styles.meta}>{item.slot.toUpperCase()} · Inventory copy {inventoryIndex + 1}</Text>{options.map((enchantment) => { const available = state.level >= enchantment.artisanLevel && guild.gold >= enchantment.goldCost && materialRequirementsMet(guild, enchantment.materials); return <Pressable disabled={!available} key={enchantment.id} onPress={() => act(() => enchantInventoryEquipment(guild, inventoryIndex, enchantment.id), `${item.name} gained ${enchantment.name}.`)} style={[styles.enchant, !available && styles.disabled]}><View style={styles.flex}><Text style={styles.enchantName}>{enchantment.name}</Text><Text style={styles.description}>{enchantment.description}</Text><Text style={styles.cost}>{enchantment.goldCost} gold</Text><MaterialCostList costs={enchantment.materials} inventory={guild.materials} /></View><Text style={styles.arrow}>›</Text></Pressable>; })}</Panel>; })}</>}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 55 }, header: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 7 }, title: { color: colors.text, fontSize: 29, fontWeight: "900" }, day: { color: colors.gold, fontSize: 11, fontWeight: "800", marginTop: 2 }, intro: { color: colors.muted, lineHeight: 21, marginVertical: 13 }, artisan: { gap: 8, borderColor: colors.gold }, lockedWorkshop: { borderColor: colors.border }, buildingHead: { alignItems: "center", flexDirection: "row", gap: 11 }, buildingIcon: { alignItems: "center", backgroundColor: colors.panel2, borderColor: colors.gold, borderRadius: 22, borderWidth: 1, height: 44, justifyContent: "center", width: 44 }, buildingIconText: { color: colors.gold, fontSize: 20, fontWeight: "900" }, artisanName: { color: colors.text, fontSize: 20, fontWeight: "900" }, operational: { color: colors.green, fontSize: 9, fontWeight: "900", marginTop: 2 }, locked: { color: colors.muted, fontSize: 9, fontWeight: "900", marginTop: 2 }, role: { color: colors.gold, fontWeight: "800" }, description: { color: colors.muted, lineHeight: 19 }, project: { backgroundColor: colors.panel2, borderRadius: 10, gap: 6, marginTop: 5, padding: 11 }, projectName: { color: colors.text, fontSize: 16, fontWeight: "900" }, projectMeta: { color: colors.gold, fontSize: 11, fontWeight: "800" }, projectDays: { color: colors.text, fontSize: 12, fontWeight: "900" }, progressTrack: { backgroundColor: colors.background, borderRadius: 5, height: 7, overflow: "hidden" }, progressFill: { backgroundColor: colors.green, height: "100%" }, lockReason: { color: colors.danger, fontSize: 11, lineHeight: 16, marginBottom: 8 }, mastered: { color: colors.green, fontWeight: "900", marginTop: 6 }, section: { color: colors.gold, fontWeight: "900", letterSpacing: 1.3, marginTop: 18, marginBottom: 9 }, recipe: { marginBottom: 10, gap: 7 }, recipeHead: { alignItems: "center", flexDirection: "row", gap: 10 }, repairRow: { alignItems: "center", borderTopColor: colors.border, borderTopWidth: 1, flexDirection: "row", gap: 9, paddingTop: 9 }, itemName: { color: colors.text, fontSize: 18, fontWeight: "900" }, meta: { color: colors.green, fontSize: 11, fontWeight: "800" }, cost: { color: colors.gold, fontSize: 12, fontWeight: "800" }, enchant: { flexDirection: "row", gap: 8, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10, marginTop: 5 }, enchantName: { color: colors.text, fontWeight: "900" }, flex: { flex: 1 }, arrow: { color: colors.gold, fontSize: 26 }, disabled: { opacity: .43 } });
