import React from "react";
import { StyleSheet, Text, View } from "react-native";
import { SETTLEMENTS } from "../../data/world/settlements";
import { REGIONS } from "../../data/world/regions";
import type { GuildState } from "../../game/guild/types";
import { GameIcon } from "../icons/GameIcon";
import { colors } from "../ui";
function Resource({ icon, value, color }: { icon: "gold" | "jeweler" | "victory"; value: string | number; color?: string }) { return <View style={styles.resource}><GameIcon id={icon} size={18} framed={false} /><Text style={[styles.value, color ? { color } : undefined]}>{value}</Text></View>; }
export function GlobalResourceHeader({ guild }: { guild: GuildState }) { const region = REGIONS[guild.world.currentRegionId]; const settlementId = region?.settlementIds.find((id) => guild.world.discoveredSettlementIds.includes(id)); const location = settlementId ? SETTLEMENTS[settlementId]?.name : region?.name ?? "Unknown"; return <View style={styles.header}><View style={styles.identity}><Text numberOfLines={1} style={styles.guild}>{guild.guildName}</Text><Text numberOfLines={1} style={styles.location}>Day {guild.currentDay} · {location}</Text></View><View style={styles.resources}><Resource icon="gold" value={guild.gold.toLocaleString()} /><Resource icon="jeweler" value={guild.gems} color={colors.blue} /><Resource icon="victory" value={guild.reputation} /></View></View>; }
const styles = StyleSheet.create({ header: { minHeight: 56, borderBottomWidth: 1, borderColor: colors.border, backgroundColor: colors.panel, paddingHorizontal: 12, paddingVertical: 8, flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 8 }, identity: { flex: 1, minWidth: 0 }, guild: { color: colors.text, fontSize: 15, fontWeight: "900" }, location: { color: colors.muted, fontSize: 11, marginTop: 2 }, resources: { flexDirection: "row", gap: 7, alignItems: "center" }, resource: { alignItems: "center", flexDirection: "row", gap: 2 }, value: { color: colors.gold, fontSize: 11, fontWeight: "800" } });
