export const GAME_CONFIG = {
  startingGold: 5_000,
  startingGems: 5,
  startingReputation: 0,
  startingDay: 1,
  recruitmentCandidateCount: 3,
  baseAttributeMin: 1,
  baseAttributeMax: 20,
  potentialMin: 50,
  potentialMax: 100,
  baseHeroCapacity: 8,
  rewardedAdGems: 5,
  goldPerGem: 250,
  maxAdventureStamina: 100,
  adventureStaminaRecoveryPerDay: 25,
  standardQuestStaminaCost: 50,
  dailyTavernIncome: 50,
} as const;
