export const GAME_CONFIG = {
  startingGold: 5_000,
  startingGems: 5,
  startingRations: 24,
  rationBundleSize: 8,
  rationBundleGoldCost: 40,
  startingReputation: 0,
  startingDay: 1,
  recruitmentCandidateCount: 3,
  baseAttributeMin: 1,
  baseAttributeMax: 20,
  baseHeroCapacity: 8,
  rewardedAdGems: 5,
  goldPerGem: 250,
  maxAdventureStamina: 100,
  adventureStaminaRecoveryPerDay: 35,
  dailyHeroHealthRecoveryRatio: 0.10,
  standardQuestStaminaCost: 50,
  // Passive income keeps the guild alive, but quests must fund treatment,
  // maintenance, crafting, and expansion.
  dailyTavernIncome: 40,
} as const;
