import React from "react";
import { Pressable, StyleSheet, Text, View, type ViewProps } from "react-native";
import { CLASSES } from "../data/classes/classes";
import { RACES } from "../data/races/races";
import type { Hero } from "../game/heroes/types";
import { getRaceNameColor } from "../ui/raceColors";
import { HeroPortrait } from "./heroes/HeroPortrait";
import { useTheme } from "../theme/theme";

import { NotificationDot } from "./navigation/NotificationDot";
export const colors = { background: "#101416", panel: "#1a2123", panel2: "#232d2f", gold: "#d8ad5c", text: "#f3eee3", muted: "#a8b1ad", green: "#79b887", danger: "#dd7a73", border: "#354044", blue: "#70a4c5" };

export function Panel(props: ViewProps) { const{colors:c}=useTheme();return <View {...props} style={[styles.panel,{backgroundColor:c.panel,borderColor:c.border},props.style]} />; }
export function SectionTitle({ children }: React.PropsWithChildren) { const{colors:c}=useTheme();return <Text style={[styles.sectionTitle,{color:c.gold}]}>{children}</Text>; }
export function ActionButton({ label, onPress, disabled = false }: { label: string; onPress(): void; disabled?: boolean }) { const{colors:c}=useTheme();return <Pressable accessibilityRole="button" disabled={disabled} hitSlop={6} onPress={onPress} style={({ pressed }) => [styles.button,{backgroundColor:c.gold}, (pressed || disabled) && styles.buttonDim]}><Text style={[styles.buttonText,{color:c.buttonText}]}>{label}</Text></Pressable>; }
export function SecondaryButton({ label, onPress, disabled = false }: { label: string; onPress(): void; disabled?: boolean }) { const{colors:c}=useTheme();return <Pressable accessibilityRole="button" disabled={disabled} hitSlop={6} onPress={onPress} style={({ pressed }) => [styles.secondaryButton,{borderColor:c.gold}, (pressed || disabled) && styles.buttonDim]}><Text style={[styles.secondaryText,{color:c.gold}]}>{label}</Text></Pressable>; }
export function BackButton({ onPress }: { onPress(): void }) { const{colors:c}=useTheme();return <Pressable accessibilityRole="button" onPress={onPress} hitSlop={12}><Text style={[styles.back,{color:c.gold}]}>‹ Back</Text></Pressable>; }
export function EmptyState({ title, message, actionLabel, onAction }: { title: string; message: string; actionLabel?: string; onAction?(): void }) { const{colors:c}=useTheme();return <Panel style={styles.empty}><Text style={[styles.emptyTitle,{color:c.text}]}>{title}</Text><Text style={[styles.muted,{color:c.muted}]}>{message}</Text>{actionLabel && onAction ? <ActionButton label={actionLabel} onPress={onAction} /> : null}</Panel>; }
export function SegmentedTabs<T extends string>({ values, value, onChange, notificationValues = [] }: { values: readonly T[]; value: T; onChange(value: any): void; notificationValues?: readonly T[] }) { const{colors:c}=useTheme();return <View style={[styles.tabs,{backgroundColor:c.panel}]}>{values.map((item) => <Pressable key={item} hitSlop={4} onPress={() => onChange(item)} accessibilityRole="tab" accessibilityState={{ selected: item === value }} style={[styles.tab, item === value && {backgroundColor:c.gold}]}><Text style={[styles.tabText,{color:c.muted},item === value && {color:c.buttonText}]}>{item}</Text>{notificationValues.includes(item) ? <View style={{ position: "absolute", top: 0, right: 1 }}><NotificationDot label={`${item}: choice available`}/></View> : null}</Pressable>)}</View>; }
export function Portrait({ hero, size = 84 }: { hero: Hero; size?: number }) { return <HeroPortrait raceId={hero.raceId} classId={hero.classId} gender={hero.gender} variant={hero.portraitVariant ?? 0} label={hero.name} size={size} />; }
export function HeroCard({ hero, onPress, subtitle, notification = false }: { hero: Hero; onPress(): void; subtitle?: string; notification?: boolean }) { const{colors:c}=useTheme();return <Pressable accessibilityRole="button" accessibilityLabel={`Inspect ${hero.name}`} onPress={onPress} style={({ pressed }) => [styles.heroCard,{backgroundColor:c.panel,borderColor:c.border}, pressed && styles.buttonDim]}><Portrait hero={hero} /><View style={styles.heroCardText}><Text style={[styles.heroName, { color: getRaceNameColor(hero.raceId) }]}>{hero.name}</Text><Text style={[styles.muted,{color:c.muted}]}>{subtitle ?? `${RACES[hero.raceId].name} • ${CLASSES[hero.classId].name}`}</Text><Text style={[styles.small,{color:c.text}]}>Level {hero.level}</Text></View>{notification ? <NotificationDot label="Hero skill choice available"/> : null}<Text style={[styles.chevron,{color:c.gold}]}>›</Text></Pressable>; }

const styles = StyleSheet.create({ panel: { backgroundColor: colors.panel, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 16 }, sectionTitle: { color: colors.gold, fontSize: 13, letterSpacing: 1.4, fontWeight: "800", marginBottom: 10, marginTop: 8 }, button: { backgroundColor: colors.gold, paddingHorizontal: 18, paddingVertical: 13, borderRadius: 10, alignItems: "center" }, secondaryButton: { borderWidth: 1, borderColor: colors.gold, paddingHorizontal: 16, paddingVertical: 11, borderRadius: 10, alignItems: "center" }, secondaryText: { color: colors.gold, fontSize: 14, fontWeight: "800" }, buttonDim: { opacity: 0.55 }, buttonText: { color: "#17130c", fontSize: 15, fontWeight: "800" }, back: { color: colors.gold, fontSize: 17, fontWeight: "700", paddingVertical: 6 }, portrait: { backgroundColor: "#34484a", borderColor: colors.gold, borderWidth: 2, alignItems: "center", justifyContent: "center" }, initials: { color: colors.text, fontWeight: "800" }, portraitClass: { color: colors.gold, fontSize: 9, fontWeight: "800" }, heroCard: { backgroundColor: colors.panel, borderColor: colors.border, borderWidth: 1, borderRadius: 14, padding: 14, flexDirection: "row", alignItems: "center", gap: 14, marginBottom: 12 }, heroCardText: { flex: 1, gap: 4 }, heroName: { color: colors.text, fontSize: 20, fontWeight: "800" }, muted: { color: colors.muted, fontSize: 14 }, small: { color: colors.text, fontSize: 13 }, chevron: { color: colors.gold, fontSize: 34 }, empty: { alignItems: "stretch", gap: 12 }, emptyTitle: { color: colors.text, fontSize: 18, fontWeight: "800" }, tabs: { flexDirection: "row", backgroundColor: colors.panel, borderRadius: 11, padding: 3, marginBottom: 14 }, tab: { flex: 1, alignItems: "center", paddingVertical: 9, borderRadius: 8 }, activeTab: { backgroundColor: colors.gold }, tabText: { color: colors.muted, fontSize: 12, fontWeight: "800" }, activeTabText: { color: "#17130c" } });
