import React from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { BackButton, Panel, SecondaryButton, colors } from "../../components/ui";
import type { UiPreferences } from "../../game/guild/types";
import { useGuild } from "../../state/GuildContext";
import { THEMES, type ThemeId, useTheme } from "../../theme/theme";
import { showAdMobPrivacyOptions } from "../../game/monetization/admobRewardedAdProvider";
import { useGameDialog } from "../../components/dialogs/GameDialog";
import { PRIVACY_POLICY_URL } from "../../config/legal";

function Toggle({label,description,value,onChange}:{label:string;description:string;value:boolean;onChange(value:boolean):void}){return <Pressable accessibilityRole="switch" accessibilityState={{checked:value}} onPress={()=>onChange(!value)}><Panel style={[styles.row,value&&styles.active]}><View style={styles.copy}><Text style={styles.name}>{label}</Text><Text style={styles.description}>{description}</Text></View><View style={[styles.switch,value&&styles.switchOn]}><View style={[styles.knob,value&&styles.knobOn]}/></View></Panel></Pressable>}

export function SettingsScreen({onBack}:{onBack():void}) {
  const {guild,updateGuild}=useGuild(); const settings=guild.uiPreferences; const theme=useTheme(); const {showDialog}=useGameDialog();
  const set=<K extends keyof UiPreferences>(key:K,value:UiPreferences[K])=>updateGuild({...guild,uiPreferences:{...settings,[key]:value}});
  const themeId=settings.themeId??"guild_dark";
  return <ScrollView style={{backgroundColor:theme.colors.background}} contentContainerStyle={styles.content}>
    <BackButton onPress={onBack}/><Text style={styles.eyebrow}>PLAYER PREFERENCES</Text><Text style={styles.title}>Settings</Text><Text style={styles.intro}>These options are stored with this guild save and do not change combat balance.</Text>
    <Text style={styles.section}>COLOR THEME</Text>
    <View style={styles.themeGrid}>{(Object.keys(THEMES) as ThemeId[]).map((id)=>{const option=THEMES[id];const selected=id===themeId;return <Pressable key={id} accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={()=>set("themeId",id)} style={[styles.themeCard,{backgroundColor:option.colors.panel,borderColor:selected?option.colors.gold:option.colors.border}]}><View style={styles.swatches}><View style={[styles.swatch,{backgroundColor:option.colors.background}]}/><View style={[styles.swatch,{backgroundColor:option.colors.panel2}]}/><View style={[styles.swatch,{backgroundColor:option.colors.gold}]}/></View><Text style={[styles.optionName,{color:option.colors.text}]}>{selected?"✓ ":""}{option.name}</Text><Text style={[styles.optionDescription,{color:option.colors.muted}]}>{option.description}</Text></Pressable>})}</View>
    <Text style={styles.themeNote}>Light Parchment will follow after remaining feature screens have moved to semantic theme colors.</Text>
    <Text style={styles.section}>ACCESSIBILITY & FLOW</Text>
    <Toggle label="Reduced combat effects" description="Hides projectile and impact particle layers while preserving damage and condition information." value={settings.reduceCombatEffects} onChange={(value)=>set("reduceCombatEffects",value)}/>
    <Toggle label="Confirm End Turn" description="Requests confirmation before ending a hero's turn, preventing accidental taps." value={settings.confirmEndTurn} onChange={(value)=>set("confirmEndTurn",value)}/>
    <Toggle label="Compact quest cards" description="Quest lists initially show only the information needed to choose an activity." value={settings.compactQuestCards} onChange={(value)=>set("compactQuestCards",value)}/>
    <Text style={styles.section}>DEFAULT COMBAT CAMERA</Text><View style={styles.options}>{(["fit","close"] as const).map((value)=><Pressable accessibilityRole="radio" accessibilityState={{checked:settings.defaultCombatZoom===value}} key={value} onPress={()=>set("defaultCombatZoom",value)} style={[styles.option,settings.defaultCombatZoom===value&&styles.optionActive]}><Text style={styles.optionName}>{value==="fit"?"Fit Battlefield":"Closer View"}</Text><Text style={styles.optionDescription}>{value==="fit"?"Shows the entire board when combat opens.":"Starts large battlefields at 135% zoom for clearer portraits."}</Text></Pressable>)}</View>
    <Text style={styles.section}>PRIVACY & ADS</Text><Panel style={styles.privacy}><Text style={styles.name}>Privacy and advertising choices</Text><Text style={styles.description}>Read how Guildmaster and Google Mobile Ads handle information, or review the advertising choices available in your region.</Text><View style={styles.privacyAction}><SecondaryButton label="Privacy Policy" onPress={()=>{void Linking.openURL(PRIVACY_POLICY_URL).catch(()=>showDialog({title:"Privacy Policy Unavailable",message:"The privacy-policy page could not be opened.",tone:"danger"}));}}/><SecondaryButton label="Manage Ad Privacy" onPress={()=>{void showAdMobPrivacyOptions().catch((error:unknown)=>showDialog({title:"Privacy Options Unavailable",message:error instanceof Error?error.message:"Privacy options could not be opened.",tone:"danger"}));}}/></View></Panel>
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:18,paddingBottom:50},eyebrow:{color:colors.gold,fontSize:10,fontWeight:"900",letterSpacing:1.5,marginTop:12},title:{color:colors.text,fontSize:30,fontWeight:"900",marginTop:5},intro:{color:colors.muted,lineHeight:20,marginBottom:15,marginTop:7},row:{alignItems:"center",flexDirection:"row",gap:12,marginBottom:9},active:{borderColor:colors.gold},copy:{flex:1},name:{color:colors.text,fontSize:16,fontWeight:"900"},description:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},switch:{backgroundColor:"#343d40",borderRadius:11,height:22,padding:3,width:40},switchOn:{backgroundColor:colors.green},knob:{backgroundColor:colors.text,borderRadius:8,height:16,width:16},knobOn:{alignSelf:"flex-end"},section:{color:colors.gold,fontSize:11,fontWeight:"900",letterSpacing:1.2,marginBottom:8,marginTop:12},options:{flexDirection:"row",gap:8},option:{backgroundColor:colors.panel,borderColor:colors.border,borderRadius:10,borderWidth:1,flex:1,padding:12},optionActive:{borderColor:colors.gold,backgroundColor:colors.panel2},optionName:{color:colors.text,fontWeight:"900"},optionDescription:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:4},themeGrid:{gap:8},themeCard:{borderRadius:11,borderWidth:2,padding:12},swatches:{flexDirection:"row",gap:5,marginBottom:9},swatch:{borderColor:"rgba(255,255,255,.25)",borderRadius:4,borderWidth:1,height:18,width:34},themeNote:{color:colors.muted,fontSize:10,lineHeight:15,marginBottom:8,marginTop:8},privacy:{gap:4},privacyAction:{gap:8,marginTop:9}});
