import React, { useState } from "react";
import { Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { BackButton, Panel, SecondaryButton, SegmentedTabs, colors } from "../../components/ui";
import type { UiPreferences } from "../../game/guild/types";
import { useGuild } from "../../state/GuildContext";
import { THEMES, type ThemeId, useTheme } from "../../theme/theme";
import { showAdMobPrivacyOptions } from "../../game/monetization/admobRewardedAdProvider";
import { useGameDialog } from "../../components/dialogs/GameDialog";
import { PRIVACY_POLICY_URL } from "../../config/legal";

function Toggle({label,description,value,onChange}:{label:string;description:string;value:boolean;onChange(value:boolean):void}){return <Pressable accessibilityRole="switch" accessibilityState={{checked:value}} onPress={()=>onChange(!value)}><Panel style={[styles.row,value&&styles.active]}><View style={styles.copy}><Text style={styles.name}>{label}</Text><Text style={styles.description}>{description}</Text></View><View style={[styles.switch,value&&styles.switchOn]}><View style={[styles.knob,value&&styles.knobOn]}/></View></Panel></Pressable>}

export function SettingsScreen({onBack,openTutorialGuide}:{onBack():void;openTutorialGuide():void}) {
  const {guild,updateGuild,activeSaveSlot,returnToMainMenu}=useGuild(); const [tab,setTab]=useState<"Display"|"Gameplay"|"Account">("Display"); const [returning,setReturning]=useState(false); const settings=guild.uiPreferences; const theme=useTheme(); const {showDialog}=useGameDialog();
  const set=<K extends keyof UiPreferences>(key:K,value:UiPreferences[K])=>updateGuild({...guild,uiPreferences:{...settings,[key]:value}});
  const themeId=settings.themeId??"guild_dark";
  return <ScrollView style={{backgroundColor:theme.colors.background}} contentContainerStyle={styles.content}>
    <BackButton onPress={onBack}/><Text style={styles.eyebrow}>PLAYER PREFERENCES</Text><Text style={styles.title}>Settings</Text><Text style={styles.intro}>These options are stored with this guild save and do not change combat balance.</Text>
    <SegmentedTabs values={["Display","Gameplay","Account"] as const} value={tab} onChange={setTab}/>{tab==="Display"&&<><Text style={styles.section}>COLOR THEME</Text>
    <View style={styles.themeGrid}>{(Object.keys(THEMES) as ThemeId[]).map((id)=>{const option=THEMES[id];const selected=id===themeId;return <Pressable key={id} accessibilityRole="radio" accessibilityState={{checked:selected}} onPress={()=>set("themeId",id)} style={[styles.themeCard,{backgroundColor:option.colors.panel,borderColor:selected?option.colors.gold:option.colors.border}]}><View style={styles.swatches}><View style={[styles.swatch,{backgroundColor:option.colors.background}]}/><View style={[styles.swatch,{backgroundColor:option.colors.panel2}]}/><View style={[styles.swatch,{backgroundColor:option.colors.gold}]}/></View><Text style={[styles.optionName,{color:option.colors.text}]}>{selected?"✓ ":""}{option.name}</Text><Text style={[styles.optionDescription,{color:option.colors.muted}]}>{option.description}</Text></Pressable>})}</View>
    </>}{tab==="Gameplay"&&<><Text style={styles.section}>HELP & TUTORIALS</Text><Panel style={styles.privacy}><Text style={styles.name}>Guildmaster Handbook</Text><Text style={styles.description}>Review the current tutorials for recruitment, the War Table, Side Quests, deployment checks, red-border basic attacks, the Guild Planner, hero progression, travel, archives, gear and durability, dungeons, and Raids.</Text><View style={styles.privacyAction}><SecondaryButton label="Open Guildmaster Handbook" onPress={openTutorialGuide}/></View></Panel>
    <Text style={styles.section}>ACCESSIBILITY & FLOW</Text>
    <Toggle label="Strong combat contrast" description="Makes reachable, targetable, safe, hazardous, selected, and objective tiles more visually distinct." value={settings.strongerCombatContrast} onChange={(value)=>set("strongerCombatContrast",value)}/>
    <Toggle label="Reduced motion" description="Shortens or removes projectile, battlefield, and impact movement while preserving combat results." value={settings.reduceMotion} onChange={(value)=>set("reduceMotion",value)}/>
    <Toggle label="Reduced combat effects" description="Hides projectile and impact particle layers while preserving damage and condition information." value={settings.reduceCombatEffects} onChange={(value)=>set("reduceCombatEffects",value)}/>
    <Toggle label="Tactile feedback" description="Uses short device vibration feedback for key combat confirmations. Automatically ignored on web." value={settings.tactileFeedback} onChange={(value)=>set("tactileFeedback",value)}/>
    <Toggle label="Confirm End Turn" description="Requests confirmation before ending a hero's turn, preventing accidental taps." value={settings.confirmEndTurn} onChange={(value)=>set("confirmEndTurn",value)}/>
    <Toggle label="Compact quest cards" description="Quest lists initially show only the information needed to choose an activity." value={settings.compactQuestCards} onChange={(value)=>set("compactQuestCards",value)}/>
    <Text style={styles.section}>ENEMY TURN SPEED</Text><View style={styles.speedOptions}>{(["normal","fast","very_fast"] as const).map((value)=><Pressable accessibilityRole="radio" accessibilityState={{checked:settings.enemyTurnSpeed===value}} key={value} onPress={()=>set("enemyTurnSpeed",value)} style={[styles.option,settings.enemyTurnSpeed===value&&styles.optionActive]}><Text style={styles.optionName}>{value==="normal"?"Normal":value==="fast"?"Fast":"Very Fast"}</Text><Text style={styles.optionDescription}>{value==="normal"?"About 0.7s between enemy actions so attacks remain readable.":value==="fast"?"About 0.4s between enemy actions.":"Minimal pause for already-familiar fights."}</Text></Pressable>)}</View>
    <Text style={styles.section}>DEFAULT COMBAT CAMERA</Text><View style={styles.options}>{(["fit","close"] as const).map((value)=><Pressable accessibilityRole="radio" accessibilityState={{checked:settings.defaultCombatZoom===value}} key={value} onPress={()=>set("defaultCombatZoom",value)} style={[styles.option,settings.defaultCombatZoom===value&&styles.optionActive]}><Text style={styles.optionName}>{value==="fit"?"Fit Battlefield":"Closer View"}</Text><Text style={styles.optionDescription}>{value==="fit"?"Shows the entire board when combat opens.":"Starts large battlefields at 135% zoom for clearer portraits."}</Text></Pressable>)}</View>
    </>}{tab==="Account"&&<><Text style={styles.section}>SAVE SLOTS</Text><Panel style={styles.privacy}><Text style={styles.name}>Current guild · Save Slot {activeSaveSlot ?? "—"}</Text><Text style={styles.description}>Guild progress autosaves to this slot. Return to the save selector to continue the other guild or start a new one.</Text><View style={styles.privacyAction}><SecondaryButton guardMs={800} disabled={returning} label={returning?"Saving Guild…":"Save & Return to Save Select"} onPress={()=>showDialog({title:"Return to Save Select?",message:"Your current guild will be saved before returning to the two-slot selector.",eyebrow:"SAVE SLOTS",actions:[{label:"Stay Here",tone:"secondary"},{label:"Save & Return",tone:"primary",onPress:()=>{if(returning)return;setReturning(true);void returnToMainMenu().catch((error:unknown)=>{setReturning(false);showDialog({title:"Could not save guild",message:error instanceof Error?error.message:"Save failed. Please try again.",tone:"danger"});});}}]})}/></View></Panel>
    <Text style={styles.section}>PRIVACY & ADS</Text><Panel style={styles.privacy}><Text style={styles.name}>Privacy and advertising choices</Text><Text style={styles.description}>Read how Guildmaster and Google Mobile Ads handle information, or review the advertising choices available in your region.</Text><View style={styles.privacyAction}><SecondaryButton guardMs={800} label="Privacy Policy" onPress={()=>{void Linking.openURL(PRIVACY_POLICY_URL).catch(()=>showDialog({title:"Privacy Policy Unavailable",message:"The privacy-policy page could not be opened.",tone:"danger"}));}}/><SecondaryButton guardMs={800} label="Manage Ad Privacy" onPress={()=>{void showAdMobPrivacyOptions().catch((error:unknown)=>showDialog({title:"Privacy Options Unavailable",message:error instanceof Error?error.message:"Privacy options could not be opened.",tone:"danger"}));}}/></View></Panel></>}
  </ScrollView>;
}
const styles=StyleSheet.create({content:{padding:16,paddingBottom:50},eyebrow:{color:colors.gold,fontSize:10,fontWeight:"900",letterSpacing:1.5,marginTop:12},title:{color:colors.text,fontSize:30,fontWeight:"900",marginTop:5},intro:{color:colors.muted,lineHeight:20,marginBottom:15,marginTop:7},row:{alignItems:"center",flexDirection:"row",gap:12,marginBottom:9},active:{borderColor:colors.gold},copy:{flex:1},name:{color:colors.text,fontSize:16,fontWeight:"900"},description:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},switch:{backgroundColor:"#343d40",borderRadius:11,height:22,padding:3,width:40},switchOn:{backgroundColor:colors.green},knob:{backgroundColor:colors.text,borderRadius:8,height:16,width:16},knobOn:{alignSelf:"flex-end"},section:{color:colors.gold,fontSize:11,fontWeight:"900",letterSpacing:1.2,marginBottom:8,marginTop:12},options:{flexDirection:"row",gap:8},speedOptions:{gap:8},option:{backgroundColor:colors.panel,borderColor:colors.border,borderRadius:10,borderWidth:1,flex:1,padding:12},optionActive:{borderColor:colors.gold,backgroundColor:colors.panel2},optionName:{color:colors.text,fontWeight:"900"},optionDescription:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:4},themeGrid:{gap:8},themeCard:{borderRadius:11,borderWidth:2,padding:12},swatches:{flexDirection:"row",gap:5,marginBottom:9},swatch:{borderColor:"rgba(255,255,255,.25)",borderRadius:4,borderWidth:1,height:18,width:34},themeNote:{color:colors.muted,fontSize:10,lineHeight:15,marginBottom:8,marginTop:8},privacy:{gap:4},privacyAction:{gap:8,marginTop:9}});
