import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { BackButton, Panel, SectionTitle, colors } from "../../components/ui";
import { CAMPAIGN_CHOICES } from "../../data/campaign/campaignChoices";
import { CAMPAIGN_NODES, CHAPTER_1 } from "../../data/campaign/chapter1";
import { completeCampaignNode, getAvailableCampaignNodes } from "../../game/campaign/campaignService";
import { resolveCampaignChoice } from "../../game/campaign/campaignChoiceResolver";
import type { GuildState } from "../../game/guild/types";
export function CampaignScreen({ guild, updateGuild, onBack, startQuest }: { guild: GuildState; updateGuild(guild: GuildState): void; onBack(): void; startQuest(questId: string, nodeId: string): void }) { const available = new Set(getAvailableCampaignNodes(guild.world).map((node) => node.id)); const complete = (nodeId: string, choiceId?: string) => { let world = choiceId ? resolveCampaignChoice(guild.world, choiceId) : guild.world; const result = completeCampaignNode(world, nodeId); updateGuild({ ...guild, world: result.worldState, gold: guild.gold + result.goldReward, reputation: guild.reputation + result.guildReputationReward }); };
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.title}>Chapter 1</Text><Text style={styles.chapter}>{CHAPTER_1.name}</Text><Text style={styles.intro}>The Wardstones that protected Eldoria are failing. Ordinary guild contracts are beginning to reveal a connected threat.</Text><SectionTitle>STORY PATH</SectionTitle>{CHAPTER_1.nodeIds.map((id, index) => { const node = CAMPAIGN_NODES[id]!; const done = guild.world.completedCampaignNodeIds.includes(id); const ready = available.has(id); return <Panel key={id} style={[styles.node, done && styles.done]}><View style={styles.row}><Text style={styles.number}>{index + 1}</Text><View style={styles.flex}><Text style={styles.nodeTitle}>{node.title}</Text><Text style={styles.type}>{done ? "✓ COMPLETE" : ready ? `${node.type.toUpperCase()} · AVAILABLE` : "🔒 LOCKED"}</Text></View></View>{ready && node.questId && <Pressable onPress={() => startQuest(node.questId!, node.id)} style={styles.button}><Text style={styles.buttonText}>{node.type === "boss" ? "Face Boss" : "Start Quest"}</Text></Pressable>}{ready && !node.questId && node.choiceIds?.map((choiceId) => <Pressable key={choiceId} onPress={() => complete(id, choiceId)} style={styles.choice}><Text style={styles.choiceText}>{CAMPAIGN_CHOICES[choiceId]!.text}</Text></Pressable>)}{ready && !node.questId && !node.choiceIds?.length && <Pressable onPress={() => complete(id)} style={styles.button}><Text style={styles.buttonText}>Continue Story</Text></Pressable>}</Panel>; })}</ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 50 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 10 }, chapter: { color: colors.gold, fontSize: 18, fontWeight: "800", marginTop: 3 }, intro: { color: colors.muted, lineHeight: 21, marginVertical: 13 }, node: { marginBottom: 10 }, done: { opacity: .65 }, row: { flexDirection: "row", gap: 12, alignItems: "center" }, number: { color: colors.gold, fontSize: 24, fontWeight: "900" }, flex: { flex: 1 }, nodeTitle: { color: colors.text, fontSize: 17, fontWeight: "800" }, type: { color: colors.muted, fontSize: 10, marginTop: 3 }, button: { backgroundColor: colors.gold, borderRadius: 8, padding: 10, alignItems: "center", marginTop: 10 }, buttonText: { color: "#1b160d", fontWeight: "900" }, choice: { borderColor: colors.gold, borderWidth: 1, borderRadius: 8, padding: 10, marginTop: 8 }, choiceText: { color: colors.text, fontWeight: "700" } });
