import React, { useEffect, useRef, useState } from "react";
import { AccessibilityInfo, Animated, StyleSheet, Text, View } from "react-native";
import type { CombatVisualEvent } from "../../game/combat/combatTypes";

export type TileCombatEffect = CombatVisualEvent["effects"][number] & { eventId:number; damageType?:CombatVisualEvent["damageType"] };

export function PixelCombatEffect({effect}:{effect:TileCombatEffect}){
  const progress=useRef(new Animated.Value(0)).current;const [reduced,setReduced]=useState(false);
  useEffect(()=>{AccessibilityInfo.isReduceMotionEnabled().then(setReduced);const subscription=AccessibilityInfo.addEventListener("reduceMotionChanged",setReduced);return()=>subscription.remove();},[]);
  useEffect(()=>{progress.setValue(0);Animated.timing(progress,{toValue:1,duration:reduced?220:650,useNativeDriver:true}).start();},[effect.eventId,progress,reduced]);
  const color=effect.healing>0?"#78f0a5":effect.damageType==="magic"?"#b58cff":effect.damageType==="true"?"#fff2ac":"#ff765f";const label=effect.healing>0?`+${effect.healing}`:effect.hit?`-${effect.damage}`:"MISS";const conditionColor=effect.conditionIds.includes("burning")?"#ff7a3d":effect.conditionIds.includes("poisoned")?"#6bdb66":effect.conditionIds.some((id)=>id.includes("frozen")||id.includes("rooted"))?"#74d8f2":effect.conditionIds.length?"#efb060":null;
  return <View pointerEvents="none" style={StyleSheet.absoluteFill}><Animated.View style={[styles.flash,{borderColor:color,opacity:progress.interpolate({inputRange:[0,.15,.6,1],outputRange:[0,1,.55,0]}),transform:[{scale:progress.interpolate({inputRange:[0,.35,1],outputRange:[.45,1.15,1.35]})}]}]}>{!reduced&&effect.hit&&<><View style={[styles.pixel,{backgroundColor:color,left:"12%",top:"18%"}]}/><View style={[styles.pixel,{backgroundColor:color,right:"10%",top:"36%"}]}/><View style={[styles.pixelSmall,{backgroundColor:color,bottom:"12%",left:"35%"}]}/>{effect.damageType==="physical"&&<View style={[styles.slash,{backgroundColor:color}]}/>}</>}{conditionColor&&<Animated.View style={[styles.conditionRing,{borderColor:conditionColor,opacity:progress.interpolate({inputRange:[0,.35,1],outputRange:[0,1,0]})}]}/>}<Animated.Text style={[styles.number,{color,opacity:progress.interpolate({inputRange:[0,.1,.75,1],outputRange:[0,1,1,0]}),transform:[{translateY:progress.interpolate({inputRange:[0,1],outputRange:[2,reduced?-5:-20]})}]}]}>{effect.critical?`CRIT ${label}`:label}</Animated.Text></Animated.View></View>;
}
const styles=StyleSheet.create({flash:{bottom:0,left:0,right:0,top:0,position:"absolute",alignItems:"center",borderWidth:2,justifyContent:"center",zIndex:20},number:{backgroundColor:"rgba(8,10,14,.84)",fontSize:8,fontWeight:"900",paddingHorizontal:2,position:"absolute",top:-9,zIndex:24},pixel:{height:4,position:"absolute",width:4},pixelSmall:{height:3,position:"absolute",width:3},slash:{height:3,position:"absolute",transform:[{rotate:"-35deg"}],width:"72%"},conditionRing:{borderRadius:999,borderWidth:2,height:"82%",position:"absolute",width:"82%"}});
