import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SkillIcon } from "../skills/SkillIcon";
import type { DamageType } from "../../game/combat/skillTypes";
import { DamageTypeBadge } from "./DamageTypeBadge";
import { useTheme } from "../../theme/theme";

export interface SkillBarItem { id: string; name: string; detail: string; enabled: boolean; damageType?:DamageType }
export function SkillBar({ items, selectedId, onSelect, onInspect }: { items: readonly SkillBarItem[]; selectedId?: string; onSelect(id: string): void; onInspect?(id: string): void }) { const{colors}=useTheme();return <View style={styles.wrap}>{items.map((item) => <Pressable key={item.id} onPress={() => { onInspect?.(item.id); if (item.enabled) onSelect(item.id); }} style={[styles.button,{backgroundColor:colors.panel2,borderColor:colors.border}, selectedId === item.id && {borderColor:colors.gold,borderWidth:2}, !item.enabled && styles.disabled]}><SkillIcon skillId={item.id} size={44} /><View style={styles.copy}><View style={styles.nameRow}><Text style={[styles.name,{color:colors.text}]}>{item.name}</Text>{item.damageType&&<DamageTypeBadge type={item.damageType}/>}</View><Text style={[styles.detail,{color:colors.muted}]}>{item.detail}</Text><Text style={[styles.tap,{color:colors.gold}]}>Tap for details</Text></View></Pressable>)}</View>; }

export function QuickSkillBar({ items, selectedId, onSelect, endControl }: { items: readonly SkillBarItem[]; selectedId?: string; onSelect(id: string): void; endControl?: React.ReactNode }) {
  const{colors}=useTheme();return <View style={styles.quickRow}><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.quickScroll} contentContainerStyle={styles.quickWrap}>{items.map((item) => <Pressable accessibilityLabel={`${item.name}. ${item.damageType??"support"}. ${item.detail}`} accessibilityRole="button" accessibilityState={{ disabled: !item.enabled, selected: selectedId === item.id }} disabled={!item.enabled} key={item.id} onPress={() => onSelect(item.id)} style={[styles.quickButton,{backgroundColor:colors.panel2,borderColor:colors.border}, selectedId === item.id && {backgroundColor:colors.panel,borderColor:colors.gold,borderWidth:2}, !item.enabled && styles.disabled]}>{item.damageType&&<DamageTypeBadge type={item.damageType} compact/>}<SkillIcon skillId={item.id} size={46}/><Text numberOfLines={1} style={[styles.quickName,{color:colors.text}]}>{item.name}</Text></Pressable>)}</ScrollView>{endControl}</View>;
}

const styles = StyleSheet.create({ wrap: { gap: 7 }, button: { alignItems: "center", flexDirection: "row", gap: 10, padding: 8, borderWidth: 1, borderColor: "#445069", borderRadius: 9, backgroundColor: "#202a3d" }, copy: { flex: 1 },nameRow:{alignItems:"center",flexDirection:"row",gap:7}, disabled: { opacity: .4 }, name: { color: "#f3f4f7", fontWeight: "800" }, detail: { color: "#9ca7b9", fontSize: 12, marginTop: 2 }, tap: { color: "#d8ad5c", fontSize: 10, marginTop: 4, fontWeight: "700" }, quickRow: { alignItems: "stretch", flexDirection: "row" }, quickScroll: { flex: 1 }, quickWrap: { gap: 8, paddingHorizontal: 9, paddingVertical: 8 }, quickButton: { alignItems: "center", backgroundColor: "#202a3d", borderColor: "#445069", borderRadius: 9, borderWidth: 1, padding: 5, width: 66 }, quickName: { color: "#f3f4f7", fontSize: 9, fontWeight: "800", marginTop: 3, maxWidth: 58 } });
