import React from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SkillIcon } from "../skills/SkillIcon";

export interface SkillBarItem { id: string; name: string; detail: string; enabled: boolean }
export function SkillBar({ items, selectedId, onSelect, onInspect }: { items: readonly SkillBarItem[]; selectedId?: string; onSelect(id: string): void; onInspect?(id: string): void }) { return <View style={styles.wrap}>{items.map((item) => <Pressable key={item.id} onPress={() => { onInspect?.(item.id); if (item.enabled) onSelect(item.id); }} style={[styles.button, selectedId === item.id && styles.selected, !item.enabled && styles.disabled]}><SkillIcon skillId={item.id} size={44} /><View style={styles.copy}><Text style={styles.name}>{item.name}</Text><Text style={styles.detail}>{item.detail}</Text><Text style={styles.tap}>Tap for details</Text></View></Pressable>)}</View>; }

export function QuickSkillBar({ items, selectedId, onSelect }: { items: readonly SkillBarItem[]; selectedId?: string; onSelect(id: string): void }) {
  return <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.quickWrap}>{items.map((item) => <Pressable accessibilityLabel={`${item.name}. ${item.detail}`} accessibilityRole="button" accessibilityState={{ disabled: !item.enabled, selected: selectedId === item.id }} disabled={!item.enabled} key={item.id} onPress={() => onSelect(item.id)} style={[styles.quickButton, selectedId === item.id && styles.quickSelected, !item.enabled && styles.disabled]}><SkillIcon skillId={item.id} size={46}/><Text numberOfLines={1} style={styles.quickName}>{item.name}</Text></Pressable>)}</ScrollView>;
}

const styles = StyleSheet.create({ wrap: { gap: 7 }, button: { alignItems: "center", flexDirection: "row", gap: 10, padding: 8, borderWidth: 1, borderColor: "#445069", borderRadius: 9, backgroundColor: "#202a3d" }, copy: { flex: 1 }, selected: { borderColor: "#f2cb68", borderWidth: 2 }, disabled: { opacity: .4 }, name: { color: "#f3f4f7", fontWeight: "800" }, detail: { color: "#9ca7b9", fontSize: 12, marginTop: 2 }, tap: { color: "#d8ad5c", fontSize: 10, marginTop: 4, fontWeight: "700" }, quickWrap: { gap: 8, paddingHorizontal: 9, paddingVertical: 8 }, quickButton: { alignItems: "center", backgroundColor: "#202a3d", borderColor: "#445069", borderRadius: 9, borderWidth: 1, padding: 5, width: 66 }, quickSelected: { backgroundColor: "#3a3440", borderColor: "#f2cb68", borderWidth: 2 }, quickName: { color: "#f3f4f7", fontSize: 9, fontWeight: "800", marginTop: 3, maxWidth: 58 } });
