import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useGameDialog } from "../../components/dialogs/GameDialog";
import { ActionButton, BackButton, EmptyState, Panel, Portrait, SectionTitle, colors } from "../../components/ui";
import { TRAINING_PROGRAMS } from "../../data/training/trainingPrograms";
import { TRAINING_GROUND_CONFIG } from "../../config/trainingConfig";
import { calculateTrainingQuote, getTrainingProgressionLimit, startHeroTraining, startTrainingGroundUpgrade, trainingCapacity } from "../../game/training/trainingService";
import type { TrainingProgramId } from "../../game/training/trainingTypes";
import { useGuild } from "../../state/GuildContext";
import { getRaceNameColor } from "../../ui/raceColors";

export function TrainingGroundsScreen({ onBack, openCalendar }: { onBack(): void; openCalendar(): void }) {
  const { showDialog } = useGameDialog();
  const { guild, updateGuild } = useGuild(); const available = guild.heroes.filter((hero) => hero.isAvailable && hero.currentHP > 0); const [heroId, setHeroId] = useState(available[0]?.id); const [programId, setProgramId] = useState<TrainingProgramId>("sparring_drills");
  const hero = guild.heroes.find((item) => item.id === heroId); const program = TRAINING_PROGRAMS[programId]; const quote = useMemo(() => hero ? calculateTrainingQuote(hero, programId, guild) : undefined, [hero, programId, guild]); const limit = useMemo(() => hero ? getTrainingProgressionLimit(guild, hero) : undefined, [guild, hero]); const capacity = trainingCapacity(guild); const upgrade = TRAINING_GROUND_CONFIG.upgrades[guild.trainingGround.level + 1];
  const begin = () => { if (!hero) return; try { updateGuild(startHeroTraining(guild, hero.id, programId)); showDialog({ title: "Training scheduled", message: `${hero.name} will finish on Day ${guild.currentDay + program.durationDays}.`, tone: "success" }); } catch (error) { showDialog({ title: "Cannot train", message: error instanceof Error ? error.message : "Training could not begin", tone: "danger" }); } };
  const improve = () => { try { updateGuild(startTrainingGroundUpgrade(guild)); } catch (error) { showDialog({ title: "Cannot upgrade", message: error instanceof Error ? error.message : "Upgrade could not begin", tone: "danger" }); } };
  return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.eyebrow}>GUILDHAVEN FACILITY</Text><Text style={styles.title}>Training Hall</Text><Text style={styles.intro}>Use time and gold to help new recruits catch up through XP. Training never increases attributes and cannot replace field experience.</Text>
    <Panel style={styles.facility}><View><Text style={styles.level}>LEVEL {guild.trainingGround.level}</Text><Text style={styles.meta}>{guild.trainingGround.sessions.length}/{capacity} training slots occupied</Text></View>{guild.trainingGround.upgrade ? <Text style={styles.upgrade}>UPGRADING · READY DAY {guild.trainingGround.upgrade.completionDay}</Text> : upgrade ? <ActionButton label={`Upgrade · ${upgrade.goldCost}g · ${upgrade.durationDays}d`} onPress={improve} /> : <Text style={styles.mastered}>MASTER FACILITY</Text>}</Panel>
    {guild.trainingGround.sessions.length ? <><SectionTitle>ACTIVE TRAINING</SectionTitle>{guild.trainingGround.sessions.map((session) => { const trainee = guild.heroes.find((item) => item.id === session.heroId); return <Panel key={session.id} style={styles.session}><Text style={styles.sessionName}>{trainee?.name ?? "Unknown hero"}</Text><Text style={styles.meta}>{TRAINING_PROGRAMS[session.programId].name} · Ready Day {session.completionDay}</Text><Text style={styles.reward}>{session.xpReward} XP</Text></Panel>; })}<ActionButton label="Open Guild Calendar" onPress={openCalendar} /></> : null}
    <SectionTitle>SELECT HERO</SectionTitle>{available.length ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.heroRow}>{available.map((entry) => <Pressable key={entry.id} onPress={() => setHeroId(entry.id)}><Panel style={[styles.hero, heroId === entry.id && styles.selected]}><Portrait hero={entry} size={54} /><Text numberOfLines={1} style={[styles.heroName, { color: getRaceNameColor(entry.raceId) }]}>{entry.name}</Text><Text style={styles.heroMeta}>Lv {entry.level} · Pot. {entry.potentialEstimateMin}–{entry.potentialEstimateMax}</Text></Panel></Pressable>)}</ScrollView> : <EmptyState title="No heroes available" message="Heroes who are injured, dead, gathering, or already training cannot begin another program." />}
    <SectionTitle>PROGRAM</SectionTitle>{Object.values(TRAINING_PROGRAMS).map((entry) => { const locked = guild.trainingGround.level < entry.trainingGroundLevel; return <Pressable key={entry.id} disabled={locked} onPress={() => setProgramId(entry.id)}><Panel style={[styles.program, programId === entry.id && styles.selected, locked && styles.locked]}><View style={styles.programHead}><Text style={styles.programName}>{entry.name}</Text><Text style={styles.duration}>{locked ? `GROUND LV ${entry.trainingGroundLevel}` : `${entry.durationDays} DAY${entry.durationDays === 1 ? "" : "S"}`}</Text></View><Text style={styles.description}>{entry.description}</Text><Text style={styles.meta}>{entry.baseGoldCost} base gold · {entry.baseXp} base XP</Text></Panel></Pressable>; })}
    {hero && quote && limit ? <Panel style={styles.quote}><Text style={styles.quoteTitle}>{hero.name} · {program.name}</Text><Text style={styles.cap}>TRAINING CAP · LEVEL {limit.levelCap}</Text><Text style={styles.capDetail}>Campaign cap {limit.campaignCap} · roster catch-up cap {limit.rosterCap}</Text><Text style={styles.quoteLine}>Cost: {quote.goldCost} gold</Text><Text style={styles.quoteLine}>Expected result: {quote.xpReward} XP</Text><Text style={styles.quoteNote}>Training is an XP-only catch-up system. Surplus XP is not banked beyond the cap.</Text><ActionButton label={`Begin · Ready Day ${guild.currentDay + program.durationDays}`} disabled={guild.trainingGround.sessions.length >= capacity || guild.gold < quote.goldCost || quote.xpReward <= 0} onPress={begin} /></Panel> : null}
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 55 }, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginTop: 8 }, title: { color: colors.text, fontSize: 30, fontWeight: "900", marginTop: 3 }, intro: { color: colors.muted, lineHeight: 20, marginVertical: 9 }, facility: { borderColor: colors.gold, flexDirection: "row", justifyContent: "space-between", alignItems: "center", gap: 10 }, level: { color: colors.gold, fontWeight: "900", fontSize: 18 }, meta: { color: colors.muted, fontSize: 11, marginTop: 4 }, upgrade: { color: colors.gold, fontSize: 10, fontWeight: "900", flex: 1, textAlign: "right" }, mastered: { color: colors.green, fontWeight: "900" }, session: { marginBottom: 7 }, sessionName: { color: colors.text, fontWeight: "900" }, reward: { color: colors.green, fontSize: 11, marginTop: 5 }, heroRow: { gap: 8 }, hero: { width: 128, alignItems: "center" }, selected: { borderColor: colors.gold, borderWidth: 2, backgroundColor: colors.panel2 }, heroName: { fontWeight: "900", marginTop: 5, maxWidth: 108 }, heroMeta: { color: colors.muted, fontSize: 9, marginTop: 3 }, program: { marginBottom: 8 }, locked: { opacity: .45 }, programHead: { flexDirection: "row", justifyContent: "space-between", gap: 10 }, programName: { color: colors.text, fontSize: 16, fontWeight: "900" }, duration: { color: colors.gold, fontSize: 10, fontWeight: "900" }, description: { color: colors.text, lineHeight: 18, marginTop: 6 }, attributes: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, attribute: { backgroundColor: colors.panel, borderColor: colors.border, borderWidth: 1, borderRadius: 8, padding: 11, width: "30%", alignItems: "center" }, attributeSelected: { borderColor: colors.gold, backgroundColor: colors.panel2 }, attributeText: { color: colors.text, fontWeight: "900" }, quote: { marginTop: 18, borderColor: colors.green }, quoteTitle: { color: colors.text, fontSize: 17, fontWeight: "900" }, cap: { color: colors.gold, fontWeight: "900", marginTop: 8 }, capDetail: { color: colors.muted, fontSize: 10, marginTop: 2 }, quoteLine: { color: colors.green, fontWeight: "800", marginTop: 6 }, development: { color: colors.text, fontSize: 11, marginTop: 8 }, warning: { color: colors.danger, fontSize: 11, lineHeight: 16, marginTop: 5 }, quoteNote: { color: colors.muted, fontSize: 10, lineHeight: 15, marginVertical: 9 } });
