import React, { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SkillIcon } from "../../components/skills/SkillIcon";
import { SkillDetailsModal } from "../../components/skills/SkillDetailsModal";
import { ArchiveRewardsPanel } from "../../components/archives/ArchiveRewardsPanel";
import { BackButton, Panel, SectionTitle, SegmentedTabs, colors } from "../../components/ui";
import { CLASSES } from "../../data/classes/classes";
import { ENEMIES } from "../../data/enemies";
import { ENEMY_SKILLS } from "../../data/skills/enemySkills";
import { HERO_SKILLS } from "../../data/skills/heroSkills";
import { SUBCLASSES } from "../../data/subclasses/subclasses";
import { MASTERIES } from "../../data/masteries/masteries";
import { getSkillDescriptionLines } from "../../game/combat/skillDescription";
import type { CombatSkillDefinition } from "../../game/combat/skillTypes";
import { useGuild } from "../../state/GuildContext";
import { formatGameId } from "../../ui/textFormat";

type Tab = "Hero Skills" | "Enemy Abilities";

function SkillTile({ skill, source, onPress }: { skill: CombatSkillDefinition; source: string; onPress(): void }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`Inspect ${skill.name}`} onPress={onPress} style={({pressed})=>[styles.tilePressable,pressed&&styles.pressed]}><Panel style={styles.tile}><SkillIcon skillId={skill.id} size={46} /><Text numberOfLines={2} style={styles.name}>{skill.name}</Text><Text numberOfLines={2} style={styles.meta}>{source}</Text><Text style={styles.type}>{formatGameId(skill.type).toUpperCase()}</Text></Panel></Pressable>;
}

export function SkillCodexScreen({ onBack }: { onBack(): void }) {
  const { guild } = useGuild(); const [tab, setTab] = useState<Tab>("Hero Skills"); const [query,setQuery]=useState(""); const [selectedSkillId,setSelectedSkillId]=useState<string>();
  const heroSources = useMemo(() => { const sources: Record<string, string[]> = {}; for (const heroClass of Object.values(CLASSES)) for (const id of heroClass.skillIds) (sources[id] ??= []).push(heroClass.name); for (const subclass of Object.values(SUBCLASSES)) for (const id of subclass.addedSkillIds) (sources[id] ??= []).push(subclass.name); for (const mastery of Object.values(MASTERIES)) for (const id of mastery.addedSkillIds) (sources[id] ??= []).push(`${mastery.name} mastery`); return sources; }, []);
  const enemyEntries = useMemo(() => { const discovered = new Set(guild.discoveredEnemyIds); const sources: Record<string, string[]> = {}; for (const enemy of Object.values(ENEMIES)) if (discovered.has(enemy.id)) for (const id of enemy.skillIds) (sources[id] ??= []).push(enemy.name); return Object.keys(sources).map((id) => ({ skill: ENEMY_SKILLS[id], source: sources[id]!.join(", ") })).filter((entry): entry is { skill: CombatSkillDefinition; source: string } => Boolean(entry.skill)).sort((a, b) => a.skill.name.localeCompare(b.skill.name)); }, [guild.discoveredEnemyIds]);
  const heroEntries = Object.values(HERO_SKILLS).map((skill) => ({ skill, source: heroSources[skill.id]?.join(", ") ?? "Subclass technique" })).sort((a, b) => a.source.localeCompare(b.source) || a.skill.name.localeCompare(b.skill.name));
  const normalized=query.trim().toLowerCase();const entries = (tab === "Hero Skills" ? heroEntries : enemyEntries).filter(({skill,source})=>!normalized||skill.name.toLowerCase().includes(normalized)||source.toLowerCase().includes(normalized)||skill.type.includes(normalized)); const selectedEntry=entries.find(({skill})=>skill.id===selectedSkillId) ?? (tab==="Hero Skills"?heroEntries:enemyEntries).find(({skill})=>skill.id===selectedSkillId);
  return <><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={styles.content}><BackButton onPress={onBack} /><Text style={styles.eyebrow}>TACTICIAN'S ARCHIVE</Text><Text style={styles.title}>Skills & Abilities</Text><Text style={styles.intro}>A mechanical field guide drawn from the same definitions used in combat. Enemy techniques are recorded when their owners are first encountered.</Text><ArchiveRewardsPanel track="tactics" /><TextInput accessibilityLabel="Search skills and abilities" placeholder="Search skill, class or type…" placeholderTextColor={colors.muted} value={query} onChangeText={setQuery} autoCorrect={false} autoCapitalize="none" returnKeyType="done" submitBehavior="blurAndSubmit" style={styles.search}/><SegmentedTabs values={["Hero Skills", "Enemy Abilities"] as const} value={tab} onChange={(value)=>{setTab(value);setSelectedSkillId(undefined);}} /><SectionTitle>{tab === "Hero Skills" ? `${entries.length} HERO TECHNIQUES` : `${entries.length} DISCOVERED ENEMY TECHNIQUES`}</SectionTitle><View style={styles.entryGrid}>{entries.map(({ skill, source }) => <SkillTile key={skill.id} skill={skill} source={source} onPress={()=>setSelectedSkillId(skill.id)} />)}</View>{!entries.length ? <Panel><Text style={styles.empty}>{query?"No techniques match this search.":"No enemy abilities recorded yet. Meet enemies in tactical combat to reveal their techniques."}</Text></Panel> : null}</ScrollView><SkillDetailsModal visible={Boolean(selectedEntry)} onClose={()=>setSelectedSkillId(undefined)}>{selectedEntry?<Panel style={styles.modalEntry}><View style={styles.modalHead}><SkillIcon skillId={selectedEntry.skill.id} size={58}/><View style={styles.copy}><Text style={styles.modalName}>{selectedEntry.skill.name}</Text><Text style={styles.modalMeta}>{selectedEntry.source} · {formatGameId(selectedEntry.skill.type)}</Text></View></View><View style={styles.details}>{getSkillDescriptionLines(selectedEntry.skill).map((line,index)=><Text key={`${line}-${index}`} style={styles.line}>• {line}</Text>)}</View></Panel>:null}</SkillDetailsModal></>;
}

const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 52 }, search:{backgroundColor:colors.panel,borderColor:colors.border,borderRadius:9,borderWidth:1,color:colors.text,marginBottom:12,minHeight:44,paddingHorizontal:12,paddingVertical:10},entryGrid:{flexDirection:"row",flexWrap:"wrap",gap:8},tilePressable:{flexBasis:"47%",flexGrow:1,minWidth:138},tile:{alignItems:"flex-start",minHeight:146,padding:10},type:{color:colors.gold,fontSize:8,fontWeight:"900",letterSpacing:.6,marginTop:"auto",paddingTop:7},modalEntry:{borderColor:colors.gold,gap:8},modalHead:{alignItems:"center",flexDirection:"row",gap:10},modalName:{color:colors.text,fontSize:19,fontWeight:"900"},modalMeta:{color:colors.gold,fontSize:10,lineHeight:15,marginTop:3}, eyebrow: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 1.8, marginTop: 8 }, title: { color: colors.text, fontSize: 29, fontWeight: "900", marginTop: 3 }, intro: { color: colors.muted, lineHeight: 20, marginVertical: 10 }, entry: { marginBottom: 8, padding: 10 }, head: { alignItems: "center", flexDirection: "row", gap: 11 }, copy: { flex: 1 }, name: { color: colors.text, fontSize: 16, fontWeight: "900" }, meta: { color: colors.gold, fontSize: 10, marginTop: 4 }, chevron: { color: colors.gold, fontSize: 23 }, details: { borderTopColor: colors.border, borderTopWidth: 1, marginTop: 10, paddingTop: 8 }, line: { color: colors.muted, fontSize: 12, lineHeight: 18, marginTop: 3 }, empty: { color: colors.muted, lineHeight: 20, textAlign: "center" }, pressed:{opacity:.76,transform:[{translateY:1}]} });
