import React,{useState}from"react";
import{Pressable,ScrollView,StyleSheet,Text,View}from"react-native";
import{GameIcon}from"../../components/icons/GameIcon";
import{TrophyIcon}from"../../components/renown/TrophyIcon";
import{BackButton,Panel,SegmentedTabs,colors}from"../../components/ui";
import{GUILD_TROPHIES}from"../../data/renown/guildTrophies";
import{createGuildLegacyState,getGuildRank,getNextGuildRank,getUnlockedTrophyIds,toggleDisplayedTrophy,TROPHY_DISPLAY_CAPACITY}from"../../game/renown/guildLegacyService";
import{useGuild}from"../../state/GuildContext";

export function GuildLegacyScreen({onBack}:{onBack():void}){
 const{guild,updateGuild}=useGuild();const[message,setMessage]=useState<string>();const[tab,setTab]=useState<"Renown"|"Trophy Hall">("Renown");const legacy=guild.legacy??createGuildLegacyState();const rank=getGuildRank(guild.reputation);const next=getNextGuildRank(guild.reputation);const unlocked=getUnlockedTrophyIds(guild.world.completedQuestIds);const capacity=rank.benefits.trophyDisplaySlots;const hallUnlocked=capacity>0;const rogueliteWins=Object.values(guild.rogueliteRotation.records).reduce((sum,record)=>sum+record.victories,0);const raidWins=Object.values(guild.raidProgress?.records??{}).reduce((sum,record)=>sum+record.victories,0);const operationBest=Math.max(0,...Object.values(guild.guildOperations.bestSuccessesByOperationId??{}));
 const toggle=(id:string)=>{try{if(!hallUnlocked)throw new Error("Reach Local Company rank at 50 reputation to open the Trophy Hall");const updated=toggleDisplayedTrophy(legacy,id,unlocked,capacity);updateGuild({...guild,legacy:updated});setMessage(updated.displayedTrophyIds.includes(id)?`${GUILD_TROPHIES[id]?.name} placed in the hall.`:`${GUILD_TROPHIES[id]?.name} returned to storage.`);}catch(error){setMessage(error instanceof Error?error.message:"Unable to change display");}};
 const progress=next?Math.min(100,(guild.reputation-rank.reputationRequired)/(next.reputationRequired-rank.reputationRequired)*100):100;
 return <ScrollView contentContainerStyle={styles.content}><BackButton onPress={onBack}/><Text style={styles.eyebrow}>GUILD LEGACY</Text><Text style={styles.title}>Renown & Trophy Hall</Text>
  <SegmentedTabs values={["Renown","Trophy Hall"] as const} value={tab} onChange={setTab}/>{tab==="Renown"&&<><Panel style={styles.rank}><GameIcon id="victory" size={58}/><View style={styles.flex}><Text style={styles.rankName}>{rank.name}</Text><Text style={styles.description}>{rank.description}</Text>{next?<><Text style={styles.progress}>{guild.reputation} / {next.reputationRequired} REPUTATION · NEXT: {next.name.toUpperCase()}</Text><View style={styles.track}><View style={[styles.fill,{width:`${progress}%`}]}/></View></>:<Text style={styles.progress}>MAXIMUM GUILD RANK</Text>}</View></Panel>
  <Text style={styles.section}>ACTIVE RANK BENEFITS</Text><Panel>{rank.unlocks.map((unlock)=><Text key={unlock} style={styles.unlock}>◆ {unlock}</Text>)}<Text style={styles.benefit}>Road encounter pay +{Math.round(rank.benefits.contractGoldModifier*100)}% · Tavern income +{Math.round(rank.benefits.tavernIncomeModifier*100)}%</Text><Text style={styles.benefit}>Quest reputation +{Math.round(rank.benefits.questReputationModifier*100)}% · Displays {capacity}/{TROPHY_DISPLAY_CAPACITY}</Text></Panel>
  <Text style={styles.section}>GUILD RECORDS</Text><View style={styles.records}><Panel style={styles.recordCard}><Text style={styles.recordValue}>{rogueliteWins}</Text><Text style={styles.recordLabel}>ROGUELITE WINS</Text></Panel><Panel style={styles.recordCard}><Text style={styles.recordValue}>{guild.guildOperations.completedCount}</Text><Text style={styles.recordLabel}>OPERATIONS</Text><Text style={styles.recordMeta}>Best {operationBest}/6</Text></Panel><Panel style={styles.recordCard}><Text style={styles.recordValue}>{raidWins}</Text><Text style={styles.recordLabel}>RAID WINS</Text></Panel><Panel style={styles.recordCard}><Text style={styles.recordValue}>{unlocked.length}</Text><Text style={styles.recordLabel}>TROPHIES</Text></Panel></View>
  </>}{tab==="Trophy Hall"&&<><View style={styles.hallHeader}><Text style={styles.section}>DISPLAYED TROPHIES</Text><Text style={styles.slots}>{legacy.displayedTrophyIds.length}/{capacity} ACTIVE</Text></View>{!hallUnlocked&&<Text style={styles.message}>Reach Local Company rank at 50 reputation to use the display hall.</Text>}
  <View style={styles.displayRow}>{Array.from({length:TROPHY_DISPLAY_CAPACITY},(_,index)=>{const slotUnlocked=index<capacity;const id=slotUnlocked?legacy.displayedTrophyIds[index]:undefined;const trophy=id?GUILD_TROPHIES[id]:undefined;return <View key={index} style={[styles.pedestal,!slotUnlocked&&styles.lockedSlot]}>{!slotUnlocked?<><TrophyIcon trophyId="locked" size={40} locked/><Text style={styles.empty}>RANK LOCKED</Text></>:trophy?<><TrophyIcon trophyId={trophy.id} size={48}/><Text numberOfLines={2} style={styles.pedestalName}>{trophy.name}</Text></>:<><View style={styles.emptyCrest}><Text style={styles.emptyCrestText}>+</Text></View><Text style={styles.empty}>EMPTY DISPLAY</Text></>}</View>;})}</View>{message&&<Text style={styles.message}>{message}</Text>}
  <Text style={styles.section}>TROPHY COLLECTION</Text><View style={styles.trophyGrid}>{Object.values(GUILD_TROPHIES).map((trophy)=>{const earned=unlocked.includes(trophy.id);const displayed=legacy.displayedTrophyIds.includes(trophy.id);return <Pressable key={trophy.id} disabled={!earned} onPress={()=>toggle(trophy.id)} style={styles.trophyPressable}><Panel style={[styles.trophy,displayed&&styles.displayed,!earned&&styles.locked]}><View style={styles.trophyTop}><TrophyIcon trophyId={trophy.id} size={46} locked={!earned}/><Text style={displayed?styles.displayTag:styles.collectionTag}>{displayed?"DISPLAYED":earned?"OWNED":"LOCKED"}</Text></View><Text numberOfLines={2} style={styles.trophyName}>{earned?trophy.name:"Undiscovered Trophy"}</Text><Text numberOfLines={2} style={styles.description}>{earned?trophy.description:"Defeat the associated major foe to reveal this trophy."}</Text><Text numberOfLines={2} style={styles.bonus}>{earned?trophy.bonus.label:"BONUS UNKNOWN"}</Text><Text style={styles.action}>{earned?(hallUnlocked?(displayed?"REMOVE":"DISPLAY"):"RANK REQUIRED"):"LOCKED"}</Text></Panel></Pressable>;})}</View>
 </>}</ScrollView>;
}
const styles=StyleSheet.create({content:{padding:16,paddingBottom:60},eyebrow:{color:colors.gold,fontSize:10,fontWeight:"900",letterSpacing:1.6,marginTop:8},title:{color:colors.text,fontSize:29,fontWeight:"900",marginBottom:13,marginTop:3},flex:{flex:1},rank:{alignItems:"center",borderColor:colors.gold,flexDirection:"row",gap:12},rankName:{color:colors.gold,fontSize:21,fontWeight:"900"},description:{color:colors.muted,fontSize:11,lineHeight:16,marginTop:3},progress:{color:colors.text,fontSize:9,fontWeight:"900",marginTop:7},track:{backgroundColor:colors.panel2,borderRadius:4,height:7,marginTop:5,overflow:"hidden"},fill:{backgroundColor:colors.green,height:"100%"},section:{color:colors.gold,fontSize:11,fontWeight:"900",letterSpacing:1.2,marginBottom:8,marginTop:17},unlock:{color:colors.text,fontSize:12,marginVertical:3},benefit:{color:colors.green,fontSize:10,fontWeight:"800",marginTop:6},hallHeader:{alignItems:"flex-end",flexDirection:"row",justifyContent:"space-between"},slots:{color:colors.muted,fontSize:9,fontWeight:"900",marginBottom:8},records:{flexDirection:"row",flexWrap:"wrap",gap:7},recordCard:{alignItems:"center",flexBasis:"47%",flexGrow:1,padding:9},recordValue:{color:colors.text,fontSize:20,fontWeight:"900"},recordLabel:{color:colors.gold,fontSize:7,fontWeight:"900",letterSpacing:.6,marginTop:2},recordMeta:{color:colors.muted,fontSize:8,fontWeight:"800",marginTop:2},displayRow:{flexDirection:"row",flexWrap:"wrap",gap:7},pedestal:{alignItems:"center",backgroundColor:"#141d24",borderBottomColor:colors.gold,borderBottomWidth:3,borderRadius:8,borderWidth:1,borderColor:colors.border,height:83,justifyContent:"center",padding:4,width:"31%"},lockedSlot:{borderBottomColor:colors.border,opacity:.45},emptyCrest:{alignItems:"center",borderColor:colors.border,borderRadius:7,borderStyle:"dashed",borderWidth:1,height:42,justifyContent:"center",width:42},emptyCrestText:{color:colors.muted,fontSize:20,fontWeight:"900"},pedestalName:{color:colors.text,fontSize:8,fontWeight:"900",marginTop:3,textAlign:"center"},empty:{color:colors.muted,fontSize:8,fontWeight:"900",marginTop:3},message:{color:colors.green,fontSize:11,marginTop:10},trophyGrid:{flexDirection:"row",flexWrap:"wrap",gap:8},trophyPressable:{flexBasis:"47%",flexGrow:1,minWidth:138},trophy:{minHeight:175,padding:10},trophyTop:{alignItems:"flex-start",flexDirection:"row",justifyContent:"space-between"},collectionTag:{color:colors.gold,fontSize:7,fontWeight:"900",letterSpacing:.5},displayTag:{color:colors.green,fontSize:7,fontWeight:"900",letterSpacing:.5},displayed:{backgroundColor:"#17251e",borderColor:colors.green},locked:{opacity:.5},trophyName:{color:colors.text,fontSize:17,fontWeight:"900"},bonus:{color:colors.green,fontSize:10,fontWeight:"900",marginTop:5},action:{color:colors.gold,fontSize:8,fontWeight:"900",letterSpacing:.6,marginTop:5}});
