import React, { useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { GameIcon } from "../../components/icons/GameIcon";
import { MaterialIcon } from "../../components/materials/MaterialIcon";
import { ActionButton, EmptyState, Panel, SegmentedTabs, colors } from "../../components/ui";
import { MATERIALS } from "../../data/crafting/materials";
import { equipmentSlotIcon } from "../../data/ui/gameIcons";
import type { ResolvedEquipmentDefinition } from "../../game/equipment/equipmentResolver";
import { useGuild } from "../../state/GuildContext";
import { filterInventory, type InventoryTab } from "../../ui/inventory";

const TABS: InventoryTab[] = ["All", "Weapons", "Armor", "Accessories", "Materials"];
export function InventoryScreen({ openItem, openCrafting, openGathering, openPotions }: { openItem(item: ResolvedEquipmentDefinition): void; openCrafting(): void; openGathering(): void; openPotions(): void }) {
  const { guild } = useGuild(); const [tab, setTab] = useState<InventoryTab>("All"); const items = filterInventory(guild.inventory, tab); const materialCount = Object.values(guild.materials).reduce((sum, amount) => sum + amount, 0); const potionCount = Object.values(guild.potions).reduce((sum, amount) => sum + amount, 0);
  return <ScrollView contentContainerStyle={styles.content}><View style={styles.header}><Text style={styles.title}>Inventory</Text><Text style={styles.count}>{guild.inventory.length} gear | {materialCount} materials | {potionCount} potions</Text></View><View style={styles.actions}><View style={styles.action}><ActionButton label="Workshops" onPress={openCrafting} /></View><View style={styles.action}><ActionButton label="Expeditions" onPress={openGathering} /></View><View style={styles.action}><ActionButton label="Potions" onPress={openPotions} /></View></View><SegmentedTabs values={TABS} value={tab} onChange={setTab}/>{tab === "Materials" ? Object.values(MATERIALS).map((material) => <Panel key={material.id} style={styles.material}><MaterialIcon materialId={material.id} size={56} /><View style={styles.flex}><Text style={styles.name}>{material.name}</Text><Text style={styles.detail}>{material.rarity.toUpperCase()} | {material.description}</Text></View><Text style={styles.quantity}>{guild.materials[material.id]}</Text></Panel>) : items.map((item, index) => <Pressable key={`${item.inventoryKey}-${index}`} onPress={() => openItem(item)}><Panel style={styles.item}><View style={[styles.icon, { borderColor: rarityColor(item.rarity) }]}><GameIcon id={equipmentSlotIcon(item.slot)} size={48} framed={false} /></View><View style={styles.flex}><Text style={styles.name}>{item.name}</Text><Text style={[styles.rarity, { color: rarityColor(item.rarity) }]}>{item.rarity.toUpperCase()} | {item.slot} | Requirement Lv {item.levelRequirement}</Text><Text style={styles.detail}>Value {item.value} | {item.modifiers.map((modifier) => `${modifier.value >= 0 ? "+" : ""}${modifier.operation === "percentage" ? `${modifier.value * 100}%` : modifier.value} ${modifier.target}`).join(" | ")}</Text>{item.enchantmentIds.length > 0 && <Text style={styles.enchanted}>ENCHANTED | {item.enchantmentIds.join(", ").replace(/_/g, " ")}</Text>}</View><Text style={styles.arrow}>{">"}</Text></Panel></Pressable>)}{tab !== "Materials" && !items.length && <EmptyState title="No equipment here" message="Craft gear, complete quests, or send heroes on gathering missions to expand the guild inventory." />}</ScrollView>;
}
function rarityColor(rarity: string) { return rarity === "legendary" ? "#e3a642" : rarity === "epic" ? "#b68be3" : rarity === "rare" ? "#72a9df" : rarity === "uncommon" ? colors.green : colors.muted; }
const styles = StyleSheet.create({ content: { padding: 18, paddingBottom: 40 }, header: { marginBottom: 14 }, title: { color: colors.text, fontSize: 30, fontWeight: "900" }, count: { color: colors.gold, marginTop: 4 }, actions: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginBottom: 14 }, action: { flexGrow: 1, minWidth: "30%" }, flex: { flex: 1 }, item: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 10 }, icon: { width: 52, height: 52, borderRadius: 10, borderWidth: 2, alignItems: "center", justifyContent: "center", backgroundColor: colors.panel2, overflow: "hidden" }, name: { color: colors.text, fontSize: 17, fontWeight: "900" }, rarity: { fontSize: 10, fontWeight: "900", marginTop: 3 }, detail: { color: colors.muted, fontSize: 12, marginTop: 3 }, enchanted: { color: colors.gold, fontSize: 10, fontWeight: "900", marginTop: 4 }, arrow: { color: colors.gold, fontSize: 24 }, material: { flexDirection: "row", alignItems: "center", gap: 11, marginBottom: 8 }, quantity: { color: colors.gold, fontSize: 24, fontWeight: "900" } });
