import { DUNGEONS, DUNGEON_NODES } from "../../data/dungeons/dungeons";
import type { DungeonRunState } from "./dungeonTypes";
import type { HeroCombatInstance } from "../combat/combatTypes";
import type { RandomSource } from "../../utils/random";
export function startDungeonRun(dungeonId: string, modifierIds: string[] = [], partyHeroIds: string[] = [], heroInstances: HeroCombatInstance[] = [], random?: RandomSource): DungeonRunState { const dungeon = DUNGEONS[dungeonId]; if (!dungeon) throw new Error("Unknown dungeon"); if (modifierIds.some((id) => !dungeon.runModifierIds.includes(id))) throw new Error("Invalid dungeon modifier"); const selectedEncounterIds = Object.fromEntries(dungeon.nodeIds.flatMap((nodeId) => { const node = DUNGEON_NODES[nodeId]; const pool = node?.encounterPoolIds ?? []; return pool.length ? [[nodeId, random ? random.pick(pool) : pool[0]!]] : []; })); return { id: `dungeon-${dungeonId}`, dungeonId, currentNodeId: dungeon.startNodeId, selectedEncounterIds, visitedNodeIds: [], resolvedNodeIds: [], selectedModifierIds: [...new Set(modifierIds)], partyHeroIds: [...new Set(partyHeroIds)], heroInstances, goldEarned: 0, xpEarnedPerHero: 0, recipeIdsUnlocked: [], lastResolutionText: null, status: "active" }; }
export function isCurrentDungeonNodeResolved(run: DungeonRunState): boolean { return run.resolvedNodeIds.includes(run.currentNodeId); }
export function availableDungeonNodeIds(run: DungeonRunState): string[] { return run.status === "active" && isCurrentDungeonNodeResolved(run) ? DUNGEON_NODES[run.currentNodeId]?.nextNodeIds ?? [] : []; }
export function chooseDungeonNode(run: DungeonRunState, nodeId: string): DungeonRunState { if (!availableDungeonNodeIds(run).includes(nodeId)) throw new Error("Dungeon node is not connected to the current route"); return { ...run, currentNodeId: nodeId, visitedNodeIds: [...run.visitedNodeIds, run.currentNodeId], lastResolutionText: null }; }
export function markDungeonNodeResolved(run: DungeonRunState, resolutionText: string): DungeonRunState { if (run.status !== "active") throw new Error("Dungeon run is not active"); const node = DUNGEON_NODES[run.currentNodeId]; if (!node) throw new Error("Unknown dungeon node"); return { ...run, resolvedNodeIds: [...new Set([...run.resolvedNodeIds, node.id])], lastResolutionText: resolutionText, status: node.type === "boss" ? "victory" : "active" }; }
